# Video Game Sales and Ratings Data

##### This dataset provides comprehensive data on video game sales, ratings, and user insights globally, including details such as the game's name, platform, year of release, genre, publisher, sales in different regions, critic and user scores, and ESRB rating.

###  Column Descriptions

| Column | Description |
|--------|------------|
| Index | Unique identifier for each video game record. |
| Name | The name of the video game.|
| Platform | The platform on which the game is available, such as PC, PS4, Xbox, etc. |
| Year_of_Release | The year in which the game was released. |
| Genre | The genre of the game, such as Action, Sports, etc.|
| Publisher|  The company that published the game.  |
| NA_Sales| The sales of the game in North America, in millions. |
| EU_Sales| The sales of the game in Europe, in millions.|
| JP_Sales| The sales of the game in Japan, in millions. |
| Other_Sales| The sales of the game in other regions, in millions.|
| Global_Sales| The total global sales of the game, in millions. |
| Critic_Score| The average score given to the game by critics.|
| Critic_Count| The number of critics who reviewed the game.|
| User_Score| The number of critics who reviewed the game.|
| User_Count | The average score given to the game by users.|
| Developer| The company that developed the game.|
| Rating| The ESRB rating of the game, such as E for Everyone, T for Teen, or M for Mature.|

###  Import core libraries for data analysis and visualization.

In [104]:
import numpy as np
import pandas as pd
import plotly.express as px 
import matplotlib.pyplot as plt
import datetime

##### Override default color sequence globally

In [105]:
my_colors= [
    "#4B0082",  # deep purple (low values)
    "#9B59B6",  # lighter purple
    "#00A86B",  # emerald green (mid values)
    "#2ECC71",  # lighter green
    "#BDC3C7"   # light gray (high values)
]
px.defaults.color_discrete_sequence = my_colors

### Load and Explore Data

In [106]:
# Load the dataset.
df=pd.read_csv("Video_Games.csv")
df.head()

,index,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

### Data Cleaning & Quality

In [107]:
# Convert all column names in the DataFrame to lowercase to ensures consistency and avoids issues with case sensitivity.
df.columns= df.columns.str.lower()
df.columns

Index(['index', 'name', 'platform', 'year_of_release', 'genre', 'publisher',
       'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales',
       'critic_score', 'critic_count', 'user_score', 'user_count', 'developer',
       'rating'],
      dtype='object')

#### Check Data Types

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16928 entries, 0 to 16927
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            16928 non-null  int64
 1   name             16926 non-null  object
 2   platform         16928 non-null  object
 3   year_of_release  16655 non-null  float64
 4   genre            16926 non-null  object
 5   publisher        16873 non-null  object
 6   na_sales         16928 non-null  float64
 7   eu_sales         16928 non-null  float64
 8   jp_sales         16928 non-null  float64
 9   other_sales      16928 non-null  float64
 10  global_sales     16928 non-null  float64
 11  critic_score     8260 non-null   float64
 12  critic_count     8260 non-null   float64
 13  user_score       10159 non-null  object
 14  user_count       7718 non-null   float64
 15  developer        10240 non-null  object
 16  rating           10092 non-null  object
dtypes: float64(9), int64(1), object(7)
memory usage: 2.2+ MB

In [109]:
df.shape

(16928, 17)

#### Check the Missing values

In [110]:
# Check the number of missing values in each column.
df.isna().sum().sort_values(ascending=False)

user_count         9210
critic_score       8668
critic_count       8668
rating             6836
user_score         6769
developer          6688
year_of_release     273
publisher            55
name                  2
genre                 2
index                 0
na_sales              0
platform              0
jp_sales              0
eu_sales              0
other_sales           0
global_sales          0
dtype: int64

In [111]:
(df.isna().mean()*100).sort_values(ascending=False)

user_count         54.406900
critic_score       51.205104
critic_count       51.205104
rating             40.382798
user_score         39.987004
developer          39.508507
year_of_release     1.612713
publisher           0.324905
name                0.011815
genre               0.011815
index               0.000000
na_sales            0.000000
platform            0.000000
jp_sales            0.000000
eu_sales            0.000000
other_sales         0.000000
global_sales        0.000000
dtype: float64

In [112]:
# Drop all columns that have more than 50% missing values
drop_col=['index','critic_score', 'critic_count', 'user_count']  # no need for index and >50% missing values
# Remove unwanted Columns
df.drop(columns=drop_col,axis=1,inplace=True)  
df.columns

Index(['name', 'platform', 'year_of_release', 'genre', 'publisher', 'na_sales',
       'eu_sales', 'jp_sales', 'other_sales', 'global_sales', 'user_score',
       'developer', 'rating'],
      dtype='object')

In [113]:
# Drop rows if missing values less than 5% of total dataset:
# Drop rows (with missing key fields) 
df.dropna(subset=['rating','user_score','developer','year_of_release','publisher','name','genre'])

# Percentage of rows retained 
retained=((df.dropna(subset=['rating','user_score','developer','year_of_release','publisher','name','genre'])).shape[0]/df.shape[0])*100
# Will be removed if it's less than 5%
100- retained

41.847826086956516

In [114]:
df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,8,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,8,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN

#### Check the Duplicates

In [115]:
# Check the duplicated data.
df.duplicated().sum()

np.int64(209)

In [116]:
# Remove duplicates.
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

#### Check the Outliers

In [117]:
from datasist.structdata import detect_outliers                          
for col in df.select_dtypes(include = 'number').columns :                      # Check Outliers only in numerical columns
    outliers = detect_outliers(data = df, n = 0 ,features = [col])
    print(col)
    print(outliers)
    print('-'*50)

year_of_release
[]
--------------------------------------------------
na_sales
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 245, 246, 247, 248, 249, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 317, 318, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 339, 341, 342, 343, 344, 345, 346, 347, 348, 350, 351, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 378, 379, 380, 381, 382, 383, 386, 387, 388, 389, 390, 391, 392, 394, 395, 396, 397, 398, 399, 400, 401, 402, 404, 405, 407, 408, 409, 410, 411, 413, 414, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 499, 500, 501, 502, 503, 504, 505, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 522, 523, 524, 525, 527, 528, 529, 531, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 564, 565, 567, 568, 569, 570, 572, 573, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 586, 587, 588, 589, 590, 591, 593, 594, 595, 596, 597, 599, 600, 601, 603, 604, 605, 606, 607, 608, 609, 610, 612, 613, 614, 616, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 633, 634, 635, 636, 637, 638, 640, 641, 642, 643, 644, 645, 647, 648, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 688, 689, 690, 692, 693, 695, 696, 700, 701, 702, 704, 705, 706, 707, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 724, 725, 726, 727, 728, 729, 730, 731, 732, 734, 735, 736, 737, 738, 739, 741, 742, 743, 744, 745, 746, 747, 748, 749, 751, 753, 755, 756, 758, 759, 760, 761, 762, 763, 764, 766, 767, 769, 770, 771, 773, 775, 776, 777, 778, 779, 780, 781, 782, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 795, 796, 797, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 815, 816, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 829, 830, 831, 832, 833, 834, 835, 836, 837, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 850, 851, 853, 854, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 884, 886, 887, 888, 889, 890, 891, 892, 894, 895, 896, 897, 898, 899, 900, 901, 902, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 920, 921, 922, 923, 925, 927, 929, 930, 931, 932, 933, 934, 936, 937, 939, 940, 941, 942, 945, 946, 947, 948, 949, 950, 951, 952, 954, 955, 956, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 969, 970, 971, 972, 973, 974, 975, 977, 978, 979, 981, 982, 984, 986, 987, 989, 990, 991, 992, 993, 994, 995, 996, 998, 999, 1000, 1001, 1003, 1004, 1005, 1007, 1009, 1010, 1011, 1012, 1014, 1016, 1017, 1018, 1019, 1020, 1022, 1024, 1025, 1026, 1027, 1029, 1030, 1032, 1033, 1034, 1036, 1037, 1038, 1039, 1041, 1042, 1043, 1044, 1045, 1047, 1048, 1049, 1050, 1052, 1054, 1056, 1057, 1058, 1059, 1060, 1061, 1063, 1064, 1065, 1066, 1067, 1068, 1070, 1071, 1072, 1073, 1074, 1075, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1110, 1111, 1112, 1113, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1125, 1126, 1128, 1129, 1130, 1132, 1133, 1134, 1136, 1137, 1138, 1140, 1141, 1142, 1144, 1145, 1147, 1149, 1150, 1151, 1152, 1154, 1156, 1157, 1158, 1159, 1161, 1162, 1163, 1164, 1166, 1167, 1168, 1169, 1170, 1171, 1173, 1174, 1176, 1178, 1179, 1180, 1181, 1183, 1184, 1185, 1187, 1188, 1189, 1190, 1191, 1193, 1194, 1195, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1206, 1207, 1209, 1211, 1212, 1214, 1215, 1217, 1218, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1231, 1232, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1245, 1246, 1248, 1250, 1254, 1256, 1257, 1259, 1261, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1274, 1277, 1278, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1292, 1293, 1294, 1295, 1296, 1298, 1299, 1300, 1301, 1303, 1304, 1305, 1306, 1308, 1310, 1311, 1312, 1314, 1315, 1321, 1322, 1323, 1324, 1325, 1326, 1329, 1330, 1332, 1333, 1334, 1335, 1336, 1337, 1340, 1341, 1343, 1345, 1346, 1347, 1348, 1349, 1350, 1352, 1353, 1356, 1357, 1359, 1360, 1362, 1363, 1365, 1366, 1367, 1369, 1371, 1372, 1373, 1374, 1375, 1377, 1379, 1380, 1382, 1387, 1389, 1390, 1392, 1393, 1396, 1397, 1398, 1400, 1401, 1404, 1405, 1406, 1407, 1409, 1410, 1412, 1414, 1419, 1420, 1421, 1422, 1426, 1427, 1430, 1431, 1432, 1433, 1434, 1438, 1439, 1444, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1476, 1477, 1478, 1480, 1482, 1484, 1486, 1487, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1498, 1499, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1513, 1514, 1515, 1519, 1522, 1524, 1525, 1526, 1527, 1528, 1529, 1531, 1533, 1534, 1535, 1536, 1537, 1540, 1542, 1543, 1545, 1547, 1548, 1549, 1553, 1554, 1555, 1556, 1557, 1558, 1560, 1562, 1563, 1564, 1565, 1566, 1568, 1571, 1577, 1581, 1582, 1585, 1586, 1587, 1590, 1591, 1592, 1593, 1597, 1599, 1601, 1602, 1604, 1605, 1607, 1609, 1610, 1611, 1612, 1615, 1616, 1617, 1621, 1623, 1625, 1626, 1629, 1630, 1636, 1640, 1641, 1643, 1645, 1646, 1647, 1648, 1651, 1652, 1653, 1655, 1657, 1659, 1661, 1663, 1666, 1667, 1669, 1670, 1675, 1679, 1684, 1685, 1688, 1689, 1692, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1702, 1703, 1704, 1706, 1707, 1709, 1714, 1715, 1718, 1719, 1722, 1728, 1732, 1735, 1736, 1738, 1739, 1741, 1747, 1749, 1751, 1752, 1755, 1764, 1776, 1778, 1780, 1786, 1789, 1790, 1792, 1793, 1797, 1798, 1800, 1802, 1803, 1805, 1807, 1808, 1811, 1813, 1815, 1818, 1823, 1825, 1827, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1840, 1841, 1842, 1847, 1850, 1851, 1853, 1854, 1872, 1875, 1876, 1877, 1881, 1882, 1883, 1884, 1888, 1889, 1890, 1894, 1895, 1899, 1901, 1902, 1905, 1908, 1909, 1910, 1914, 1915, 1917, 1922, 1923, 1927, 1937, 1940, 1948, 1949, 1950, 1953, 1955, 1957, 1958, 1959, 1964, 1965, 1967, 1968, 1969, 1976, 1977, 1991, 1994, 2002, 2007, 2010, 2014, 2016, 2020, 2021, 2023, 2024, 2025, 2029, 2031, 2033, 2035, 2037, 2044, 2046, 2049, 2059, 2062, 2063, 2064, 2067, 2076, 2077, 2078, 2079, 2080, 2086, 2087, 2091, 2092, 2102, 2103, 2104, 2106, 2107, 2111, 2112, 2113, 2114, 2116, 2118, 2122, 2124, 2127, 2131, 2133, 2142, 2150, 2153, 2158, 2162, 2165, 2166, 2174, 2176, 2177, 2183, 2184, 2187, 2191, 2193, 2195, 2199, 2201, 2203, 2207, 2211, 2212, 2217, 2218, 2220, 2224, 2226, 2227, 2228, 2233, 2242, 2244, 2245, 2247, 2253, 2254, 2256, 2259, 2269, 2277, 2280, 2281, 2284, 2286, 2294, 2295, 2307, 2309, 2310, 2311, 2316, 2317, 2320, 2321, 2322, 2324, 2325, 2332, 2334, 2350, 2352, 2366, 2372, 2376, 2377, 2382, 2388, 2391, 2394, 2400, 2408, 2421, 2431, 2433, 2439, 2448, 2452, 2456, 2458, 2468, 2473, 2475, 2476, 2479, 2484, 2485, 2491, 2501, 2504, 2505, 2506, 2507, 2509, 2510, 2513, 2514, 2515, 2516, 2531, 2532, 2540, 2543, 2544, 2551, 2556, 2557, 2571, 2576, 2578, 2579, 2580, 2584, 2589, 2594, 2595, 2602, 2605, 2615, 2619, 2628, 2630, 2632, 2634, 2640, 2645, 2648, 2649, 2650, 2656, 2670, 2678, 2680, 2698, 2715, 2729, 2733, 2736, 2740, 2750, 2754, 2761, 2777, 2779, 2805, 2807, 2808, 2835, 2837, 2844, 2845, 2846, 2849, 2854, 2862, 2863, 2864, 2870, 2885, 2893, 2901, 2927, 2935, 2948, 2972, 2976, 2992, 3021, 3068]
--------------------------------------------------
eu_sales

#### Check Inconsistent Values

In [118]:
df.describe(include = 'number').round(2)          # Check for numerical

,year_of_release,na_sales,eu_sales,jp_sales,other_sales,global_sales
count,16450.00,16719.00,16719.00,16719.00,16719.00,16719.00
mean,2006.49,0.26,0.15,0.08,0.05,0.53
std,5.88,0.81,0.50,0.31,0.19,1.55
min,1980.00,0.00,0.00,0.00,0.00,0.01
25%,2003.00,0.00,0.00,0.00,0.00,0.06
50%,2007.00,0.08,0.02,0.00,0.01,0.17
75%,2010.00,0.24,0.11,0.04,0.03,0.47
max,2020.00,41.36,28.96,10.22,10.57,82.53

In [119]:
df.describe(include = 'object')        # Check for Categorical

,name,platform,genre,publisher,user_score,developer,rating
count,16717,16719,16717,16665,10015,10096,9950
unique,11562,31,12,581,96,1696,8
top,Need for Speed: Most Wanted,PS2,Action,Electronic Arts,tbd,Ubisoft,E
freq,12,2161,3370,1356,2425,204,3991

In [120]:
# New list excluded the dropped features.

cols = df.columns.tolist() # Identify columns in the DataFrame

# Define the dropped features
dropped_features = ['user_count', 'critic_score', 'critic_count'] 

# Keep only columns that are not dropped
final_cols = [col for col in cols if col not in dropped_features]

print("Final columns:", final_cols)

Final columns: ['name', 'platform', 'year_of_release', 'genre', 'publisher', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales', 'user_score', 'developer', 'rating']

#### Check Unique Values and Value Counts

In [121]:
# Inspect categorical cols: name, unique count, and unique values.
for col in df.select_dtypes(include = 'object').columns : 
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

name
11562
['Wii Sports' 'Super Mario Bros.' 'Mario Kart Wii' ...
 'Woody Woodpecker in Crazy Castle 5' 'LMA Manager 2007'
 'Haitaka no Psychedelica']
 ****************************************************************************************************
platform
31
['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' 'PS4' '3DS' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'WiiU' 'GC' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']
 ****************************************************************************************************
genre
12
['Sports' 'Platform' 'Racing' 'Role-Playing' 'Puzzle' 'Misc' 'Shooter'
 'Simulation' 'Action' 'Fighting' 'Adventure' 'Strategy' nan]
 ****************************************************************************************************
publisher
581
['Nintendo' 'Microsoft Game Studios' 'Take-Two Interactive'
 'Sony Computer Entertainment' 'Activision' 'Ubisoft' 'Bethesda Softworks'
 'Electronic Arts' 'Sega' 'SquareSoft' 'Atari' '505 Games' 'Capcom'
 'GT Interactive' 'Konami Digital Entertainment' 'Square Enix'
 'Sony Computer Entertainment Europe' 'Virgin Interactive' 'LucasArts'
 'Warner Bros. Interactive Entertainment' 'Universal Interactive'
 'Eidos Interactive' 'RedOctane' 'Vivendi Games' 'Enix Corporation'
 'Namco Bandai Games' 'Palcom' 'Hasbro Interactive' 'THQ'
 'Fox Interactive' 'Acclaim Entertainment' 'MTV Games'
 'Disney Interactive Studios' nan 'Codemasters' 'Majesco Entertainment'
 'Red Orb' 'Level 5' 'Arena Entertainment' 'Midway Games' 'JVC'
 'Deep Silver' 'NCSoft' '989 Studios' 'UEP Systems' 'Parker Bros.' 'Maxis'
 'Imagic' 'Tecmo Koei' 'ASCII Entertainment' 'Valve Software' 'Mindscape'
 'Infogrames' 'Unknown' 'Square' 'Valve' 'Banpresto' 'Hello Games'
 'D3Publisher' 'Activision Value' 'Oxygen Interactive'
 'Red Storm Entertainment' 'Video System' 'Global Star' 'Gotham Games'
 'Westwood Studios' 'GungHo' 'Crave Entertainment' 'Hudson Soft' 'Coleco'
 'Rising Star Games' 'TDK Mediactive' 'ASC Games' 'Accolade' 'Zoo Games'
 'Sony Online Entertainment' '3DO' 'Natsume' 'RTL' 'Alchemist'
 'Black Label Games' 'SouthPeak Games' 'Focus Home Interactive' 'Ocean'
 'Zoo Digital Publishing' 'Psygnosis' 'City Interactive'
 'Empire Interactive' 'Success' 'Compile' 'Russel' 'Atlus' 'Mastertronic'
 'Slightly Mad Studios' 'Taito' 'Agetec' 'Microprose' 'Play It' 'GSP'
 'Tomy Corporation' 'Sammy Corporation' 'Koch Media' 'Game Factory'
 'Titus' 'Marvelous Entertainment' 'Genki' 'Mojang' 'CTO SpA' 'TalonSoft'
 'Crystal Dynamics' 'Square Enix ' 'mixi, Inc' 'Pinnacle' 'SCi' 'Quelle'
 'Rage Software' 'Ubisoft Annecy' 'Interplay' 'Scholastic Inc.' 'Mystique'
 'ChunSoft' 'Square EA' '20th Century Fox Video Games'
 'Hudson Entertainment' 'Men-A-Vision' 'Nobilis' 'Avanquest Software'
 'Big Ben Interactive' 'Nordic Games' 'Touchstone' 'Spike'
 'Nippon Ichi Software' 'Sony Computer Entertainment America'
 'Jester Interactive' 'LEGO Media' 'Quest' 'Illusion Softworks'
 'Tigervision' 'Rocket Company' 'Metro 3D' 'Mattel Interactive'
 'IE Institute' 'Funbox Media' 'Rondomedia' 'Universal Gamex' 'Ghostlight'
 'Wizard Video Games' 'BMG Interactive Entertainment' 'PQube'
 'Trion Worlds' 'Xseed Games' 'Laguna' 'Takara' 'Ignition Entertainment'
 'Kadokawa Shoten' 'Enterbrain' 'Imagineer' 'CPG Products'
 'System 3 Arcade Software' 'Aruze Corp' 'Destineer' 'Gamebridge'
 'Midas Interactive Entertainment' 'Jaleco' 'Answer Software'
 'Pack In Soft' 'XS Games' 'Rebellion' 'Ultravision'
 'Harmonix Music Systems' 'Activision Blizzard' 'Xplosiv' 'Wanadoo'
 'Telltale Games' 'NovaLogic' 'Epoch' 'BAM! Entertainment'
 'GameMill Entertainment' 'Knowledge Adventure' 'Tetris Online' 'Mastiff'
 'ESP' 'TYO' 'Telegames' 'Mud Duck Productions' 'Screenlife' 'Pioneer LDC'
 'Magical Company' 'Kemco' 'Mentor Interactive' 'Human Entertainment'
 'Data Age' 'Electronic Arts Victor' 'Jack of All Games' 'Avanquest'
 'Black Bean Games' '989 Sports' 'Takara Tomy' 'Media Rings' 'Elf'
 'Starfish' 'Zushi Games' 'Jorudan' 'Destination Software, Inc' 'New'
 'Brash Entertainment' 'Kalypso Media' 'ITT Family Games' 'Ackkstudios'
 'PopCap Games' 'Starpath Corp.' 'BPS' 'Gathering of Developers'
 'NewKidCo' 'Marvelous Interactive' 'Storm City Games' 'CokeM Interactive'
 'P2 Games' 'CBS Electronics' 'Home Entertainment Suppliers' 'Magix'
 'Arc System Works' 'Angel Studios' 'Wargaming.net' 'Playmates'
 'SNK Playmore' 'Hamster Corporation' 'From Software' 'Nippon Columbia'
 'Nichibutsu' 'Conspiracy Entertainment' 'Hect' 'Mumbo Jumbo'
 'DTP Entertainment' 'Pacific Century Cyber Works' 'Indie Games'
 'Liquid Games' 'NEC' 'Axela' 'ArtDink' 'Sunsoft' 'Little Orbit' 'FuRyu'
 'Gust' 'SNK' 'NEC Interchannel' 'Nihon Falcom Corporation'
 'Xing Entertainment' 'ValuSoft' 'Victor Interactive' 'American Softworks'
 'Falcom Corporation' 'Detn8 Games' 'Bomb' 'Nordcurrent'
 'Milestone S.r.l.' 'AQ Interactive' 'Sears' 'Seta Corporation'
 'On Demand' 'CCP' 'NCS' 'Rebellion Developments' 'Agatsuma Entertainment'
 'Gremlin Interactive Ltd' 'Aspyr' 'Compile Heart' 'Culture Brain'
 'Mad Catz' 'Shogakukan' 'Merscom LLC' 'JoWood Productions'
 'Nippon Telenet' 'TDK Core' 'Kadokawa Games' 'SSI' 'Foreign Media Games'
 'Core Design Ltd.' 'bitComposer Games' 'Astragon' 'Asylum Entertainment'
 'Performance Designed Products' 'UFO Interactive' 'Essential Games'
 'Adeline Software' 'Funcom' 'PlayV' 'Panther Software'
 'Blast! Entertainment Ltd' 'Playlogic Game Factory' 'DSI Games'
 'Avalon Interactive' 'Game Life' 'Popcorn Arcade' 'Aques' 'System 3'
 'Syscom' 'Vir2L Studios' 'Vatical Entertainment' 'Neko Entertainment'
 'White Park Bay Software' 'Vic Tokai' 'Media Factory' 'Daedalic'
 'Game Arts' 'The Adventure Company' 'EA Games' 'Acquire' 'Broccoli'
 'General Entertainment' 'Paradox Interactive' 'Yacht Club Games' 'Imadio'
 'Swing! Entertainment' 'Sony Music Entertainment' 'Aqua Plus'
 'Excalibur Publishing' 'Hip Interactive' 'Tripwire Interactive'
 'DreamCatcher Interactive' 'SCS Software' 'Havas Interactive' 'Sting'
 'Idea Factory' 'Telstar' 'U.S. Gold' 'Funsta' 'DreamWorks Interactive'
 'Slitherine Software' 'MTO' 'Graffiti' 'Tru Blu Entertainment'
 'DHM Interactive' 'Crytek' 'FunSoft' 'Data Design Interactive' 'SPS'
 'Moss' 'T&E Soft' 'NDA Productions' 'Bigben Interactive' 'Data East'
 'Idea Factory International' 'Time Warner Interactive'
 'Gainax Network Systems' 'Daito' 'O3 Entertainment' 'O-Games' 'Gameloft'
 'Xicat Interactive' 'Simon & Schuster Interactive' 'Valcon Games'
 'PopTop Software' 'TOHO' 'PM Studios' 'Bohemia Interactive'
 'Reef Entertainment' '5pb' 'HMH Interactive' 'inXile Entertainment'
 'Cave' 'Microids' 'Paon' 'CDV Software Entertainment' 'Micro Cabin'
 'GameTek' 'Benesse' 'Type-Moon' 'Enjoy Gaming ltd.' 'Asmik Corp'
 'Interplay Productions' 'Asmik Ace Entertainment' 'Image Epoch'
 'Phantom EFX' 'Evolved Games' 'responDESIGN' 'Griffin International'
 'Culture Publishers' 'Hackberry' 'Hearty Robin' 'Nippon Amuse'
 'Origin Systems' 'Seventh Chord' 'Abylight' 'Mitsui' 'Insomniac Games'
 'Flight-Plan' 'Milestone' 'Glams' 'Aksys Games' 'Locus' 'Warp'
 'Irem Software Engineering' 'Myelin Media' 'Global A Entertainment'
 'Alternative Software' 'Mercury Games' 'Sunrise Interactive' 'Elite'
 'Evolution Games' 'Daedalic Entertainment' 'Edia' 'Athena' 'Aria'
 'Tivola' 'Happinet' 'Tommo' 'Altron' 'Revolution Software' 'Media Works'
 'Fortyfive' 'Gamecock' 'Imax' '10TACLE Studios' 'Groove Games'
 'Pack-In-Video' 'Crimson Cow' 'iWin' 'Asgard' 'Ecole' 'Yumedia'
 'Ascaron Entertainment GmbH' 'HAL Laboratory' 'Phenomedia'
 'Grand Prix Games' 'DigiCube' 'Creative Core' 'Kaga Create'
 'WayForward Technologies' 'LSP Games' 'ASCII Media Works' '1C Company'
 'Coconuts Japan' 'Arika' 'Marvel Entertainment' 'Ertain' 'Prototype'
 'Phantagram' 'The Learning Company' 'TechnoSoft' 'MLB.com' 'Vap' 'Misawa'
 'Yeti' 'Dusenberry Martin Racing' 'Navarre Corp' 'Pow' 'MediaQuest'
 'Team17 Software' 'Max Five' 'Tradewest' 'Comfort' 'Milestone S.r.l'
 'Pony Canyon' 'Riverhillsoft' 'Summitsoft' 'Playmore' 'Kool Kizz'
 'Monte Christo Multimedia' 'TopWare Interactive' 'Legacy Interactive'
 'Cloud Imperium Games Corporation' 'Flashpoint Games' 'CyberFront'
 'Alawar Entertainment' 'Societa' 'Interchannel' 'Experience Inc.'
 'Sonnet' 'Virtual Play Games' 'Zenrin' 'Iceberg Interactive' 'Ivolgamus'
 'MC2 Entertainment' '2D Boy' 'Games Workshop' 'Kando Games'
 'Office Create' 'Maximum Family Games' 'Fields' 'Gearbox Software'
 'Princess Soft' 'Extreme Entertainment Group' 'Big Fish Games' 'Berkeley'
 'Mamba Games' 'Fuji' 'FuRyu Corporation' 'Her Interactive'
 'imageepoch Inc.' 'Just Flight' 'Kamui' 'ASK' 'Cygames'
 'Introversion Software' '49Games' 'KSS' 'dramatic create' 'TGL' 'KID'
 'Quinrose' 'Sold Out' 'Encore' 'G.Rev' 'Sunflowers' 'Headup Games'
 'Sweets' 'Kokopeli Digital Studios' 'id Software' 'Nexon' 'BushiRoad'
 'Devolver Digital' 'Number None' 'Tryfirst' 'GN Software' "Yuke's"
 'Strategy First' 'Lexicon Entertainment' 'Paon Corporation'
 'Kids Station' 'Licensed 4U' 'GOA' '7G//AMES' 'King Records'
 'Minato Station' 'Graphsim Entertainment' 'Easy Interactive' 'Gaga'
 'Yamasa Entertainment' 'Plenty' 'Views' 'Blue Byte' 'fonfun' 'NetRevo'
 'Epic Games' 'Quintet' 'Focus Multimedia' 'Phoenix Games'
 'Marvelous Games' 'Dorart' 'Codemasters Online' 'Stainless Games'
 'Aerosoft' 'Imageworks' 'Karin Entertainment' 'Technos Japan Corporation'
 'Masque Publishing' 'Gakken' 'New World Computing' 'Mirai Shounen'
 'Datam Polystar' 'HuneX' 'Visco' 'Saurus' 'Revolution (Japan)' 'Giza10'
 'Alvion' 'Giga' 'Mycom' 'Warashi' 'System Soft' 'RED Entertainment'
 'Lighthouse Interactive' 'Michaelsoft' 'Media Entertainment'
 'Genterprise' 'Interworks Unlimited, Inc.' 'Inti Creates' 'Boost On'
 'EON Digital Entertainment' 'Nitroplus' 'Naxat Soft' 'Piacci'
 'Paradox Development' 'Otomate' 'Ascaron Entertainment' 'Ongakukan'
 'Commseed' 'UIG Entertainment' 'Takuyo' 'Interchannel-Holon'
 'Red Flagship']
 ****************************************************************************************************
user_score
96
['8' nan '8.3' '8.5' '6.6' '8.4' '8.6' '7.7' '6.3' '7.4' '8.2' '9' '7.9'
 '8.1' '8.7' '7.1' '3.4' '5.3' '4.8' '3.2' '8.9' '6.4' '7.8' '7.5' '2.6'
 '7.2' '9.2' '7' '7.3' '4.3' '7.6' '5.7' '5' '9.1' '6.5' 'tbd' '8.8' '6.9'
 '9.4' '6.8' '6.1' '6.7' '5.4' '4' '4.9' '4.5' '9.3' '6.2' '4.2' '6' '3.7'
 '4.1' '5.8' '5.6' '5.5' '4.4' '4.6' '5.9' '3.9' '3.1' '2.9' '5.2' '3.3'
 '4.7' '5.1' '3.5' '2.5' '1.9' '3' '2.7' '2.2' '2' '9.5' '2.1' '3.6' '2.8'
 '1.8' '3.8' '0' '1.6' '9.6' '2.4' '1.7' '1.1' '0.3' '1.5' '0.7' '1.2'
 '2.3' '0.5' '1.3' '0.2' '0.6' '1.4' '0.9' '1' '9.7']
 ****************************************************************************************************
developer
1696
['Nintendo' nan 'Good Science Studio' ... 'Big Red Software'
 'Atomic Games' 'Interchannel-Holon']
 ****************************************************************************************************
rating
8
['E' nan 'M' 'T' 'E10+' 'K-A' 'AO' 'EC' 'RP']
 ****************************************************************************************************

In [122]:
# Inspect numerical cols: name, unique count, and unique values.
for col in df.select_dtypes(include = 'number').columns:   
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

year_of_release
39
[2006. 1985. 2008. 2009. 1996. 1989. 1984. 2005. 1999. 2007. 2010. 2013.
 2004. 1990. 1988. 2002. 2001. 2011. 1998. 2015. 2012. 2014. 1992. 1997.
 1993. 1994. 1982. 2016. 2003. 1986. 2000.   nan 1995. 1991. 1981. 1987.
 1980. 1983. 2020. 2017.]
 ****************************************************************************************************
na_sales
402
[4.136e+01 2.908e+01 1.568e+01 1.561e+01 1.127e+01 2.320e+01 1.128e+01
 1.396e+01 1.444e+01 2.693e+01 9.050e+00 9.710e+00 9.000e+00 8.920e+00
 1.500e+01 9.010e+00 7.020e+00 9.430e+00 1.278e+01 4.740e+00 6.380e+00
 1.083e+01 9.540e+00 9.660e+00 8.410e+00 6.060e+00 3.430e+00 5.510e+00
 6.850e+00 9.040e+00 5.890e+00 6.030e+00 9.700e+00 5.280e+00 4.990e+00
 8.250e+00 8.520e+00 5.540e+00 6.990e+00 6.620e+00 5.030e+00 5.990e+00
 3.960e+00 2.500e+00 7.970e+00 6.910e+00 4.340e+00 4.350e+00 3.010e+00
 6.160e+00 6.760e+00 4.020e+00 4.890e+00 2.960e+00 4.760e+00 5.010e+00
 6.730e+00 5.950e+00 3.660e+00 5.550e+00 7.040e+00 6.650e+00 3.880e+00
 5.800e+00 4.100e+00 5.930e+00 4.360e+00 5.700e+00 2.030e+00 4.400e+00
 5.050e+00 3.540e+00 1.120e+00 6.820e+00 1.750e+00 3.740e+00 1.060e+00
 2.790e+00 2.910e+00 9.900e-01 2.570e+00 2.990e+00 2.280e+00 7.280e+00
 2.760e+00 2.900e+00 2.810e+00 6.600e-01 3.780e+00 3.270e+00 3.560e+00
 5.390e+00 4.590e+00 4.810e+00 4.460e+00 3.480e+00 2.850e+00 2.530e+00
 2.980e+00 3.680e+00 3.150e+00 4.410e+00 4.120e+00 2.710e+00 2.930e+00
 3.230e+00 4.050e+00 4.150e+00 2.770e+00 3.450e+00 3.110e+00 8.400e-01
 1.660e+00 7.800e-01 2.640e+00 3.170e+00 4.980e+00 2.550e+00 3.640e+00
 3.700e+00 4.010e+00 2.470e+00 8.000e-02 3.920e+00 8.000e-01 2.450e+00
 4.470e+00 3.180e+00 2.630e+00 1.880e+00 2.410e+00 2.800e+00 6.300e-01
 2.260e+00 2.490e+00 3.570e+00 3.070e+00 2.970e+00 2.950e+00 2.540e+00
 3.280e+00 3.140e+00 4.700e-01 2.620e+00 3.210e+00 2.070e+00 2.730e+00
 1.850e+00 2.180e+00 1.740e+00 3.020e+00 1.620e+00 3.130e+00 1.920e+00
 3.330e+00 3.220e+00 2.300e+00 4.260e+00 9.700e-01 6.500e-01 1.210e+00
 1.090e+00 2.100e+00 2.440e+00 1.980e+00 3.810e+00 3.590e+00 1.630e+00
 1.960e+00 3.400e+00 6.100e-01 2.050e+00 1.700e+00 3.420e+00 3.360e+00
 3.490e+00 3.050e+00 1.830e+00 2.310e+00 3.980e+00 0.000e+00 2.600e+00
 1.910e+00 2.740e+00 2.830e+00 2.360e+00 1.730e+00 1.940e+00 2.290e+00
 1.820e+00 2.420e+00 3.040e+00 1.800e+00 2.080e+00 1.870e+00 4.180e+00
 3.190e+00 4.210e+00 3.630e+00 2.780e+00 2.000e-01 1.610e+00 1.540e+00
 2.520e+00 2.660e+00 1.000e-01 2.820e+00 2.190e+00 1.560e+00 3.030e+00
 2.200e+00 2.090e+00 2.110e+00 1.480e+00 4.000e+00 5.800e-01 2.510e+00
 3.000e+00 2.240e+00 1.460e+00 1.410e+00 9.200e-01 8.800e-01 1.280e+00
 2.250e+00 3.380e+00 2.040e+00 3.790e+00 4.030e+00 1.650e+00 7.100e-01
 1.420e+00 1.100e+00 2.320e+00 1.200e-01 2.350e+00 2.120e+00 1.400e+00
 1.680e+00 1.130e+00 1.220e+00 2.670e+00 1.020e+00 1.190e+00 1.530e+00
 2.150e+00 9.000e-01 1.970e+00 6.800e-01 1.160e+00 9.300e-01 1.440e+00
 1.600e-01 2.130e+00 2.210e+00 1.780e+00 8.600e-01 1.350e+00 1.050e+00
 2.230e+00 2.400e+00 1.370e+00 1.300e+00 1.950e+00 1.930e+00 1.330e+00
 1.490e+00 1.580e+00 5.000e-02 6.000e-01 2.020e+00 2.380e+00 1.600e+00
 2.010e+00 1.570e+00 1.230e+00 1.900e+00 2.140e+00 1.170e+00 2.270e+00
 1.640e+00 5.900e-01 1.550e+00 4.600e-01 8.100e-01 1.450e+00 2.700e-01
 1.470e+00 1.990e+00 1.500e+00 9.000e-02 2.610e+00 1.890e+00 5.000e-01
 8.900e-01 9.500e-01 2.340e+00 7.200e-01 1.720e+00 1.180e+00 1.760e+00
 7.300e-01 1.270e+00 2.060e+00 5.500e-01 1.520e+00 1.690e+00 2.170e+00
 5.100e-01 1.000e+00 1.290e+00 1.380e+00 1.150e+00 1.670e+00 1.360e+00
 1.010e+00 1.040e+00 1.840e+00 2.220e+00 7.900e-01 1.510e+00 1.070e+00
 1.320e+00 1.590e+00 2.000e-02 2.900e-01 1.250e+00 2.560e+00 1.430e+00
 1.200e+00 4.100e-01 2.800e-01 4.300e-01 6.900e-01 2.000e+00 7.600e-01
 1.860e+00 4.800e-01 6.200e-01 1.310e+00 3.700e-01 1.500e-01 6.400e-01
 2.600e-01 4.900e-01 1.110e+00 1.300e-01 1.810e+00 1.030e+00 1.260e+00
 8.700e-01 7.700e-01 9.600e-01 1.390e+00 1.080e+00 8.500e-01 9.100e-01
 3.000e-01 3.800e-01 9.400e-01 7.000e-02 1.340e+00 1.240e+00 3.400e-01
 1.400e-01 1.000e-02 5.200e-01 8.200e-01 8.300e-01 1.100e-01 2.500e-01
 1.770e+00 3.600e-01 7.500e-01 7.400e-01 1.800e-01 2.200e-01 5.300e-01
 4.200e-01 3.200e-01 3.900e-01 2.400e-01 2.300e-01 6.000e-02 4.500e-01
 7.000e-01 6.700e-01 3.500e-01 5.600e-01 1.140e+00 9.800e-01 5.700e-01
 5.400e-01 4.000e-02 1.700e-01 4.400e-01 3.000e-02 3.300e-01 3.100e-01
 4.000e-01 2.100e-01 1.900e-01]
 ****************************************************************************************************
eu_sales
307
[2.896e+01 3.580e+00 1.276e+01 1.093e+01 8.890e+00 2.260e+00 9.140e+00
 9.180e+00 6.940e+00 6.300e-01 1.095e+01 7.470e+00 6.180e+00 8.030e+00
 4.890e+00 8.490e+00 9.090e+00 4.000e-01 3.750e+00 9.200e+00 4.460e+00
 2.710e+00 3.440e+00 5.140e+00 5.490e+00 3.900e+00 5.350e+00 3.170e+00
 5.090e+00 4.240e+00 5.040e+00 5.860e+00 3.680e+00 4.190e+00 5.730e+00
 3.590e+00 4.510e+00 2.550e+00 4.020e+00 4.370e+00 6.310e+00 3.450e+00
 2.810e+00 2.850e+00 3.490e+00 1.000e-02 3.350e+00 2.040e+00 3.070e+00
 3.870e+00 3.000e+00 4.820e+00 3.640e+00 2.150e+00 3.690e+00 2.650e+00
 2.560e+00 3.110e+00 3.140e+00 1.940e+00 1.950e+00 2.470e+00 2.280e+00
 3.420e+00 3.630e+00 2.360e+00 1.710e+00 1.850e+00 2.790e+00 1.240e+00
 6.120e+00 1.530e+00 3.470e+00 2.240e+00 5.010e+00 2.010e+00 1.720e+00
 2.070e+00 6.420e+00 3.860e+00 4.500e-01 3.480e+00 1.890e+00 5.750e+00
 2.170e+00 1.370e+00 2.350e+00 1.180e+00 2.110e+00 1.880e+00 2.830e+00
 2.990e+00 2.890e+00 3.270e+00 2.220e+00 2.140e+00 1.450e+00 1.750e+00
 1.040e+00 1.770e+00 3.020e+00 2.750e+00 2.160e+00 1.900e+00 2.590e+00
 2.200e+00 4.300e+00 9.300e-01 2.530e+00 2.520e+00 1.790e+00 1.300e+00
 2.600e+00 1.580e+00 1.200e+00 1.560e+00 1.340e+00 1.260e+00 8.300e-01
 6.210e+00 2.800e+00 1.590e+00 1.730e+00 4.330e+00 1.830e+00 0.000e+00
 2.180e+00 1.980e+00 1.470e+00 6.700e-01 1.550e+00 1.910e+00 6.900e-01
 6.000e-01 1.930e+00 1.640e+00 5.500e-01 2.190e+00 1.110e+00 2.290e+00
 2.500e+00 9.600e-01 1.210e+00 1.120e+00 7.700e-01 1.690e+00 1.080e+00
 7.900e-01 2.370e+00 2.460e+00 2.600e-01 7.500e-01 1.250e+00 2.430e+00
 9.800e-01 7.400e-01 2.230e+00 6.100e-01 2.450e+00 1.410e+00 1.800e+00
 3.280e+00 1.160e+00 1.990e+00 1.380e+00 1.360e+00 1.170e+00 1.190e+00
 9.900e-01 1.680e+00 2.000e+00 1.330e+00 1.570e+00 1.480e+00 2.100e+00
 1.270e+00 1.970e+00 9.100e-01 1.390e+00 1.960e+00 2.400e-01 1.510e+00
 1.400e-01 1.290e+00 2.390e+00 1.030e+00 5.000e-01 5.800e-01 1.310e+00
 2.020e+00 1.320e+00 1.010e+00 2.270e+00 2.300e+00 1.820e+00 2.780e+00
 4.400e-01 4.800e-01 2.700e-01 2.100e-01 2.480e+00 5.100e-01 1.520e+00
 4.000e-02 2.800e-01 1.350e+00 8.700e-01 2.130e+00 1.130e+00 1.760e+00
 7.600e-01 2.120e+00 6.600e-01 1.600e+00 1.440e+00 1.430e+00 1.700e+00
 4.700e-01 1.870e+00 8.600e-01 7.300e-01 1.280e+00 8.100e-01 1.090e+00
 6.800e-01 1.220e+00 1.400e+00 1.020e+00 1.490e+00 1.140e+00 4.900e-01
 9.000e-01 3.800e-01 1.420e+00 9.500e-01 1.620e+00 7.100e-01 1.050e+00
 9.200e-01 3.300e-01 3.000e-01 1.670e+00 1.000e+00 8.900e-01 1.000e-01
 7.200e-01 5.900e-01 5.600e-01 1.600e-01 9.700e-01 6.200e-01 8.500e-01
 9.400e-01 8.800e-01 8.400e-01 1.060e+00 2.000e-01 1.150e+00 8.000e-01
 1.100e+00 7.000e-01 1.920e+00 3.200e-01 1.500e-01 5.300e-01 9.000e-02
 1.460e+00 2.900e-01 2.200e-01 1.230e+00 7.000e-02 1.700e-01 5.400e-01
 3.600e-01 3.100e-01 1.840e+00 5.200e-01 1.100e-01 6.400e-01 1.200e-01
 2.050e+00 1.630e+00 8.200e-01 8.000e-02 5.700e-01 1.650e+00 1.900e-01
 2.000e-02 4.300e-01 2.500e-01 1.500e+00 1.800e-01 3.900e-01 1.300e-01
 1.070e+00 4.600e-01 4.100e-01 6.000e-02 3.000e-02 3.700e-01 5.000e-02
 2.300e-01 6.500e-01 4.200e-01 3.400e-01 3.500e-01 7.800e-01]
 ****************************************************************************************************
jp_sales
244
[3.770e+00 6.810e+00 3.790e+00 3.280e+00 1.022e+01 4.220e+00 6.500e+00
 2.930e+00 4.700e+00 2.800e-01 1.930e+00 4.130e+00 7.200e+00 3.600e+00
 2.400e-01 2.530e+00 9.800e-01 4.100e-01 3.540e+00 4.160e+00 6.040e+00
 4.180e+00 3.840e+00 6.000e-02 4.700e-01 5.380e+00 5.320e+00 5.650e+00
 1.870e+00 1.300e-01 3.120e+00 3.600e-01 1.100e-01 4.350e+00 6.500e-01
 7.000e-02 8.000e-02 4.900e-01 3.000e-01 2.660e+00 2.690e+00 4.800e-01
 3.800e-01 5.330e+00 1.910e+00 3.960e+00 3.100e+00 1.100e+00 1.200e+00
 1.400e-01 2.540e+00 2.140e+00 8.100e-01 2.120e+00 4.400e-01 3.150e+00
 1.250e+00 4.000e-02 0.000e+00 2.470e+00 2.230e+00 1.690e+00 1.000e-02
 3.000e+00 2.000e-02 4.390e+00 1.980e+00 1.000e-01 3.810e+00 5.000e-02
 2.490e+00 1.580e+00 3.140e+00 2.730e+00 6.600e-01 2.200e-01 3.630e+00
 1.450e+00 1.310e+00 2.430e+00 7.000e-01 3.500e-01 1.400e+00 6.000e-01
 2.260e+00 1.420e+00 1.280e+00 1.390e+00 8.700e-01 1.700e-01 9.400e-01
 1.900e-01 2.100e-01 1.600e+00 1.600e-01 1.030e+00 2.500e-01 2.060e+00
 1.490e+00 1.290e+00 9.000e-02 2.870e+00 3.000e-02 7.800e-01 8.300e-01
 2.330e+00 2.020e+00 1.360e+00 1.810e+00 1.970e+00 9.100e-01 9.900e-01
 9.500e-01 2.000e+00 1.010e+00 2.780e+00 2.110e+00 1.090e+00 2.000e-01
 1.900e+00 1.270e+00 3.610e+00 1.570e+00 2.200e+00 1.700e+00 1.080e+00
 1.500e-01 1.110e+00 2.900e-01 1.540e+00 1.200e-01 8.900e-01 4.870e+00
 1.520e+00 1.320e+00 1.150e+00 4.100e+00 1.460e+00 4.600e-01 1.050e+00
 1.610e+00 2.600e-01 1.380e+00 6.200e-01 7.300e-01 5.700e-01 3.100e-01
 5.800e-01 1.760e+00 2.100e+00 9.000e-01 5.100e-01 6.400e-01 2.460e+00
 2.300e-01 3.700e-01 9.200e-01 1.070e+00 2.620e+00 1.120e+00 5.400e-01
 2.700e-01 5.900e-01 3.670e+00 5.500e-01 1.750e+00 3.440e+00 3.300e-01
 2.550e+00 2.320e+00 2.790e+00 7.400e-01 3.180e+00 8.200e-01 7.700e-01
 4.000e-01 2.350e+00 3.190e+00 8.000e-01 7.600e-01 3.030e+00 8.800e-01
 4.500e-01 1.160e+00 3.400e-01 1.190e+00 1.130e+00 2.130e+00 1.960e+00
 7.100e-01 1.040e+00 2.680e+00 6.800e-01 2.650e+00 9.600e-01 2.410e+00
 5.200e-01 1.800e-01 1.340e+00 1.480e+00 2.340e+00 1.060e+00 1.210e+00
 2.290e+00 1.630e+00 2.050e+00 2.170e+00 1.560e+00 1.350e+00 1.330e+00
 6.300e-01 7.900e-01 7.500e-01 5.300e-01 1.530e+00 1.300e+00 3.900e-01
 6.900e-01 4.200e-01 9.300e-01 5.600e-01 8.400e-01 7.200e-01 3.200e-01
 1.710e+00 1.650e+00 6.100e-01 1.510e+00 1.500e+00 1.440e+00 1.240e+00
 1.180e+00 1.370e+00 1.000e+00 1.260e+00 8.500e-01 4.300e-01 6.700e-01
 1.140e+00 8.600e-01 1.170e+00 5.000e-01 1.020e+00 9.700e-01]
 ****************************************************************************************************
other_sales
155
[8.450e+00 7.700e-01 3.290e+00 2.950e+00 1.000e+00 5.800e-01 2.880e+00
 2.840e+00 2.240e+00 4.700e-01 2.740e+00 1.900e+00 7.100e-01 2.150e+00
 1.690e+00 1.770e+00 3.960e+00 1.057e+01 5.500e-01 2.040e+00 1.360e+00
 4.200e-01 4.600e-01 1.410e+00 1.780e+00 5.000e-01 1.180e+00 8.000e-01
 1.160e+00 1.320e+00 5.900e-01 2.380e+00 1.130e+00 7.800e-01 2.420e+00
 1.120e+00 1.280e+00 1.570e+00 1.300e+00 1.010e+00 9.100e-01 1.790e+00
 1.970e+00 8.600e-01 1.210e+00 2.300e-01 7.600e-01 7.400e-01 7.530e+00
 2.900e-01 1.030e+00 5.200e-01 2.110e+00 1.600e+00 1.610e+00 3.500e-01
 9.700e-01 1.060e+00 6.300e-01 1.500e-01 7.900e-01 9.600e-01 1.250e+00
 9.000e-01 8.100e-01 3.900e-01 6.800e-01 8.500e-01 1.800e-01 8.000e-02
 6.700e-01 7.000e-01 4.100e-01 3.300e-01 6.000e-01 5.400e-01 1.730e+00
 1.230e+00 1.600e-01 1.110e+00 3.100e-01 4.800e-01 6.200e-01 1.900e-01
 6.900e-01 1.020e+00 7.300e-01 1.080e+00 4.500e-01 2.800e-01 5.100e-01
 2.200e-01 1.090e+00 9.900e-01 3.000e-01 6.400e-01 6.600e-01 9.800e-01
 1.390e+00 1.400e-01 1.370e+00 7.000e-02 2.100e-01 6.100e-01 1.700e-01
 1.200e-01 0.000e+00 7.200e-01 2.400e-01 8.200e-01 1.740e+00 8.700e-01
 9.200e-01 5.700e-01 1.100e-01 4.000e-02 5.600e-01 2.000e-01 3.400e-01
 9.000e-02 8.300e-01 4.400e-01 6.000e-02 3.200e-01 3.800e-01 1.480e+00
 3.700e-01 1.000e-01 2.500e-01 3.600e-01 1.300e-01 4.300e-01 5.000e-02
 2.000e-02 2.600e-01 4.000e-01 7.500e-01 1.930e+00 8.400e-01 5.300e-01
 8.900e-01 1.670e+00 2.700e-01 2.930e+00 4.900e-01 1.000e-02 2.460e+00
 3.000e-02 1.510e+00 2.050e+00 1.680e+00 1.820e+00 1.330e+00 9.400e-01
 9.300e-01]
 ****************************************************************************************************
global_sales
629
[8.253e+01 4.024e+01 3.552e+01 3.277e+01 3.137e+01 3.026e+01 2.980e+01
 2.892e+01 2.832e+01 2.831e+01 2.467e+01 2.321e+01 2.310e+01 2.270e+01
 2.181e+01 2.179e+01 2.104e+01 2.081e+01 2.061e+01 2.015e+01 1.825e+01
 1.814e+01 1.728e+01 1.627e+01 1.615e+01 1.585e+01 1.529e+01 1.514e+01
 1.498e+01 1.473e+01 1.464e+01 1.463e+01 1.461e+01 1.460e+01 1.379e+01
 1.367e+01 1.347e+01 1.332e+01 1.310e+01 1.284e+01 1.266e+01 1.263e+01
 1.261e+01 1.213e+01 1.212e+01 1.189e+01 1.177e+01 1.168e+01 1.166e+01
 1.135e+01 1.118e+01 1.101e+01 1.095e+01 1.081e+01 1.070e+01 1.060e+01
 1.055e+01 1.050e+01 1.049e+01 1.030e+01 1.025e+01 1.012e+01 9.900e+00
 9.870e+00 9.860e+00 9.720e+00 9.710e+00 9.490e+00 9.440e+00 9.360e+00
 9.310e+00 9.300e+00 9.180e+00 9.160e+00 8.910e+00 8.790e+00 8.760e+00
 8.570e+00 8.490e+00 8.380e+00 8.270e+00 8.160e+00 8.090e+00 8.070e+00
 8.050e+00 8.010e+00 7.990e+00 7.980e+00 7.860e+00 7.810e+00 7.720e+00
 7.690e+00 7.660e+00 7.600e+00 7.590e+00 7.580e+00 7.550e+00 7.510e+00
 7.460e+00 7.390e+00 7.380e+00 7.320e+00 7.200e+00 7.170e+00 7.160e+00
 7.150e+00 7.140e+00 7.130e+00 7.090e+00 7.070e+00 6.950e+00 6.900e+00
 6.830e+00 6.820e+00 6.760e+00 6.750e+00 6.740e+00 6.710e+00 6.680e+00
 6.660e+00 6.650e+00 6.620e+00 6.510e+00 6.490e+00 6.470e+00 6.450e+00
 6.440e+00 6.430e+00 6.410e+00 6.400e+00 6.390e+00 6.340e+00 6.320e+00
 6.310e+00 6.300e+00 6.290e+00 6.270e+00 6.210e+00 6.190e+00 6.090e+00
 6.080e+00 6.050e+00 6.030e+00 5.990e+00 5.950e+00 5.870e+00 5.820e+00
 5.780e+00 5.740e+00 5.640e+00 5.630e+00 5.580e+00 5.550e+00 5.540e+00
 5.490e+00 5.480e+00 5.470e+00 5.460e+00 5.450e+00 5.420e+00 5.390e+00
 5.380e+00 5.340e+00 5.330e+00 5.310e+00 5.300e+00 5.290e+00 5.270e+00
 5.260e+00 5.240e+00 5.230e+00 5.220e+00 5.210e+00 5.200e+00 5.190e+00
 5.160e+00 5.150e+00 5.140e+00 5.130e+00 5.120e+00 5.100e+00 5.090e+00
 5.080e+00 5.070e+00 5.050e+00 5.030e+00 5.020e+00 5.010e+00 5.000e+00
 4.980e+00 4.930e+00 4.920e+00 4.910e+00 4.880e+00 4.870e+00 4.850e+00
 4.840e+00 4.820e+00 4.800e+00 4.790e+00 4.760e+00 4.730e+00 4.710e+00
 4.700e+00 4.680e+00 4.670e+00 4.630e+00 4.620e+00 4.610e+00 4.600e+00
 4.590e+00 4.570e+00 4.530e+00 4.500e+00 4.490e+00 4.480e+00 4.470e+00
 4.460e+00 4.450e+00 4.430e+00 4.420e+00 4.410e+00 4.390e+00 4.380e+00
 4.370e+00 4.360e+00 4.340e+00 4.330e+00 4.320e+00 4.310e+00 4.290e+00
 4.280e+00 4.270e+00 4.240e+00 4.230e+00 4.220e+00 4.210e+00 4.200e+00
 4.190e+00 4.180e+00 4.170e+00 4.160e+00 4.140e+00 4.120e+00 4.110e+00
 4.100e+00 4.090e+00 4.080e+00 4.070e+00 4.060e+00 4.050e+00 4.040e+00
 4.030e+00 4.010e+00 3.980e+00 3.970e+00 3.960e+00 3.950e+00 3.940e+00
 3.910e+00 3.900e+00 3.890e+00 3.880e+00 3.870e+00 3.850e+00 3.840e+00
 3.830e+00 3.800e+00 3.790e+00 3.770e+00 3.760e+00 3.740e+00 3.730e+00
 3.720e+00 3.710e+00 3.700e+00 3.670e+00 3.660e+00 3.650e+00 3.640e+00
 3.630e+00 3.620e+00 3.610e+00 3.600e+00 3.590e+00 3.580e+00 3.560e+00
 3.540e+00 3.530e+00 3.520e+00 3.510e+00 3.500e+00 3.490e+00 3.480e+00
 3.470e+00 3.460e+00 3.450e+00 3.440e+00 3.420e+00 3.410e+00 3.400e+00
 3.390e+00 3.380e+00 3.370e+00 3.360e+00 3.350e+00 3.340e+00 3.330e+00
 3.320e+00 3.310e+00 3.300e+00 3.280e+00 3.270e+00 3.260e+00 3.250e+00
 3.240e+00 3.230e+00 3.210e+00 3.200e+00 3.190e+00 3.180e+00 3.170e+00
 3.150e+00 3.140e+00 3.130e+00 3.120e+00 3.110e+00 3.100e+00 3.090e+00
 3.080e+00 3.070e+00 3.060e+00 3.050e+00 3.040e+00 3.030e+00 3.020e+00
 3.010e+00 3.000e+00 2.990e+00 2.960e+00 2.950e+00 2.940e+00 2.930e+00
 2.920e+00 2.910e+00 2.900e+00 2.890e+00 2.880e+00 2.870e+00 2.860e+00
 2.850e+00 2.840e+00 2.830e+00 2.820e+00 2.810e+00 2.800e+00 2.790e+00
 2.780e+00 2.770e+00 2.760e+00 2.750e+00 2.730e+00 2.710e+00 2.700e+00
 2.690e+00 2.680e+00 2.670e+00 2.660e+00 2.650e+00 2.630e+00 2.620e+00
 2.610e+00 2.600e+00 2.590e+00 2.580e+00 2.570e+00 2.560e+00 2.540e+00
 2.530e+00 2.520e+00 2.500e+00 2.490e+00 2.480e+00 2.470e+00 2.460e+00
 2.450e+00 2.440e+00 2.430e+00 2.420e+00 2.410e+00 2.400e+00 2.390e+00
 2.380e+00 2.370e+00 2.360e+00 2.350e+00 2.340e+00 2.320e+00 2.310e+00
 2.300e+00 2.290e+00 2.280e+00 2.270e+00 2.260e+00 2.250e+00 2.240e+00
 2.230e+00 2.220e+00 2.210e+00 2.200e+00 2.190e+00 2.180e+00 2.170e+00
 2.160e+00 2.150e+00 2.140e+00 2.130e+00 2.120e+00 2.110e+00 2.100e+00
 2.090e+00 2.080e+00 2.070e+00 2.060e+00 2.050e+00 2.040e+00 2.030e+00
 2.020e+00 2.010e+00 2.000e+00 1.990e+00 1.980e+00 1.970e+00 1.960e+00
 1.950e+00 1.940e+00 1.930e+00 1.920e+00 1.910e+00 1.900e+00 1.890e+00
 1.880e+00 1.870e+00 1.860e+00 1.850e+00 1.840e+00 1.830e+00 1.820e+00
 1.810e+00 1.800e+00 1.790e+00 1.780e+00 1.770e+00 1.760e+00 1.750e+00
 1.740e+00 1.730e+00 1.720e+00 1.710e+00 1.700e+00 1.690e+00 1.680e+00
 1.670e+00 1.660e+00 1.650e+00 1.640e+00 1.630e+00 1.620e+00 1.610e+00
 1.600e+00 1.590e+00 1.580e+00 1.570e+00 1.560e+00 1.550e+00 1.540e+00
 1.530e+00 1.520e+00 1.510e+00 1.500e+00 1.490e+00 1.480e+00 1.470e+00
 1.460e+00 1.450e+00 1.440e+00 1.430e+00 1.420e+00 1.410e+00 1.400e+00
 1.390e+00 1.380e+00 1.370e+00 1.360e+00 1.350e+00 1.340e+00 1.330e+00
 1.320e+00 1.310e+00 1.300e+00 1.290e+00 1.280e+00 1.270e+00 1.260e+00
 1.250e+00 1.240e+00 1.230e+00 1.220e+00 1.210e+00 1.200e+00 1.190e+00
 1.180e+00 1.170e+00 1.160e+00 1.150e+00 1.140e+00 1.130e+00 1.120e+00
 1.110e+00 1.100e+00 1.090e+00 1.080e+00 1.070e+00 1.060e+00 1.050e+00
 1.040e+00 1.030e+00 1.020e+00 1.010e+00 1.000e+00 9.900e-01 9.800e-01
 9.700e-01 9.600e-01 9.500e-01 9.400e-01 9.300e-01 9.200e-01 9.100e-01
 9.000e-01 8.900e-01 8.800e-01 8.700e-01 8.600e-01 8.500e-01 8.400e-01
 8.300e-01 8.200e-01 8.100e-01 8.000e-01 7.900e-01 7.800e-01 7.700e-01
 7.600e-01 7.500e-01 7.400e-01 7.300e-01 7.200e-01 7.100e-01 7.000e-01
 6.900e-01 6.800e-01 6.700e-01 6.600e-01 6.500e-01 6.400e-01 6.300e-01
 6.200e-01 6.100e-01 6.000e-01 5.900e-01 5.800e-01 5.700e-01 5.600e-01
 5.500e-01 5.400e-01 5.300e-01 5.200e-01 5.100e-01 5.000e-01 4.900e-01
 4.800e-01 4.700e-01 4.600e-01 4.500e-01 4.400e-01 4.300e-01 4.200e-01
 4.100e-01 4.000e-01 3.900e-01 3.800e-01 3.700e-01 3.600e-01 3.500e-01
 3.400e-01 3.300e-01 3.200e-01 3.100e-01 3.000e-01 2.900e-01 2.800e-01
 2.700e-01 2.600e-01 2.500e-01 2.400e-01 2.300e-01 2.200e-01 2.100e-01
 2.000e-01 1.900e-01 1.800e-01 1.700e-01 1.600e-01 1.500e-01 1.400e-01
 1.300e-01 1.200e-01 1.100e-01 1.000e-01 9.000e-02 8.000e-02 7.000e-02
 6.000e-02 5.000e-02 4.000e-02 3.000e-02 2.000e-02 1.000e-02]
 ****************************************************************************************************

### Feature Engineering
##### Detecting and fixing problems in dataset columns such as inconsistent formats, wrong data types, or invalid entries.

In [123]:
repair_columns=['year_of_release', 'publisher', 'na_sales', 'eu_sales', 'jp_sales','other_sales','global_sales','user_score']

In [124]:
""" 
    - Convert all object dtype to string dtype: optimized internally, making operations faster and more memory efficient.
    - year_of_release: contain 'Adventure'(invalid entry) will replace it with NaN (becuase it is wrong value that is belong to year) 
                     and convert the data type from float into int (ex: from [2006.] to [2006]), then fill it.
                   
    - publisher: need to remove the puncatiations: , - // . to be better.
    - na_sales, eu_sales, jp_sales, other_sales and global_sales: need to convert the scientific notation (like 4.136e+01) into standard decimal formatting (like 41.36) to be clear and more readable.
    - user_score: need to replace 'tbd' to NaN and convert the data type from object into float, then fill it. 
      
"""

" \n    - Convert all object dtype to string dtype: optimized internally, making operations faster and more memory efficient.\n    - year_of_release: contain 'Adventure'(invalid entry) will replace it with NaN (becuase it is wrong value that is belong to year) \n                     and convert the data type from float into int (ex: from [2006.] to [2006]), then fill it.\n                   \n    - publisher: need to remove the puncatiations: , - // . to be better.\n    - na_sales, eu_sales, jp_sales, other_sales and global_sales: need to convert the scientific notation (like 4.136e+01) into standard decimal formatting (like 41.36) to be clear and more readable.\n    - user_score: need to replace 'tbd' to NaN and convert the data type from object into float, then fill it. \n      \n"

Convert all object dtype to string dtype

In [125]:
# Identify object columns
obj_cols = df.select_dtypes(include='object').columns
print(obj_cols)

Index(['name', 'platform', 'genre', 'publisher', 'user_score', 'developer',
       'rating'],
      dtype='object')

In [126]:
# Convert them to pandas string dtype
df[obj_cols] = df[obj_cols].astype("string")

# Verify conversion
print(df.dtypes)

name               string[python]
platform           string[python]
year_of_release           float64
genre              string[python]
publisher          string[python]
na_sales                  float64
eu_sales                  float64
jp_sales                  float64
other_sales               float64
global_sales              float64
user_score         string[python]
developer          string[python]
rating             string[python]
dtype: object

In [127]:
# Repair 'year_of_release' column

# Step1: Convert 'year_of_release' to numeric, invalid entries (like: Adventure) → NaN
df['year_of_release'] = pd.to_numeric(df['year_of_release'], errors='coerce') 

# Step2: convert to Int to remove float decimals (e.g., 2009.0 → 2009).
df['year_of_release'] = df['year_of_release'].astype('Int64')  

# Check unique values
df['year_of_release'].unique()

<IntegerArray>
[2006, 1985, 2008, 2009, 1996, 1989, 1984, 2005, 1999, 2007, 2010, 2013, 2004,
 1990, 1988, 2002, 2001, 2011, 1998, 2015, 2012, 2014, 1992, 1997, 1993, 1994,
 1982, 2016, 2003, 1986, 2000, <NA>, 1995, 1991, 1981, 1987, 1980, 1983, 2020,
 2017]
Length: 40, dtype: Int64

In [128]:
# Repair the 'publisher' column: need to remove the puncatiations: '-' , '.' , '//' , ',' to be better.
df['publisher'] = (
    df['publisher']
    .str.strip()
    .str.lower()
    .str.replace('-', ' ')
    .str.replace('.', ' ')
    .str.replace('//', ' ')
    .str.replace(',', ' ')
)

In [129]:
# Run it after repair to see the changes:
print('publisher') 
print(df['publisher'].nunique())
print(df['publisher'].unique())

publisher
580
<StringArray>
[                   'nintendo',      'microsoft game studios',
        'take two interactive', 'sony computer entertainment',
                  'activision',                     'ubisoft',
          'bethesda softworks',             'electronic arts',
                        'sega',                  'squaresoft',
 ...
                      'piacci',         'paradox development',
                     'otomate',       'ascaron entertainment',
                   'ongakukan',                    'commseed',
           'uig entertainment',                      'takuyo',
          'interchannel holon',                'red flagship']
Length: 581, dtype: string

In [130]:
# Repair cols_to_format
cols_to_format=['na_sales','eu_sales','jp_sales','other_sales','global_sales']

# Define function for decimal formatting.
def decimal_format(x, decimals=2):
    if pd.isna(x):   # to keep NaN as it is.
        return x
    else:
        return format(float(x), f'.{decimals}f')

In [131]:
for col in cols_to_format:  # to check the output
    print(col) 
    print(df[col].nunique())
    print(df[col].unique(), '\n','*'*100)

na_sales
402
[4.136e+01 2.908e+01 1.568e+01 1.561e+01 1.127e+01 2.320e+01 1.128e+01
 1.396e+01 1.444e+01 2.693e+01 9.050e+00 9.710e+00 9.000e+00 8.920e+00
 1.500e+01 9.010e+00 7.020e+00 9.430e+00 1.278e+01 4.740e+00 6.380e+00
 1.083e+01 9.540e+00 9.660e+00 8.410e+00 6.060e+00 3.430e+00 5.510e+00
 6.850e+00 9.040e+00 5.890e+00 6.030e+00 9.700e+00 5.280e+00 4.990e+00
 8.250e+00 8.520e+00 5.540e+00 6.990e+00 6.620e+00 5.030e+00 5.990e+00
 3.960e+00 2.500e+00 7.970e+00 6.910e+00 4.340e+00 4.350e+00 3.010e+00
 6.160e+00 6.760e+00 4.020e+00 4.890e+00 2.960e+00 4.760e+00 5.010e+00
 6.730e+00 5.950e+00 3.660e+00 5.550e+00 7.040e+00 6.650e+00 3.880e+00
 5.800e+00 4.100e+00 5.930e+00 4.360e+00 5.700e+00 2.030e+00 4.400e+00
 5.050e+00 3.540e+00 1.120e+00 6.820e+00 1.750e+00 3.740e+00 1.060e+00
 2.790e+00 2.910e+00 9.900e-01 2.570e+00 2.990e+00 2.280e+00 7.280e+00
 2.760e+00 2.900e+00 2.810e+00 6.600e-01 3.780e+00 3.270e+00 3.560e+00
 5.390e+00 4.590e+00 4.810e+00 4.460e+00 3.480e+00 2.850e+00 2.530e+00
 2.980e+00 3.680e+00 3.150e+00 4.410e+00 4.120e+00 2.710e+00 2.930e+00
 3.230e+00 4.050e+00 4.150e+00 2.770e+00 3.450e+00 3.110e+00 8.400e-01
 1.660e+00 7.800e-01 2.640e+00 3.170e+00 4.980e+00 2.550e+00 3.640e+00
 3.700e+00 4.010e+00 2.470e+00 8.000e-02 3.920e+00 8.000e-01 2.450e+00
 4.470e+00 3.180e+00 2.630e+00 1.880e+00 2.410e+00 2.800e+00 6.300e-01
 2.260e+00 2.490e+00 3.570e+00 3.070e+00 2.970e+00 2.950e+00 2.540e+00
 3.280e+00 3.140e+00 4.700e-01 2.620e+00 3.210e+00 2.070e+00 2.730e+00
 1.850e+00 2.180e+00 1.740e+00 3.020e+00 1.620e+00 3.130e+00 1.920e+00
 3.330e+00 3.220e+00 2.300e+00 4.260e+00 9.700e-01 6.500e-01 1.210e+00
 1.090e+00 2.100e+00 2.440e+00 1.980e+00 3.810e+00 3.590e+00 1.630e+00
 1.960e+00 3.400e+00 6.100e-01 2.050e+00 1.700e+00 3.420e+00 3.360e+00
 3.490e+00 3.050e+00 1.830e+00 2.310e+00 3.980e+00 0.000e+00 2.600e+00
 1.910e+00 2.740e+00 2.830e+00 2.360e+00 1.730e+00 1.940e+00 2.290e+00
 1.820e+00 2.420e+00 3.040e+00 1.800e+00 2.080e+00 1.870e+00 4.180e+00
 3.190e+00 4.210e+00 3.630e+00 2.780e+00 2.000e-01 1.610e+00 1.540e+00
 2.520e+00 2.660e+00 1.000e-01 2.820e+00 2.190e+00 1.560e+00 3.030e+00
 2.200e+00 2.090e+00 2.110e+00 1.480e+00 4.000e+00 5.800e-01 2.510e+00
 3.000e+00 2.240e+00 1.460e+00 1.410e+00 9.200e-01 8.800e-01 1.280e+00
 2.250e+00 3.380e+00 2.040e+00 3.790e+00 4.030e+00 1.650e+00 7.100e-01
 1.420e+00 1.100e+00 2.320e+00 1.200e-01 2.350e+00 2.120e+00 1.400e+00
 1.680e+00 1.130e+00 1.220e+00 2.670e+00 1.020e+00 1.190e+00 1.530e+00
 2.150e+00 9.000e-01 1.970e+00 6.800e-01 1.160e+00 9.300e-01 1.440e+00
 1.600e-01 2.130e+00 2.210e+00 1.780e+00 8.600e-01 1.350e+00 1.050e+00
 2.230e+00 2.400e+00 1.370e+00 1.300e+00 1.950e+00 1.930e+00 1.330e+00
 1.490e+00 1.580e+00 5.000e-02 6.000e-01 2.020e+00 2.380e+00 1.600e+00
 2.010e+00 1.570e+00 1.230e+00 1.900e+00 2.140e+00 1.170e+00 2.270e+00
 1.640e+00 5.900e-01 1.550e+00 4.600e-01 8.100e-01 1.450e+00 2.700e-01
 1.470e+00 1.990e+00 1.500e+00 9.000e-02 2.610e+00 1.890e+00 5.000e-01
 8.900e-01 9.500e-01 2.340e+00 7.200e-01 1.720e+00 1.180e+00 1.760e+00
 7.300e-01 1.270e+00 2.060e+00 5.500e-01 1.520e+00 1.690e+00 2.170e+00
 5.100e-01 1.000e+00 1.290e+00 1.380e+00 1.150e+00 1.670e+00 1.360e+00
 1.010e+00 1.040e+00 1.840e+00 2.220e+00 7.900e-01 1.510e+00 1.070e+00
 1.320e+00 1.590e+00 2.000e-02 2.900e-01 1.250e+00 2.560e+00 1.430e+00
 1.200e+00 4.100e-01 2.800e-01 4.300e-01 6.900e-01 2.000e+00 7.600e-01
 1.860e+00 4.800e-01 6.200e-01 1.310e+00 3.700e-01 1.500e-01 6.400e-01
 2.600e-01 4.900e-01 1.110e+00 1.300e-01 1.810e+00 1.030e+00 1.260e+00
 8.700e-01 7.700e-01 9.600e-01 1.390e+00 1.080e+00 8.500e-01 9.100e-01
 3.000e-01 3.800e-01 9.400e-01 7.000e-02 1.340e+00 1.240e+00 3.400e-01
 1.400e-01 1.000e-02 5.200e-01 8.200e-01 8.300e-01 1.100e-01 2.500e-01
 1.770e+00 3.600e-01 7.500e-01 7.400e-01 1.800e-01 2.200e-01 5.300e-01
 4.200e-01 3.200e-01 3.900e-01 2.400e-01 2.300e-01 6.000e-02 4.500e-01
 7.000e-01 6.700e-01 3.500e-01 5.600e-01 1.140e+00 9.800e-01 5.700e-01
 5.400e-01 4.000e-02 1.700e-01 4.400e-01 3.000e-02 3.300e-01 3.100e-01
 4.000e-01 2.100e-01 1.900e-01]
 ****************************************************************************************************
eu_sales
307
[2.896e+01 3.580e+00 1.276e+01 1.093e+01 8.890e+00 2.260e+00 9.140e+00
 9.180e+00 6.940e+00 6.300e-01 1.095e+01 7.470e+00 6.180e+00 8.030e+00
 4.890e+00 8.490e+00 9.090e+00 4.000e-01 3.750e+00 9.200e+00 4.460e+00
 2.710e+00 3.440e+00 5.140e+00 5.490e+00 3.900e+00 5.350e+00 3.170e+00
 5.090e+00 4.240e+00 5.040e+00 5.860e+00 3.680e+00 4.190e+00 5.730e+00
 3.590e+00 4.510e+00 2.550e+00 4.020e+00 4.370e+00 6.310e+00 3.450e+00
 2.810e+00 2.850e+00 3.490e+00 1.000e-02 3.350e+00 2.040e+00 3.070e+00
 3.870e+00 3.000e+00 4.820e+00 3.640e+00 2.150e+00 3.690e+00 2.650e+00
 2.560e+00 3.110e+00 3.140e+00 1.940e+00 1.950e+00 2.470e+00 2.280e+00
 3.420e+00 3.630e+00 2.360e+00 1.710e+00 1.850e+00 2.790e+00 1.240e+00
 6.120e+00 1.530e+00 3.470e+00 2.240e+00 5.010e+00 2.010e+00 1.720e+00
 2.070e+00 6.420e+00 3.860e+00 4.500e-01 3.480e+00 1.890e+00 5.750e+00
 2.170e+00 1.370e+00 2.350e+00 1.180e+00 2.110e+00 1.880e+00 2.830e+00
 2.990e+00 2.890e+00 3.270e+00 2.220e+00 2.140e+00 1.450e+00 1.750e+00
 1.040e+00 1.770e+00 3.020e+00 2.750e+00 2.160e+00 1.900e+00 2.590e+00
 2.200e+00 4.300e+00 9.300e-01 2.530e+00 2.520e+00 1.790e+00 1.300e+00
 2.600e+00 1.580e+00 1.200e+00 1.560e+00 1.340e+00 1.260e+00 8.300e-01
 6.210e+00 2.800e+00 1.590e+00 1.730e+00 4.330e+00 1.830e+00 0.000e+00
 2.180e+00 1.980e+00 1.470e+00 6.700e-01 1.550e+00 1.910e+00 6.900e-01
 6.000e-01 1.930e+00 1.640e+00 5.500e-01 2.190e+00 1.110e+00 2.290e+00
 2.500e+00 9.600e-01 1.210e+00 1.120e+00 7.700e-01 1.690e+00 1.080e+00
 7.900e-01 2.370e+00 2.460e+00 2.600e-01 7.500e-01 1.250e+00 2.430e+00
 9.800e-01 7.400e-01 2.230e+00 6.100e-01 2.450e+00 1.410e+00 1.800e+00
 3.280e+00 1.160e+00 1.990e+00 1.380e+00 1.360e+00 1.170e+00 1.190e+00
 9.900e-01 1.680e+00 2.000e+00 1.330e+00 1.570e+00 1.480e+00 2.100e+00
 1.270e+00 1.970e+00 9.100e-01 1.390e+00 1.960e+00 2.400e-01 1.510e+00
 1.400e-01 1.290e+00 2.390e+00 1.030e+00 5.000e-01 5.800e-01 1.310e+00
 2.020e+00 1.320e+00 1.010e+00 2.270e+00 2.300e+00 1.820e+00 2.780e+00
 4.400e-01 4.800e-01 2.700e-01 2.100e-01 2.480e+00 5.100e-01 1.520e+00
 4.000e-02 2.800e-01 1.350e+00 8.700e-01 2.130e+00 1.130e+00 1.760e+00
 7.600e-01 2.120e+00 6.600e-01 1.600e+00 1.440e+00 1.430e+00 1.700e+00
 4.700e-01 1.870e+00 8.600e-01 7.300e-01 1.280e+00 8.100e-01 1.090e+00
 6.800e-01 1.220e+00 1.400e+00 1.020e+00 1.490e+00 1.140e+00 4.900e-01
 9.000e-01 3.800e-01 1.420e+00 9.500e-01 1.620e+00 7.100e-01 1.050e+00
 9.200e-01 3.300e-01 3.000e-01 1.670e+00 1.000e+00 8.900e-01 1.000e-01
 7.200e-01 5.900e-01 5.600e-01 1.600e-01 9.700e-01 6.200e-01 8.500e-01
 9.400e-01 8.800e-01 8.400e-01 1.060e+00 2.000e-01 1.150e+00 8.000e-01
 1.100e+00 7.000e-01 1.920e+00 3.200e-01 1.500e-01 5.300e-01 9.000e-02
 1.460e+00 2.900e-01 2.200e-01 1.230e+00 7.000e-02 1.700e-01 5.400e-01
 3.600e-01 3.100e-01 1.840e+00 5.200e-01 1.100e-01 6.400e-01 1.200e-01
 2.050e+00 1.630e+00 8.200e-01 8.000e-02 5.700e-01 1.650e+00 1.900e-01
 2.000e-02 4.300e-01 2.500e-01 1.500e+00 1.800e-01 3.900e-01 1.300e-01
 1.070e+00 4.600e-01 4.100e-01 6.000e-02 3.000e-02 3.700e-01 5.000e-02
 2.300e-01 6.500e-01 4.200e-01 3.400e-01 3.500e-01 7.800e-01]
 ****************************************************************************************************
jp_sales
244
[3.770e+00 6.810e+00 3.790e+00 3.280e+00 1.022e+01 4.220e+00 6.500e+00
 2.930e+00 4.700e+00 2.800e-01 1.930e+00 4.130e+00 7.200e+00 3.600e+00
 2.400e-01 2.530e+00 9.800e-01 4.100e-01 3.540e+00 4.160e+00 6.040e+00
 4.180e+00 3.840e+00 6.000e-02 4.700e-01 5.380e+00 5.320e+00 5.650e+00
 1.870e+00 1.300e-01 3.120e+00 3.600e-01 1.100e-01 4.350e+00 6.500e-01
 7.000e-02 8.000e-02 4.900e-01 3.000e-01 2.660e+00 2.690e+00 4.800e-01
 3.800e-01 5.330e+00 1.910e+00 3.960e+00 3.100e+00 1.100e+00 1.200e+00
 1.400e-01 2.540e+00 2.140e+00 8.100e-01 2.120e+00 4.400e-01 3.150e+00
 1.250e+00 4.000e-02 0.000e+00 2.470e+00 2.230e+00 1.690e+00 1.000e-02
 3.000e+00 2.000e-02 4.390e+00 1.980e+00 1.000e-01 3.810e+00 5.000e-02
 2.490e+00 1.580e+00 3.140e+00 2.730e+00 6.600e-01 2.200e-01 3.630e+00
 1.450e+00 1.310e+00 2.430e+00 7.000e-01 3.500e-01 1.400e+00 6.000e-01
 2.260e+00 1.420e+00 1.280e+00 1.390e+00 8.700e-01 1.700e-01 9.400e-01
 1.900e-01 2.100e-01 1.600e+00 1.600e-01 1.030e+00 2.500e-01 2.060e+00
 1.490e+00 1.290e+00 9.000e-02 2.870e+00 3.000e-02 7.800e-01 8.300e-01
 2.330e+00 2.020e+00 1.360e+00 1.810e+00 1.970e+00 9.100e-01 9.900e-01
 9.500e-01 2.000e+00 1.010e+00 2.780e+00 2.110e+00 1.090e+00 2.000e-01
 1.900e+00 1.270e+00 3.610e+00 1.570e+00 2.200e+00 1.700e+00 1.080e+00
 1.500e-01 1.110e+00 2.900e-01 1.540e+00 1.200e-01 8.900e-01 4.870e+00
 1.520e+00 1.320e+00 1.150e+00 4.100e+00 1.460e+00 4.600e-01 1.050e+00
 1.610e+00 2.600e-01 1.380e+00 6.200e-01 7.300e-01 5.700e-01 3.100e-01
 5.800e-01 1.760e+00 2.100e+00 9.000e-01 5.100e-01 6.400e-01 2.460e+00
 2.300e-01 3.700e-01 9.200e-01 1.070e+00 2.620e+00 1.120e+00 5.400e-01
 2.700e-01 5.900e-01 3.670e+00 5.500e-01 1.750e+00 3.440e+00 3.300e-01
 2.550e+00 2.320e+00 2.790e+00 7.400e-01 3.180e+00 8.200e-01 7.700e-01
 4.000e-01 2.350e+00 3.190e+00 8.000e-01 7.600e-01 3.030e+00 8.800e-01
 4.500e-01 1.160e+00 3.400e-01 1.190e+00 1.130e+00 2.130e+00 1.960e+00
 7.100e-01 1.040e+00 2.680e+00 6.800e-01 2.650e+00 9.600e-01 2.410e+00
 5.200e-01 1.800e-01 1.340e+00 1.480e+00 2.340e+00 1.060e+00 1.210e+00
 2.290e+00 1.630e+00 2.050e+00 2.170e+00 1.560e+00 1.350e+00 1.330e+00
 6.300e-01 7.900e-01 7.500e-01 5.300e-01 1.530e+00 1.300e+00 3.900e-01
 6.900e-01 4.200e-01 9.300e-01 5.600e-01 8.400e-01 7.200e-01 3.200e-01
 1.710e+00 1.650e+00 6.100e-01 1.510e+00 1.500e+00 1.440e+00 1.240e+00
 1.180e+00 1.370e+00 1.000e+00 1.260e+00 8.500e-01 4.300e-01 6.700e-01
 1.140e+00 8.600e-01 1.170e+00 5.000e-01 1.020e+00 9.700e-01]
 ****************************************************************************************************
other_sales
155
[8.450e+00 7.700e-01 3.290e+00 2.950e+00 1.000e+00 5.800e-01 2.880e+00
 2.840e+00 2.240e+00 4.700e-01 2.740e+00 1.900e+00 7.100e-01 2.150e+00
 1.690e+00 1.770e+00 3.960e+00 1.057e+01 5.500e-01 2.040e+00 1.360e+00
 4.200e-01 4.600e-01 1.410e+00 1.780e+00 5.000e-01 1.180e+00 8.000e-01
 1.160e+00 1.320e+00 5.900e-01 2.380e+00 1.130e+00 7.800e-01 2.420e+00
 1.120e+00 1.280e+00 1.570e+00 1.300e+00 1.010e+00 9.100e-01 1.790e+00
 1.970e+00 8.600e-01 1.210e+00 2.300e-01 7.600e-01 7.400e-01 7.530e+00
 2.900e-01 1.030e+00 5.200e-01 2.110e+00 1.600e+00 1.610e+00 3.500e-01
 9.700e-01 1.060e+00 6.300e-01 1.500e-01 7.900e-01 9.600e-01 1.250e+00
 9.000e-01 8.100e-01 3.900e-01 6.800e-01 8.500e-01 1.800e-01 8.000e-02
 6.700e-01 7.000e-01 4.100e-01 3.300e-01 6.000e-01 5.400e-01 1.730e+00
 1.230e+00 1.600e-01 1.110e+00 3.100e-01 4.800e-01 6.200e-01 1.900e-01
 6.900e-01 1.020e+00 7.300e-01 1.080e+00 4.500e-01 2.800e-01 5.100e-01
 2.200e-01 1.090e+00 9.900e-01 3.000e-01 6.400e-01 6.600e-01 9.800e-01
 1.390e+00 1.400e-01 1.370e+00 7.000e-02 2.100e-01 6.100e-01 1.700e-01
 1.200e-01 0.000e+00 7.200e-01 2.400e-01 8.200e-01 1.740e+00 8.700e-01
 9.200e-01 5.700e-01 1.100e-01 4.000e-02 5.600e-01 2.000e-01 3.400e-01
 9.000e-02 8.300e-01 4.400e-01 6.000e-02 3.200e-01 3.800e-01 1.480e+00
 3.700e-01 1.000e-01 2.500e-01 3.600e-01 1.300e-01 4.300e-01 5.000e-02
 2.000e-02 2.600e-01 4.000e-01 7.500e-01 1.930e+00 8.400e-01 5.300e-01
 8.900e-01 1.670e+00 2.700e-01 2.930e+00 4.900e-01 1.000e-02 2.460e+00
 3.000e-02 1.510e+00 2.050e+00 1.680e+00 1.820e+00 1.330e+00 9.400e-01
 9.300e-01]
 ****************************************************************************************************
global_sales
629
[8.253e+01 4.024e+01 3.552e+01 3.277e+01 3.137e+01 3.026e+01 2.980e+01
 2.892e+01 2.832e+01 2.831e+01 2.467e+01 2.321e+01 2.310e+01 2.270e+01
 2.181e+01 2.179e+01 2.104e+01 2.081e+01 2.061e+01 2.015e+01 1.825e+01
 1.814e+01 1.728e+01 1.627e+01 1.615e+01 1.585e+01 1.529e+01 1.514e+01
 1.498e+01 1.473e+01 1.464e+01 1.463e+01 1.461e+01 1.460e+01 1.379e+01
 1.367e+01 1.347e+01 1.332e+01 1.310e+01 1.284e+01 1.266e+01 1.263e+01
 1.261e+01 1.213e+01 1.212e+01 1.189e+01 1.177e+01 1.168e+01 1.166e+01
 1.135e+01 1.118e+01 1.101e+01 1.095e+01 1.081e+01 1.070e+01 1.060e+01
 1.055e+01 1.050e+01 1.049e+01 1.030e+01 1.025e+01 1.012e+01 9.900e+00
 9.870e+00 9.860e+00 9.720e+00 9.710e+00 9.490e+00 9.440e+00 9.360e+00
 9.310e+00 9.300e+00 9.180e+00 9.160e+00 8.910e+00 8.790e+00 8.760e+00
 8.570e+00 8.490e+00 8.380e+00 8.270e+00 8.160e+00 8.090e+00 8.070e+00
 8.050e+00 8.010e+00 7.990e+00 7.980e+00 7.860e+00 7.810e+00 7.720e+00
 7.690e+00 7.660e+00 7.600e+00 7.590e+00 7.580e+00 7.550e+00 7.510e+00
 7.460e+00 7.390e+00 7.380e+00 7.320e+00 7.200e+00 7.170e+00 7.160e+00
 7.150e+00 7.140e+00 7.130e+00 7.090e+00 7.070e+00 6.950e+00 6.900e+00
 6.830e+00 6.820e+00 6.760e+00 6.750e+00 6.740e+00 6.710e+00 6.680e+00
 6.660e+00 6.650e+00 6.620e+00 6.510e+00 6.490e+00 6.470e+00 6.450e+00
 6.440e+00 6.430e+00 6.410e+00 6.400e+00 6.390e+00 6.340e+00 6.320e+00
 6.310e+00 6.300e+00 6.290e+00 6.270e+00 6.210e+00 6.190e+00 6.090e+00
 6.080e+00 6.050e+00 6.030e+00 5.990e+00 5.950e+00 5.870e+00 5.820e+00
 5.780e+00 5.740e+00 5.640e+00 5.630e+00 5.580e+00 5.550e+00 5.540e+00
 5.490e+00 5.480e+00 5.470e+00 5.460e+00 5.450e+00 5.420e+00 5.390e+00
 5.380e+00 5.340e+00 5.330e+00 5.310e+00 5.300e+00 5.290e+00 5.270e+00
 5.260e+00 5.240e+00 5.230e+00 5.220e+00 5.210e+00 5.200e+00 5.190e+00
 5.160e+00 5.150e+00 5.140e+00 5.130e+00 5.120e+00 5.100e+00 5.090e+00
 5.080e+00 5.070e+00 5.050e+00 5.030e+00 5.020e+00 5.010e+00 5.000e+00
 4.980e+00 4.930e+00 4.920e+00 4.910e+00 4.880e+00 4.870e+00 4.850e+00
 4.840e+00 4.820e+00 4.800e+00 4.790e+00 4.760e+00 4.730e+00 4.710e+00
 4.700e+00 4.680e+00 4.670e+00 4.630e+00 4.620e+00 4.610e+00 4.600e+00
 4.590e+00 4.570e+00 4.530e+00 4.500e+00 4.490e+00 4.480e+00 4.470e+00
 4.460e+00 4.450e+00 4.430e+00 4.420e+00 4.410e+00 4.390e+00 4.380e+00
 4.370e+00 4.360e+00 4.340e+00 4.330e+00 4.320e+00 4.310e+00 4.290e+00
 4.280e+00 4.270e+00 4.240e+00 4.230e+00 4.220e+00 4.210e+00 4.200e+00
 4.190e+00 4.180e+00 4.170e+00 4.160e+00 4.140e+00 4.120e+00 4.110e+00
 4.100e+00 4.090e+00 4.080e+00 4.070e+00 4.060e+00 4.050e+00 4.040e+00
 4.030e+00 4.010e+00 3.980e+00 3.970e+00 3.960e+00 3.950e+00 3.940e+00
 3.910e+00 3.900e+00 3.890e+00 3.880e+00 3.870e+00 3.850e+00 3.840e+00
 3.830e+00 3.800e+00 3.790e+00 3.770e+00 3.760e+00 3.740e+00 3.730e+00
 3.720e+00 3.710e+00 3.700e+00 3.670e+00 3.660e+00 3.650e+00 3.640e+00
 3.630e+00 3.620e+00 3.610e+00 3.600e+00 3.590e+00 3.580e+00 3.560e+00
 3.540e+00 3.530e+00 3.520e+00 3.510e+00 3.500e+00 3.490e+00 3.480e+00
 3.470e+00 3.460e+00 3.450e+00 3.440e+00 3.420e+00 3.410e+00 3.400e+00
 3.390e+00 3.380e+00 3.370e+00 3.360e+00 3.350e+00 3.340e+00 3.330e+00
 3.320e+00 3.310e+00 3.300e+00 3.280e+00 3.270e+00 3.260e+00 3.250e+00
 3.240e+00 3.230e+00 3.210e+00 3.200e+00 3.190e+00 3.180e+00 3.170e+00
 3.150e+00 3.140e+00 3.130e+00 3.120e+00 3.110e+00 3.100e+00 3.090e+00
 3.080e+00 3.070e+00 3.060e+00 3.050e+00 3.040e+00 3.030e+00 3.020e+00
 3.010e+00 3.000e+00 2.990e+00 2.960e+00 2.950e+00 2.940e+00 2.930e+00
 2.920e+00 2.910e+00 2.900e+00 2.890e+00 2.880e+00 2.870e+00 2.860e+00
 2.850e+00 2.840e+00 2.830e+00 2.820e+00 2.810e+00 2.800e+00 2.790e+00
 2.780e+00 2.770e+00 2.760e+00 2.750e+00 2.730e+00 2.710e+00 2.700e+00
 2.690e+00 2.680e+00 2.670e+00 2.660e+00 2.650e+00 2.630e+00 2.620e+00
 2.610e+00 2.600e+00 2.590e+00 2.580e+00 2.570e+00 2.560e+00 2.540e+00
 2.530e+00 2.520e+00 2.500e+00 2.490e+00 2.480e+00 2.470e+00 2.460e+00
 2.450e+00 2.440e+00 2.430e+00 2.420e+00 2.410e+00 2.400e+00 2.390e+00
 2.380e+00 2.370e+00 2.360e+00 2.350e+00 2.340e+00 2.320e+00 2.310e+00
 2.300e+00 2.290e+00 2.280e+00 2.270e+00 2.260e+00 2.250e+00 2.240e+00
 2.230e+00 2.220e+00 2.210e+00 2.200e+00 2.190e+00 2.180e+00 2.170e+00
 2.160e+00 2.150e+00 2.140e+00 2.130e+00 2.120e+00 2.110e+00 2.100e+00
 2.090e+00 2.080e+00 2.070e+00 2.060e+00 2.050e+00 2.040e+00 2.030e+00
 2.020e+00 2.010e+00 2.000e+00 1.990e+00 1.980e+00 1.970e+00 1.960e+00
 1.950e+00 1.940e+00 1.930e+00 1.920e+00 1.910e+00 1.900e+00 1.890e+00
 1.880e+00 1.870e+00 1.860e+00 1.850e+00 1.840e+00 1.830e+00 1.820e+00
 1.810e+00 1.800e+00 1.790e+00 1.780e+00 1.770e+00 1.760e+00 1.750e+00
 1.740e+00 1.730e+00 1.720e+00 1.710e+00 1.700e+00 1.690e+00 1.680e+00
 1.670e+00 1.660e+00 1.650e+00 1.640e+00 1.630e+00 1.620e+00 1.610e+00
 1.600e+00 1.590e+00 1.580e+00 1.570e+00 1.560e+00 1.550e+00 1.540e+00
 1.530e+00 1.520e+00 1.510e+00 1.500e+00 1.490e+00 1.480e+00 1.470e+00
 1.460e+00 1.450e+00 1.440e+00 1.430e+00 1.420e+00 1.410e+00 1.400e+00
 1.390e+00 1.380e+00 1.370e+00 1.360e+00 1.350e+00 1.340e+00 1.330e+00
 1.320e+00 1.310e+00 1.300e+00 1.290e+00 1.280e+00 1.270e+00 1.260e+00
 1.250e+00 1.240e+00 1.230e+00 1.220e+00 1.210e+00 1.200e+00 1.190e+00
 1.180e+00 1.170e+00 1.160e+00 1.150e+00 1.140e+00 1.130e+00 1.120e+00
 1.110e+00 1.100e+00 1.090e+00 1.080e+00 1.070e+00 1.060e+00 1.050e+00
 1.040e+00 1.030e+00 1.020e+00 1.010e+00 1.000e+00 9.900e-01 9.800e-01
 9.700e-01 9.600e-01 9.500e-01 9.400e-01 9.300e-01 9.200e-01 9.100e-01
 9.000e-01 8.900e-01 8.800e-01 8.700e-01 8.600e-01 8.500e-01 8.400e-01
 8.300e-01 8.200e-01 8.100e-01 8.000e-01 7.900e-01 7.800e-01 7.700e-01
 7.600e-01 7.500e-01 7.400e-01 7.300e-01 7.200e-01 7.100e-01 7.000e-01
 6.900e-01 6.800e-01 6.700e-01 6.600e-01 6.500e-01 6.400e-01 6.300e-01
 6.200e-01 6.100e-01 6.000e-01 5.900e-01 5.800e-01 5.700e-01 5.600e-01
 5.500e-01 5.400e-01 5.300e-01 5.200e-01 5.100e-01 5.000e-01 4.900e-01
 4.800e-01 4.700e-01 4.600e-01 4.500e-01 4.400e-01 4.300e-01 4.200e-01
 4.100e-01 4.000e-01 3.900e-01 3.800e-01 3.700e-01 3.600e-01 3.500e-01
 3.400e-01 3.300e-01 3.200e-01 3.100e-01 3.000e-01 2.900e-01 2.800e-01
 2.700e-01 2.600e-01 2.500e-01 2.400e-01 2.300e-01 2.200e-01 2.100e-01
 2.000e-01 1.900e-01 1.800e-01 1.700e-01 1.600e-01 1.500e-01 1.400e-01
 1.300e-01 1.200e-01 1.100e-01 1.000e-01 9.000e-02 8.000e-02 7.000e-02
 6.000e-02 5.000e-02 4.000e-02 3.000e-02 2.000e-02 1.000e-02]
 ****************************************************************************************************

In [132]:
# Repair 'user_score' column: replace the 'tbd' to NaN value then convert the data type from object into float. 
df['user_score']= df['user_score'].replace('tbd',np.nan) 
df['user_score']= df['user_score'].astype(float)  
df['user_score'].dtype

dtype('float64')

In [133]:
df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,<NA>,<NA>
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,<NA>,<NA>

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16719 entries, 0 to 16718
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16717 non-null  string
 1   platform         16719 non-null  string
 2   year_of_release  16450 non-null  Int64
 3   genre            16717 non-null  string
 4   publisher        16665 non-null  string
 5   na_sales         16719 non-null  float64
 6   eu_sales         16719 non-null  float64
 7   jp_sales         16719 non-null  float64
 8   other_sales      16719 non-null  float64
 9   global_sales     16719 non-null  float64
 10  user_score       7590 non-null   float64
 11  developer        10096 non-null  string
 12  rating           9950 non-null   string
dtypes: Int64(1), float64(6), string(6)
memory usage: 1.8 MB

#### Additional Features to Enhance Understanding and better explanation
###### Sales Category: Define a function to categorize sales and apply it in the existing global_sales to create a new feature named sales_category.
###### Game Age Category: Calulate game age and define a function to categorize game age is it new, recent, old or classic.

In [135]:
# Sales Category

df['global_sales'] = pd.to_numeric(df['global_sales'], errors='coerce')   # to ensure global_sales is numeric

def categorize_sales(value):
    
    if 0 <= value < 25:
        return 'low'
    elif 25 <= value < 50:
        return 'medium'
    elif 50 <= value < 75:
        return 'high'
    elif 75 <= value <= 100:
        return 'best_seller'
    else:
        return 'out_of_range'  # optional for values > 100

# Apply the function to create a new column
df['sales_category'] = df['global_sales'].apply(categorize_sales)

print(df[['name','global_sales','sales_category']].head())

                       name  global_sales sales_category
0                Wii Sports         82.53    best_seller
1         Super Mario Bros.         40.24         medium
2            Mario Kart Wii         35.52         medium
3         Wii Sports Resort         32.77         medium
4  Pokemon Red/Pokemon Blue         31.37         medium

In [136]:
# Game Age Category

current_year= datetime.datetime.now().year
df['game_age']=current_year - df['year_of_release']      # Calulate Gmae age

print(df[['year_of_release','game_age']].head())

   year_of_release  game_age
0             2006        20
1             1985        41
2             2008        18
3             2009        17
4             1996        30

In [137]:
def categorize_age(value):
    
    if value < 5:
        return 'new'
    elif 5 <= value < 15:
        return 'recent'
    else:
        return 'old'
    
# Apply the function to create a new column
df['game_age_category'] = df['game_age'].apply(categorize_age)

print(df[['game_age_category','game_age']].head())

  game_age_category  game_age
0               old        20
1               old        41
2               old        18
3               old        17
4               old        30

#### Validate data quality (after cleaning)

In [138]:
print(df.shape)
df.head()

(16719, 16)

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20,old
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,<NA>,<NA>,medium,41,old
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E,medium,18,old
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E,medium,17,old
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,<NA>,<NA>,medium,30,old

In [139]:
df.dtypes

name                 string[python]
platform             string[python]
year_of_release               Int64
genre                string[python]
publisher            string[python]
na_sales                    float64
eu_sales                    float64
jp_sales                    float64
other_sales                 float64
global_sales                float64
user_score                  float64
developer            string[python]
rating               string[python]
sales_category               object
game_age                      Int64
game_age_category            object
dtype: object

In [140]:
df.isna().sum().sort_values(ascending=False)

user_score           9129
rating               6769
developer            6623
year_of_release       269
game_age              269
publisher              54
genre                   2
name                    2
jp_sales                0
eu_sales                0
na_sales                0
platform                0
other_sales             0
global_sales            0
sales_category          0
game_age_category       0
dtype: int64

In [141]:
# Final data check: show column names, unique counts, and values
for col in df:
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

name
11562
<StringArray>
[                                                 'Wii Sports',
                                           'Super Mario Bros.',
                                              'Mario Kart Wii',
                                           'Wii Sports Resort',
                                    'Pokemon Red/Pokemon Blue',
                                                      'Tetris',
                                       'New Super Mario Bros.',
                                                    'Wii Play',
                                   'New Super Mario Bros. Wii',
                                                   'Duck Hunt',
 ...
                                    'Mezase!! Tsuri Master DS',
 'Eiyuu Densetsu: Sora no Kiseki Material Collection Portable',
                                     'STORM: Frontline Nation',
                                            'Strawberry Nauts',
                                                    'Plushees',
                                                     '15 Days',
                                            'Aiyoku no Eustia',
                          'Woody Woodpecker in Crazy Castle 5',
                                            'LMA Manager 2007',
                                     'Haitaka no Psychedelica']
Length: 11563, dtype: string
 ****************************************************************************************************
platform
31
<StringArray>
[ 'Wii',  'NES',   'GB',   'DS', 'X360',  'PS3',  'PS2', 'SNES',  'GBA',
  'PS4',  '3DS',  'N64',   'PS',   'XB',   'PC', '2600',  'PSP', 'XOne',
 'WiiU',   'GC',  'GEN',   'DC',  'PSV',  'SAT',  'SCD',   'WS',   'NG',
 'TG16',  '3DO',   'GG', 'PCFX']
Length: 31, dtype: string
 ****************************************************************************************************
year_of_release
39
<IntegerArray>
[2006, 1985, 2008, 2009, 1996, 1989, 1984, 2005, 1999, 2007, 2010, 2013, 2004,
 1990, 1988, 2002, 2001, 2011, 1998, 2015, 2012, 2014, 1992, 1997, 1993, 1994,
 1982, 2016, 2003, 1986, 2000, <NA>, 1995, 1991, 1981, 1987, 1980, 1983, 2020,
 2017]
Length: 40, dtype: Int64
 ****************************************************************************************************
genre
12
<StringArray>
[      'Sports',     'Platform',       'Racing', 'Role-Playing',
       'Puzzle',         'Misc',      'Shooter',   'Simulation',
       'Action',     'Fighting',    'Adventure',     'Strategy',
           <NA>]
Length: 13, dtype: string
 ****************************************************************************************************
publisher
580
<StringArray>
[                   'nintendo',      'microsoft game studios',
        'take two interactive', 'sony computer entertainment',
                  'activision',                     'ubisoft',
          'bethesda softworks',             'electronic arts',
                        'sega',                  'squaresoft',
 ...
                      'piacci',         'paradox development',
                     'otomate',       'ascaron entertainment',
                   'ongakukan',                    'commseed',
           'uig entertainment',                      'takuyo',
          'interchannel holon',                'red flagship']
Length: 581, dtype: string
 ****************************************************************************************************
na_sales
402
[4.136e+01 2.908e+01 1.568e+01 1.561e+01 1.127e+01 2.320e+01 1.128e+01
 1.396e+01 1.444e+01 2.693e+01 9.050e+00 9.710e+00 9.000e+00 8.920e+00
 1.500e+01 9.010e+00 7.020e+00 9.430e+00 1.278e+01 4.740e+00 6.380e+00
 1.083e+01 9.540e+00 9.660e+00 8.410e+00 6.060e+00 3.430e+00 5.510e+00
 6.850e+00 9.040e+00 5.890e+00 6.030e+00 9.700e+00 5.280e+00 4.990e+00
 8.250e+00 8.520e+00 5.540e+00 6.990e+00 6.620e+00 5.030e+00 5.990e+00
 3.960e+00 2.500e+00 7.970e+00 6.910e+00 4.340e+00 4.350e+00 3.010e+00
 6.160e+00 6.760e+00 4.020e+00 4.890e+00 2.960e+00 4.760e+00 5.010e+00
 6.730e+00 5.950e+00 3.660e+00 5.550e+00 7.040e+00 6.650e+00 3.880e+00
 5.800e+00 4.100e+00 5.930e+00 4.360e+00 5.700e+00 2.030e+00 4.400e+00
 5.050e+00 3.540e+00 1.120e+00 6.820e+00 1.750e+00 3.740e+00 1.060e+00
 2.790e+00 2.910e+00 9.900e-01 2.570e+00 2.990e+00 2.280e+00 7.280e+00
 2.760e+00 2.900e+00 2.810e+00 6.600e-01 3.780e+00 3.270e+00 3.560e+00
 5.390e+00 4.590e+00 4.810e+00 4.460e+00 3.480e+00 2.850e+00 2.530e+00
 2.980e+00 3.680e+00 3.150e+00 4.410e+00 4.120e+00 2.710e+00 2.930e+00
 3.230e+00 4.050e+00 4.150e+00 2.770e+00 3.450e+00 3.110e+00 8.400e-01
 1.660e+00 7.800e-01 2.640e+00 3.170e+00 4.980e+00 2.550e+00 3.640e+00
 3.700e+00 4.010e+00 2.470e+00 8.000e-02 3.920e+00 8.000e-01 2.450e+00
 4.470e+00 3.180e+00 2.630e+00 1.880e+00 2.410e+00 2.800e+00 6.300e-01
 2.260e+00 2.490e+00 3.570e+00 3.070e+00 2.970e+00 2.950e+00 2.540e+00
 3.280e+00 3.140e+00 4.700e-01 2.620e+00 3.210e+00 2.070e+00 2.730e+00
 1.850e+00 2.180e+00 1.740e+00 3.020e+00 1.620e+00 3.130e+00 1.920e+00
 3.330e+00 3.220e+00 2.300e+00 4.260e+00 9.700e-01 6.500e-01 1.210e+00
 1.090e+00 2.100e+00 2.440e+00 1.980e+00 3.810e+00 3.590e+00 1.630e+00
 1.960e+00 3.400e+00 6.100e-01 2.050e+00 1.700e+00 3.420e+00 3.360e+00
 3.490e+00 3.050e+00 1.830e+00 2.310e+00 3.980e+00 0.000e+00 2.600e+00
 1.910e+00 2.740e+00 2.830e+00 2.360e+00 1.730e+00 1.940e+00 2.290e+00
 1.820e+00 2.420e+00 3.040e+00 1.800e+00 2.080e+00 1.870e+00 4.180e+00
 3.190e+00 4.210e+00 3.630e+00 2.780e+00 2.000e-01 1.610e+00 1.540e+00
 2.520e+00 2.660e+00 1.000e-01 2.820e+00 2.190e+00 1.560e+00 3.030e+00
 2.200e+00 2.090e+00 2.110e+00 1.480e+00 4.000e+00 5.800e-01 2.510e+00
 3.000e+00 2.240e+00 1.460e+00 1.410e+00 9.200e-01 8.800e-01 1.280e+00
 2.250e+00 3.380e+00 2.040e+00 3.790e+00 4.030e+00 1.650e+00 7.100e-01
 1.420e+00 1.100e+00 2.320e+00 1.200e-01 2.350e+00 2.120e+00 1.400e+00
 1.680e+00 1.130e+00 1.220e+00 2.670e+00 1.020e+00 1.190e+00 1.530e+00
 2.150e+00 9.000e-01 1.970e+00 6.800e-01 1.160e+00 9.300e-01 1.440e+00
 1.600e-01 2.130e+00 2.210e+00 1.780e+00 8.600e-01 1.350e+00 1.050e+00
 2.230e+00 2.400e+00 1.370e+00 1.300e+00 1.950e+00 1.930e+00 1.330e+00
 1.490e+00 1.580e+00 5.000e-02 6.000e-01 2.020e+00 2.380e+00 1.600e+00
 2.010e+00 1.570e+00 1.230e+00 1.900e+00 2.140e+00 1.170e+00 2.270e+00
 1.640e+00 5.900e-01 1.550e+00 4.600e-01 8.100e-01 1.450e+00 2.700e-01
 1.470e+00 1.990e+00 1.500e+00 9.000e-02 2.610e+00 1.890e+00 5.000e-01
 8.900e-01 9.500e-01 2.340e+00 7.200e-01 1.720e+00 1.180e+00 1.760e+00
 7.300e-01 1.270e+00 2.060e+00 5.500e-01 1.520e+00 1.690e+00 2.170e+00
 5.100e-01 1.000e+00 1.290e+00 1.380e+00 1.150e+00 1.670e+00 1.360e+00
 1.010e+00 1.040e+00 1.840e+00 2.220e+00 7.900e-01 1.510e+00 1.070e+00
 1.320e+00 1.590e+00 2.000e-02 2.900e-01 1.250e+00 2.560e+00 1.430e+00
 1.200e+00 4.100e-01 2.800e-01 4.300e-01 6.900e-01 2.000e+00 7.600e-01
 1.860e+00 4.800e-01 6.200e-01 1.310e+00 3.700e-01 1.500e-01 6.400e-01
 2.600e-01 4.900e-01 1.110e+00 1.300e-01 1.810e+00 1.030e+00 1.260e+00
 8.700e-01 7.700e-01 9.600e-01 1.390e+00 1.080e+00 8.500e-01 9.100e-01
 3.000e-01 3.800e-01 9.400e-01 7.000e-02 1.340e+00 1.240e+00 3.400e-01
 1.400e-01 1.000e-02 5.200e-01 8.200e-01 8.300e-01 1.100e-01 2.500e-01
 1.770e+00 3.600e-01 7.500e-01 7.400e-01 1.800e-01 2.200e-01 5.300e-01
 4.200e-01 3.200e-01 3.900e-01 2.400e-01 2.300e-01 6.000e-02 4.500e-01
 7.000e-01 6.700e-01 3.500e-01 5.600e-01 1.140e+00 9.800e-01 5.700e-01
 5.400e-01 4.000e-02 1.700e-01 4.400e-01 3.000e-02 3.300e-01 3.100e-01
 4.000e-01 2.100e-01 1.900e-01]
 ****************************************************************************************************
eu_sales
307
[2.896e+01 3.580e+00 1.276e+01 1.093e+01 8.890e+00 2.260e+00 9.140e+00
 9.180e+00 6.940e+00 6.300e-01 1.095e+01 7.470e+00 6.180e+00 8.030e+00
 4.890e+00 8.490e+00 9.090e+00 4.000e-01 3.750e+00 9.200e+00 4.460e+00
 2.710e+00 3.440e+00 5.140e+00 5.490e+00 3.900e+00 5.350e+00 3.170e+00
 5.090e+00 4.240e+00 5.040e+00 5.860e+00 3.680e+00 4.190e+00 5.730e+00
 3.590e+00 4.510e+00 2.550e+00 4.020e+00 4.370e+00 6.310e+00 3.450e+00
 2.810e+00 2.850e+00 3.490e+00 1.000e-02 3.350e+00 2.040e+00 3.070e+00
 3.870e+00 3.000e+00 4.820e+00 3.640e+00 2.150e+00 3.690e+00 2.650e+00
 2.560e+00 3.110e+00 3.140e+00 1.940e+00 1.950e+00 2.470e+00 2.280e+00
 3.420e+00 3.630e+00 2.360e+00 1.710e+00 1.850e+00 2.790e+00 1.240e+00
 6.120e+00 1.530e+00 3.470e+00 2.240e+00 5.010e+00 2.010e+00 1.720e+00
 2.070e+00 6.420e+00 3.860e+00 4.500e-01 3.480e+00 1.890e+00 5.750e+00
 2.170e+00 1.370e+00 2.350e+00 1.180e+00 2.110e+00 1.880e+00 2.830e+00
 2.990e+00 2.890e+00 3.270e+00 2.220e+00 2.140e+00 1.450e+00 1.750e+00
 1.040e+00 1.770e+00 3.020e+00 2.750e+00 2.160e+00 1.900e+00 2.590e+00
 2.200e+00 4.300e+00 9.300e-01 2.530e+00 2.520e+00 1.790e+00 1.300e+00
 2.600e+00 1.580e+00 1.200e+00 1.560e+00 1.340e+00 1.260e+00 8.300e-01
 6.210e+00 2.800e+00 1.590e+00 1.730e+00 4.330e+00 1.830e+00 0.000e+00
 2.180e+00 1.980e+00 1.470e+00 6.700e-01 1.550e+00 1.910e+00 6.900e-01
 6.000e-01 1.930e+00 1.640e+00 5.500e-01 2.190e+00 1.110e+00 2.290e+00
 2.500e+00 9.600e-01 1.210e+00 1.120e+00 7.700e-01 1.690e+00 1.080e+00
 7.900e-01 2.370e+00 2.460e+00 2.600e-01 7.500e-01 1.250e+00 2.430e+00
 9.800e-01 7.400e-01 2.230e+00 6.100e-01 2.450e+00 1.410e+00 1.800e+00
 3.280e+00 1.160e+00 1.990e+00 1.380e+00 1.360e+00 1.170e+00 1.190e+00
 9.900e-01 1.680e+00 2.000e+00 1.330e+00 1.570e+00 1.480e+00 2.100e+00
 1.270e+00 1.970e+00 9.100e-01 1.390e+00 1.960e+00 2.400e-01 1.510e+00
 1.400e-01 1.290e+00 2.390e+00 1.030e+00 5.000e-01 5.800e-01 1.310e+00
 2.020e+00 1.320e+00 1.010e+00 2.270e+00 2.300e+00 1.820e+00 2.780e+00
 4.400e-01 4.800e-01 2.700e-01 2.100e-01 2.480e+00 5.100e-01 1.520e+00
 4.000e-02 2.800e-01 1.350e+00 8.700e-01 2.130e+00 1.130e+00 1.760e+00
 7.600e-01 2.120e+00 6.600e-01 1.600e+00 1.440e+00 1.430e+00 1.700e+00
 4.700e-01 1.870e+00 8.600e-01 7.300e-01 1.280e+00 8.100e-01 1.090e+00
 6.800e-01 1.220e+00 1.400e+00 1.020e+00 1.490e+00 1.140e+00 4.900e-01
 9.000e-01 3.800e-01 1.420e+00 9.500e-01 1.620e+00 7.100e-01 1.050e+00
 9.200e-01 3.300e-01 3.000e-01 1.670e+00 1.000e+00 8.900e-01 1.000e-01
 7.200e-01 5.900e-01 5.600e-01 1.600e-01 9.700e-01 6.200e-01 8.500e-01
 9.400e-01 8.800e-01 8.400e-01 1.060e+00 2.000e-01 1.150e+00 8.000e-01
 1.100e+00 7.000e-01 1.920e+00 3.200e-01 1.500e-01 5.300e-01 9.000e-02
 1.460e+00 2.900e-01 2.200e-01 1.230e+00 7.000e-02 1.700e-01 5.400e-01
 3.600e-01 3.100e-01 1.840e+00 5.200e-01 1.100e-01 6.400e-01 1.200e-01
 2.050e+00 1.630e+00 8.200e-01 8.000e-02 5.700e-01 1.650e+00 1.900e-01
 2.000e-02 4.300e-01 2.500e-01 1.500e+00 1.800e-01 3.900e-01 1.300e-01
 1.070e+00 4.600e-01 4.100e-01 6.000e-02 3.000e-02 3.700e-01 5.000e-02
 2.300e-01 6.500e-01 4.200e-01 3.400e-01 3.500e-01 7.800e-01]
 ****************************************************************************************************
jp_sales
244
[3.770e+00 6.810e+00 3.790e+00 3.280e+00 1.022e+01 4.220e+00 6.500e+00
 2.930e+00 4.700e+00 2.800e-01 1.930e+00 4.130e+00 7.200e+00 3.600e+00
 2.400e-01 2.530e+00 9.800e-01 4.100e-01 3.540e+00 4.160e+00 6.040e+00
 4.180e+00 3.840e+00 6.000e-02 4.700e-01 5.380e+00 5.320e+00 5.650e+00
 1.870e+00 1.300e-01 3.120e+00 3.600e-01 1.100e-01 4.350e+00 6.500e-01
 7.000e-02 8.000e-02 4.900e-01 3.000e-01 2.660e+00 2.690e+00 4.800e-01
 3.800e-01 5.330e+00 1.910e+00 3.960e+00 3.100e+00 1.100e+00 1.200e+00
 1.400e-01 2.540e+00 2.140e+00 8.100e-01 2.120e+00 4.400e-01 3.150e+00
 1.250e+00 4.000e-02 0.000e+00 2.470e+00 2.230e+00 1.690e+00 1.000e-02
 3.000e+00 2.000e-02 4.390e+00 1.980e+00 1.000e-01 3.810e+00 5.000e-02
 2.490e+00 1.580e+00 3.140e+00 2.730e+00 6.600e-01 2.200e-01 3.630e+00
 1.450e+00 1.310e+00 2.430e+00 7.000e-01 3.500e-01 1.400e+00 6.000e-01
 2.260e+00 1.420e+00 1.280e+00 1.390e+00 8.700e-01 1.700e-01 9.400e-01
 1.900e-01 2.100e-01 1.600e+00 1.600e-01 1.030e+00 2.500e-01 2.060e+00
 1.490e+00 1.290e+00 9.000e-02 2.870e+00 3.000e-02 7.800e-01 8.300e-01
 2.330e+00 2.020e+00 1.360e+00 1.810e+00 1.970e+00 9.100e-01 9.900e-01
 9.500e-01 2.000e+00 1.010e+00 2.780e+00 2.110e+00 1.090e+00 2.000e-01
 1.900e+00 1.270e+00 3.610e+00 1.570e+00 2.200e+00 1.700e+00 1.080e+00
 1.500e-01 1.110e+00 2.900e-01 1.540e+00 1.200e-01 8.900e-01 4.870e+00
 1.520e+00 1.320e+00 1.150e+00 4.100e+00 1.460e+00 4.600e-01 1.050e+00
 1.610e+00 2.600e-01 1.380e+00 6.200e-01 7.300e-01 5.700e-01 3.100e-01
 5.800e-01 1.760e+00 2.100e+00 9.000e-01 5.100e-01 6.400e-01 2.460e+00
 2.300e-01 3.700e-01 9.200e-01 1.070e+00 2.620e+00 1.120e+00 5.400e-01
 2.700e-01 5.900e-01 3.670e+00 5.500e-01 1.750e+00 3.440e+00 3.300e-01
 2.550e+00 2.320e+00 2.790e+00 7.400e-01 3.180e+00 8.200e-01 7.700e-01
 4.000e-01 2.350e+00 3.190e+00 8.000e-01 7.600e-01 3.030e+00 8.800e-01
 4.500e-01 1.160e+00 3.400e-01 1.190e+00 1.130e+00 2.130e+00 1.960e+00
 7.100e-01 1.040e+00 2.680e+00 6.800e-01 2.650e+00 9.600e-01 2.410e+00
 5.200e-01 1.800e-01 1.340e+00 1.480e+00 2.340e+00 1.060e+00 1.210e+00
 2.290e+00 1.630e+00 2.050e+00 2.170e+00 1.560e+00 1.350e+00 1.330e+00
 6.300e-01 7.900e-01 7.500e-01 5.300e-01 1.530e+00 1.300e+00 3.900e-01
 6.900e-01 4.200e-01 9.300e-01 5.600e-01 8.400e-01 7.200e-01 3.200e-01
 1.710e+00 1.650e+00 6.100e-01 1.510e+00 1.500e+00 1.440e+00 1.240e+00
 1.180e+00 1.370e+00 1.000e+00 1.260e+00 8.500e-01 4.300e-01 6.700e-01
 1.140e+00 8.600e-01 1.170e+00 5.000e-01 1.020e+00 9.700e-01]
 ****************************************************************************************************
other_sales
155
[8.450e+00 7.700e-01 3.290e+00 2.950e+00 1.000e+00 5.800e-01 2.880e+00
 2.840e+00 2.240e+00 4.700e-01 2.740e+00 1.900e+00 7.100e-01 2.150e+00
 1.690e+00 1.770e+00 3.960e+00 1.057e+01 5.500e-01 2.040e+00 1.360e+00
 4.200e-01 4.600e-01 1.410e+00 1.780e+00 5.000e-01 1.180e+00 8.000e-01
 1.160e+00 1.320e+00 5.900e-01 2.380e+00 1.130e+00 7.800e-01 2.420e+00
 1.120e+00 1.280e+00 1.570e+00 1.300e+00 1.010e+00 9.100e-01 1.790e+00
 1.970e+00 8.600e-01 1.210e+00 2.300e-01 7.600e-01 7.400e-01 7.530e+00
 2.900e-01 1.030e+00 5.200e-01 2.110e+00 1.600e+00 1.610e+00 3.500e-01
 9.700e-01 1.060e+00 6.300e-01 1.500e-01 7.900e-01 9.600e-01 1.250e+00
 9.000e-01 8.100e-01 3.900e-01 6.800e-01 8.500e-01 1.800e-01 8.000e-02
 6.700e-01 7.000e-01 4.100e-01 3.300e-01 6.000e-01 5.400e-01 1.730e+00
 1.230e+00 1.600e-01 1.110e+00 3.100e-01 4.800e-01 6.200e-01 1.900e-01
 6.900e-01 1.020e+00 7.300e-01 1.080e+00 4.500e-01 2.800e-01 5.100e-01
 2.200e-01 1.090e+00 9.900e-01 3.000e-01 6.400e-01 6.600e-01 9.800e-01
 1.390e+00 1.400e-01 1.370e+00 7.000e-02 2.100e-01 6.100e-01 1.700e-01
 1.200e-01 0.000e+00 7.200e-01 2.400e-01 8.200e-01 1.740e+00 8.700e-01
 9.200e-01 5.700e-01 1.100e-01 4.000e-02 5.600e-01 2.000e-01 3.400e-01
 9.000e-02 8.300e-01 4.400e-01 6.000e-02 3.200e-01 3.800e-01 1.480e+00
 3.700e-01 1.000e-01 2.500e-01 3.600e-01 1.300e-01 4.300e-01 5.000e-02
 2.000e-02 2.600e-01 4.000e-01 7.500e-01 1.930e+00 8.400e-01 5.300e-01
 8.900e-01 1.670e+00 2.700e-01 2.930e+00 4.900e-01 1.000e-02 2.460e+00
 3.000e-02 1.510e+00 2.050e+00 1.680e+00 1.820e+00 1.330e+00 9.400e-01
 9.300e-01]
 ****************************************************************************************************
global_sales
629
[8.253e+01 4.024e+01 3.552e+01 3.277e+01 3.137e+01 3.026e+01 2.980e+01
 2.892e+01 2.832e+01 2.831e+01 2.467e+01 2.321e+01 2.310e+01 2.270e+01
 2.181e+01 2.179e+01 2.104e+01 2.081e+01 2.061e+01 2.015e+01 1.825e+01
 1.814e+01 1.728e+01 1.627e+01 1.615e+01 1.585e+01 1.529e+01 1.514e+01
 1.498e+01 1.473e+01 1.464e+01 1.463e+01 1.461e+01 1.460e+01 1.379e+01
 1.367e+01 1.347e+01 1.332e+01 1.310e+01 1.284e+01 1.266e+01 1.263e+01
 1.261e+01 1.213e+01 1.212e+01 1.189e+01 1.177e+01 1.168e+01 1.166e+01
 1.135e+01 1.118e+01 1.101e+01 1.095e+01 1.081e+01 1.070e+01 1.060e+01
 1.055e+01 1.050e+01 1.049e+01 1.030e+01 1.025e+01 1.012e+01 9.900e+00
 9.870e+00 9.860e+00 9.720e+00 9.710e+00 9.490e+00 9.440e+00 9.360e+00
 9.310e+00 9.300e+00 9.180e+00 9.160e+00 8.910e+00 8.790e+00 8.760e+00
 8.570e+00 8.490e+00 8.380e+00 8.270e+00 8.160e+00 8.090e+00 8.070e+00
 8.050e+00 8.010e+00 7.990e+00 7.980e+00 7.860e+00 7.810e+00 7.720e+00
 7.690e+00 7.660e+00 7.600e+00 7.590e+00 7.580e+00 7.550e+00 7.510e+00
 7.460e+00 7.390e+00 7.380e+00 7.320e+00 7.200e+00 7.170e+00 7.160e+00
 7.150e+00 7.140e+00 7.130e+00 7.090e+00 7.070e+00 6.950e+00 6.900e+00
 6.830e+00 6.820e+00 6.760e+00 6.750e+00 6.740e+00 6.710e+00 6.680e+00
 6.660e+00 6.650e+00 6.620e+00 6.510e+00 6.490e+00 6.470e+00 6.450e+00
 6.440e+00 6.430e+00 6.410e+00 6.400e+00 6.390e+00 6.340e+00 6.320e+00
 6.310e+00 6.300e+00 6.290e+00 6.270e+00 6.210e+00 6.190e+00 6.090e+00
 6.080e+00 6.050e+00 6.030e+00 5.990e+00 5.950e+00 5.870e+00 5.820e+00
 5.780e+00 5.740e+00 5.640e+00 5.630e+00 5.580e+00 5.550e+00 5.540e+00
 5.490e+00 5.480e+00 5.470e+00 5.460e+00 5.450e+00 5.420e+00 5.390e+00
 5.380e+00 5.340e+00 5.330e+00 5.310e+00 5.300e+00 5.290e+00 5.270e+00
 5.260e+00 5.240e+00 5.230e+00 5.220e+00 5.210e+00 5.200e+00 5.190e+00
 5.160e+00 5.150e+00 5.140e+00 5.130e+00 5.120e+00 5.100e+00 5.090e+00
 5.080e+00 5.070e+00 5.050e+00 5.030e+00 5.020e+00 5.010e+00 5.000e+00
 4.980e+00 4.930e+00 4.920e+00 4.910e+00 4.880e+00 4.870e+00 4.850e+00
 4.840e+00 4.820e+00 4.800e+00 4.790e+00 4.760e+00 4.730e+00 4.710e+00
 4.700e+00 4.680e+00 4.670e+00 4.630e+00 4.620e+00 4.610e+00 4.600e+00
 4.590e+00 4.570e+00 4.530e+00 4.500e+00 4.490e+00 4.480e+00 4.470e+00
 4.460e+00 4.450e+00 4.430e+00 4.420e+00 4.410e+00 4.390e+00 4.380e+00
 4.370e+00 4.360e+00 4.340e+00 4.330e+00 4.320e+00 4.310e+00 4.290e+00
 4.280e+00 4.270e+00 4.240e+00 4.230e+00 4.220e+00 4.210e+00 4.200e+00
 4.190e+00 4.180e+00 4.170e+00 4.160e+00 4.140e+00 4.120e+00 4.110e+00
 4.100e+00 4.090e+00 4.080e+00 4.070e+00 4.060e+00 4.050e+00 4.040e+00
 4.030e+00 4.010e+00 3.980e+00 3.970e+00 3.960e+00 3.950e+00 3.940e+00
 3.910e+00 3.900e+00 3.890e+00 3.880e+00 3.870e+00 3.850e+00 3.840e+00
 3.830e+00 3.800e+00 3.790e+00 3.770e+00 3.760e+00 3.740e+00 3.730e+00
 3.720e+00 3.710e+00 3.700e+00 3.670e+00 3.660e+00 3.650e+00 3.640e+00
 3.630e+00 3.620e+00 3.610e+00 3.600e+00 3.590e+00 3.580e+00 3.560e+00
 3.540e+00 3.530e+00 3.520e+00 3.510e+00 3.500e+00 3.490e+00 3.480e+00
 3.470e+00 3.460e+00 3.450e+00 3.440e+00 3.420e+00 3.410e+00 3.400e+00
 3.390e+00 3.380e+00 3.370e+00 3.360e+00 3.350e+00 3.340e+00 3.330e+00
 3.320e+00 3.310e+00 3.300e+00 3.280e+00 3.270e+00 3.260e+00 3.250e+00
 3.240e+00 3.230e+00 3.210e+00 3.200e+00 3.190e+00 3.180e+00 3.170e+00
 3.150e+00 3.140e+00 3.130e+00 3.120e+00 3.110e+00 3.100e+00 3.090e+00
 3.080e+00 3.070e+00 3.060e+00 3.050e+00 3.040e+00 3.030e+00 3.020e+00
 3.010e+00 3.000e+00 2.990e+00 2.960e+00 2.950e+00 2.940e+00 2.930e+00
 2.920e+00 2.910e+00 2.900e+00 2.890e+00 2.880e+00 2.870e+00 2.860e+00
 2.850e+00 2.840e+00 2.830e+00 2.820e+00 2.810e+00 2.800e+00 2.790e+00
 2.780e+00 2.770e+00 2.760e+00 2.750e+00 2.730e+00 2.710e+00 2.700e+00
 2.690e+00 2.680e+00 2.670e+00 2.660e+00 2.650e+00 2.630e+00 2.620e+00
 2.610e+00 2.600e+00 2.590e+00 2.580e+00 2.570e+00 2.560e+00 2.540e+00
 2.530e+00 2.520e+00 2.500e+00 2.490e+00 2.480e+00 2.470e+00 2.460e+00
 2.450e+00 2.440e+00 2.430e+00 2.420e+00 2.410e+00 2.400e+00 2.390e+00
 2.380e+00 2.370e+00 2.360e+00 2.350e+00 2.340e+00 2.320e+00 2.310e+00
 2.300e+00 2.290e+00 2.280e+00 2.270e+00 2.260e+00 2.250e+00 2.240e+00
 2.230e+00 2.220e+00 2.210e+00 2.200e+00 2.190e+00 2.180e+00 2.170e+00
 2.160e+00 2.150e+00 2.140e+00 2.130e+00 2.120e+00 2.110e+00 2.100e+00
 2.090e+00 2.080e+00 2.070e+00 2.060e+00 2.050e+00 2.040e+00 2.030e+00
 2.020e+00 2.010e+00 2.000e+00 1.990e+00 1.980e+00 1.970e+00 1.960e+00
 1.950e+00 1.940e+00 1.930e+00 1.920e+00 1.910e+00 1.900e+00 1.890e+00
 1.880e+00 1.870e+00 1.860e+00 1.850e+00 1.840e+00 1.830e+00 1.820e+00
 1.810e+00 1.800e+00 1.790e+00 1.780e+00 1.770e+00 1.760e+00 1.750e+00
 1.740e+00 1.730e+00 1.720e+00 1.710e+00 1.700e+00 1.690e+00 1.680e+00
 1.670e+00 1.660e+00 1.650e+00 1.640e+00 1.630e+00 1.620e+00 1.610e+00
 1.600e+00 1.590e+00 1.580e+00 1.570e+00 1.560e+00 1.550e+00 1.540e+00

### Export cleaned DataFrame to CSV.

In [142]:
#### Save the dataframe to a file named 'cleaned_df.csv'
df.to_csv('clean_video_games.csv', index=False)

### Data Preprocessing

In [143]:
df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20,old
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,<NA>,<NA>,medium,41,old
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E,medium,18,old
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E,medium,17,old
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,<NA>,<NA>,medium,30,old

In [144]:
df=df.drop(['sales_category','game_age','game_age_category'], axis=1) # no need for prediction
df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,<NA>,<NA>
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,<NA>,<NA>

#### Load cleaned dataset

In [145]:
cleaned_df= pd.read_csv('clean_video_games.csv')
cleaned_df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006.0,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20.0,old
1,Super Mario Bros.,NES,1985.0,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,medium,41.0,old
2,Mario Kart Wii,Wii,2008.0,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E,medium,18.0,old
3,Wii Sports Resort,Wii,2009.0,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E,medium,17.0,old
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,medium,30.0,old

In [146]:
x = cleaned_df.drop(columns=["global_sales"])
y = cleaned_df["global_sales"]

In [147]:
# Numerical Handling...
num_cols = x.select_dtypes(include = 'number').columns
num = num_cols.drop(['game_age'])
num

Index(['year_of_release', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales',
       'user_score'],
      dtype='object')

In [148]:
cat_cols = x.select_dtypes(include = 'object').columns 
cat = cat_cols.drop(['sales_category', 'game_age_category',''], errors='ignore') # no need for EDA only.
cat

Index(['name', 'platform', 'genre', 'publisher', 'developer', 'rating'], dtype='object')

In [149]:
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import RobustScaler 

rs=RobustScaler()
num_pipeline=Pipeline(steps=[('scaling',rs)])
num_pipeline

Pipeline(steps=[('scaling', RobustScaler())])

In [150]:
from category_encoders import BinaryEncoder 

be=BinaryEncoder()
be_pipeline=Pipeline(steps=[('be',be)])
be_pipeline

Pipeline(steps=[('be', BinaryEncoder())])

In [151]:
from category_encoders import BinaryEncoder 

be=BinaryEncoder()
be_pipeline=Pipeline(steps=[('be',be)])
be_pipeline

Pipeline(steps=[('be', BinaryEncoder())])

In [152]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from category_encoders import BinaryEncoder
from sklearn.compose import ColumnTransformer

# Define feature groups
num = ['year_of_release', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales','user_score']
cat_ohe = ['genre', 'rating']
cat_be = ['name', 'platform', 'publisher', 'developer']

# Build preprocessing pipelines
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", RobustScaler())
])

ohe_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("ohe", OneHotEncoder(drop="first", sparse_output=False))
])

be_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="constant", fill_value="Unknown")),
    ("be", BinaryEncoder())
])

preprocessing_pipe = ColumnTransformer([
    ("num", num_pipeline, num),
    ("ohe", ohe_pipeline,cat_ohe),
    ("be", be_pipeline, cat_be)
], remainder="drop")  # drop everything else

In [153]:
from sklearn.compose import ColumnTransformer

preprocessing_pipe=ColumnTransformer(transformers=[('num_cols',num_pipeline,num),
                                                   ('ohe',ohe_pipeline,cat_ohe),
                                                   ('be',be_pipeline,cat_be)],
                                     remainder='passthrough')

preprocessing_pipe

ColumnTransformer(remainder='passthrough',
                  transformers=[('num_cols',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', RobustScaler())]),
                                 ['year_of_release', 'na_sales', 'eu_sales',
                                  'jp_sales', 'other_sales', 'user_score']),
                                ('ohe',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False))]),
                                 ['genre', 'rating']),
                                ('be',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='Unknown',
                                                                strategy='constant')),
                                                 ('be', BinaryEncoder())]),
                                 ['name', 'platform', 'publisher',
                                  'developer'])])

### Machine Learning

In [154]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_validate, ShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from category_encoders import BinaryEncoder
from sklearn.compose import ColumnTransformer
import joblib

In [155]:
df = pd.read_csv("clean_video_games.csv")

# Ensure target is numeric and aligned
df["global_sales"] = pd.to_numeric(df["global_sales"], errors="coerce")
df = df.dropna(subset=["global_sales"])

X = df.drop(columns=["global_sales", "sales_category", "game_age", "game_age_category"], errors="ignore")
y = df["global_sales"].astype(float)

# Optional: filter out zero-sales rows to avoid NaN R²
df = df[df["global_sales"] > 0]
X = df.drop(columns=["global_sales"], errors="ignore")
y = df["global_sales"].astype(float)

In [156]:
# 3. Preprocessing Pipeline
# ============================================
num = ['year_of_release','na_sales','eu_sales','jp_sales','other_sales','user_score']
cat_ohe = ['genre','rating']
cat_be = ['name','platform','publisher','developer']

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", RobustScaler())
])


ohe_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("ohe", OneHotEncoder(drop="first", sparse_output=False, handle_unknown="ignore"))
])



be_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="constant", fill_value="Unknown")),
    ("be", BinaryEncoder())
])

preprocessing_pipe = ColumnTransformer([
    ("num", num_pipeline, num),
    ("ohe", ohe_pipeline, cat_ohe),
    ("be", be_pipeline, cat_be)
], remainder="drop")

In [157]:
model_zoo = [
    ("Linear Regression", LinearRegression()),
    ("KNN", KNeighborsRegressor(n_neighbors=10)),
    ("SVR", SVR(kernel="rbf")),
    ("Decision Tree", DecisionTreeRegressor(max_depth=7, random_state=42)),
    ("Random Forest", RandomForestRegressor(random_state=42))
]

In [158]:
cv_split = ShuffleSplit(n_splits=5, test_size=0.2, random_state=42)

results = []
best_model = None
best_score = -np.inf

for name, model in model_zoo:
    model_pipeline = Pipeline([
        ("Preprocessing", preprocessing_pipe),
        ("Model", model)
    ])
    
    cv = cross_validate(
        model_pipeline,
        X,
        y,
        cv=cv_split,
        scoring=["r2", "neg_mean_absolute_error", "neg_root_mean_squared_error"],
        return_train_score=True,
        n_jobs=-1,
        error_score="raise"
    )
    
    results.append({
        "Model": name,
        "Train R²": np.nanmean(cv["train_r2"]),
        "Test R²": np.nanmean(cv["test_r2"]),
        "Test MAE": -np.nanmean(cv["test_neg_mean_absolute_error"]),
        "Test RMSE": -np.nanmean(cv["test_neg_root_mean_squared_error"])
    })
    
    if np.nanmean(cv["test_r2"]) > best_score:
        best_score = np.nanmean(cv["test_r2"])
        best_model = model_pipeline

results_df = pd.DataFrame(results)
display(results_df)

               Model  Train R²   Test R²  Test MAE  Test RMSE
0  Linear Regression  0.999989  0.999987  0.003015   0.005258
1                KNN  0.890420  0.890119  0.086657   0.505716
2                SVR  0.648124  0.629925  0.083919   0.948041
3      Decision Tree  0.989807  0.802360  0.119280   0.611562
4      Random Forest  0.989532  0.943620  0.031060   0.349212

In [159]:
best_model.fit(X, y)
joblib.dump(best_model, "video_game_model.pkl")
print("Best model saved as video_game_model.pkl")

Best model saved as video_game_model.pkl

In [160]:
df.head(1)

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006.0,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20.0,old

### Exploratory Data Analysis (EDA)

#####  Sales Performance Insights ...

In [161]:
# Top selling game: identify the game with highet global_sales.
cleaned_df['global_sales'].max()
df.loc[cleaned_df['global_sales'].idxmax()]['name']

'Wii Sports'

In [162]:
top5games= cleaned_df['name'].value_counts().head(5)
top5games

name
Need for Speed: Most Wanted    12
Ratatouille                     9
Madden NFL 07                   9
FIFA 14                         9
LEGO Marvel Super Heroes        9
Name: count, dtype: int64

In [163]:
# Bar Chart - Top 10 Games with the Globa_sales. 
top10_games = cleaned_df[['name','global_sales','genre']].sort_values(by='global_sales', ascending=False).head(10)
top10_games

                        name  global_sales         genre
0                 Wii Sports         82.53        Sports
1          Super Mario Bros.         40.24      Platform
2             Mario Kart Wii         35.52        Racing
3          Wii Sports Resort         32.77        Sports
4   Pokemon Red/Pokemon Blue         31.37  Role-Playing
5                     Tetris         30.26        Puzzle
6      New Super Mario Bros.         29.80      Platform
7                   Wii Play         28.92          Misc
8  New Super Mario Bros. Wii         28.32      Platform
9                  Duck Hunt         28.31       Shooter

In [164]:

#my_colors = ["#4B0082", "#9B59B6", "#00A86B", "#2ECC71", "#2C2C2C", "#BDC3C7"]

fig_top10_games = px.bar(
    top10_games,
    x='name',
    y='global_sales',
    title='Top 10 Games by Global Sales (Bar Chart)',
    text='global_sales',
    color='genre'  ,
   # color_discrete_sequence=my_colors
)

fig_top10_games.update_layout(
    xaxis_title="Game Names",
    yaxis_title="Global Sales (Millions)"
)

fig_top10_games.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig_top10_games.show()

In [165]:
# Top 10 best‑selling games list (based in global sales) with age rating.
best_sellinggame_with_agerate = cleaned_df.sort_values(by='global_sales', ascending=False).head(10)

print(best_sellinggame_with_agerate[['name','rating']])

                        name rating
0                 Wii Sports      E
1          Super Mario Bros.    NaN
2             Mario Kart Wii      E
3          Wii Sports Resort      E
4   Pokemon Red/Pokemon Blue    NaN
5                     Tetris    NaN
6      New Super Mario Bros.      E
7                   Wii Play      E
8  New Super Mario Bros. Wii      E
9                  Duck Hunt    NaN

In [166]:
# Top 10 games with with age rating

fig_line_top10_games=px.line(best_sellinggame_with_agerate,x='name',y='global_sales',color='rating',title='Top 10 Games by Sales (Line)',text='global_sales')
fig_line_top10_games

In [167]:
# Highest Rated Games
# Sort by user_score and select top 10

# Top 10 best‑selling games list (based in global sales) with age rating.

top_rated = cleaned_df.sort_values(by='user_score', ascending=False).head(10)

print(top_rated[['name','user_score']])

                                        name  user_score
14414                     Breath of Fire III         9.7
8976         Boktai: The Sun is in Your Hand         9.6
3417   Harvest Moon: Friends of Mineral Town         9.6
10106                      Cory in the House         9.5
11120                Super Puzzle Fighter II         9.5
16631                          Karnaaj Rally         9.5
1645                Golden Sun: The Lost Age         9.5
16550            Wade Hixton's Counter Punch         9.5
5920                     MLB SlugFest Loaded         9.5
1068                         Resident Evil 4         9.4

In [168]:
fig = px.strip(
    top_rated,
    y='user_score',
    x='name',
    title='Top 10 Highest Rated Games (strip)',
    labels={'user_score':'User Score', 'name':'Game Name'},
    template='plotly_white',
    color='genre'
)

fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

In [169]:
# Top 10 best‑selling games list (based on global sales) with age rating
best_selling_with_age_rate = (
    cleaned_df.groupby(['name', 'rating'])['global_sales'].sum().reset_index().sort_values(by='global_sales', ascending=False)
    .head(10)
)
print(best_selling_with_age_rate[['name', 'rating', 'global_sales']])

                                name rating  global_sales
6000                      Wii Sports      E         82.53
2117              Grand Theft Auto V      M         56.57
3016                  Mario Kart Wii      E         35.52
6002               Wii Sports Resort      E         32.77
719   Call of Duty: Modern Warfare 3      M         30.59
712          Call of Duty: Black Ops      M         30.24
3689           New Super Mario Bros.      E         29.80
714       Call of Duty: Black Ops II      M         29.40
5998                        Wii Play      E         28.92
3692       New Super Mario Bros. Wii      E         28.32

In [170]:

fig_best_selling = px.bar(
    best_selling_with_age_rate,
    x="global_sales",
    y="name",
    color="rating",   # color bars by age rating
    orientation="h",  # horizontal bars for readability
    title="Top 10 Best-Selling Games with Age Rating (Bar Chart)",
    labels={"global_sales":"Global Sales (millions)", "name":"Game"},
    template="plotly_white"
)

fig_best_selling.show()

##### Average sales for each region (NA, EU, JP, Other):

In [171]:
# Sales by regions: Compare NA, EU, JP, and Other sales.
regions=['na_sales','eu_sales','jp_sales','other_sales']
region_sales = cleaned_df[['na_sales','eu_sales','jp_sales','other_sales']].mean()
region_sales = region_sales.rename({     # rename region sales columns for clearer labels and better visualization
    'na_sales': 'North America',
    'eu_sales': 'Europe',
    'jp_sales': 'Japan',
    'other_sales': 'Other Regions'
})
region_sales_df = region_sales.reset_index()
region_sales_df.columns = ['Region', 'Average Sales']

print(region_sales_df)

          Region  Average Sales
0  North America       0.263330
1         Europe       0.145025
2          Japan       0.077602
3  Other Regions       0.047332

In [172]:

corr_with_global = cleaned_df[regions].corrwith(cleaned_df['global_sales']).reset_index()
corr_with_global.columns = ['Region', 'Correlation with Global Sales']


corr_with_global['Region'] = corr_with_global['Region'].replace({
    'na_sales': 'North America',
    'eu_sales': 'Europe',
    'jp_sales': 'Japan',
    'other_sales': 'Other Regions'
})

fig = px.bar(corr_with_global, x='Region', y='Correlation with Global Sales',
             title="Correlation of Regional Sales with Global Sales (Bar Chart)",
             color='Correlation with Global Sales', color_continuous_scale=['#4B0082', '#00A86B', '#BDC3C7']) # purple → green → gray)
fig.show()

In [173]:
# Sales by game_name and regions.
pivot = pd.pivot_table(cleaned_df, values=['na_sales','eu_sales','jp_sales','other_sales','global_sales'],index='name',aggfunc='sum')

top10_sales_regions = pivot.sort_values(by='global_sales', ascending=False).head(10)
top10_sales_regions

,eu_sales,global_sales,jp_sales,na_sales,other_sales
name,,,,,
Wii Sports,28.96,82.53,3.77,41.36,8.45
Grand Theft Auto V,23.42,56.57,1.42,23.84,7.90
Super Mario Bros.,4.88,45.31,6.96,32.48,0.99
Tetris,2.95,35.84,6.03,26.17,0.69
Mario Kart Wii,12.76,35.52,3.79,15.68,3.29
Wii Sports Resort,10.93,32.77,3.28,15.61,2.95
Pokemon Red/Pokemon Blue,8.89,31.37,10.22,11.27,1.00
Call of Duty: Black Ops,9.35,30.82,0.59,17.57,3.31
Call of Duty: Modern Warfare 3,11.15,30.59,0.62,15.54,3.29
New Super Mario Bros.,9.14,29.80,6.50,11.28,2.88

##### Sales by Platform:

In [174]:
# Create a pivot table to summarize global sales by platform.
pivot = pd.pivot_table(cleaned_df,values='global_sales', index='platform',aggfunc='sum')
print(pivot)

          global_sales
platform
2600             97.08
3DO               0.10
3DS             259.09
DC               15.97
DS              807.10
GB              255.45
GBA             318.50
GC              199.36
GEN              30.78
GG                0.04
N64             218.88
NES             251.07
NG                1.44
PC              260.30
PCFX              0.03
PS              730.68
PS2            1255.64
PS3             939.43
PS4             314.23
PSP             294.30
PSV              54.12
SAT              33.59
SCD               1.87
SNES            200.05
TG16              0.16
WS                1.42
Wii             908.13
WiiU             82.16
X360            971.63
XB              258.26
XOne            159.44

In [175]:
# Count each rating per each platform
rating_counts = cleaned_df.groupby('platform')['rating'].value_counts().sort_values(ascending=False).head(10)
rating_counts_df = rating_counts.reset_index()

print(rating_counts_df)

  platform rating  count
0       DS      E    877
1      PS2      T    576
2      PS2      E    556
3      Wii      E    503
4      GBA      E    426
5     X360      T    343
6      PS3      T    336
7       PC      T    297
8     X360      M    294
9       XB      T    292

In [176]:
pivot = pd.pivot_table(
    cleaned_df,
   
    index='rating',
    columns='platform',   # ratings become columns
    aggfunc='size',     # count occurrences
    fill_value=0
)
pivot

platform,3DS,DC,DS,GBA,GC,PC,PS,PS2,PS3,PS4,PSP,PSV,Wii,WiiU,X360,XB,XOne
rating,,,,,,,,,,,,,,,,,
AO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
E,92,3,877,426,230,138,116,556,211,54,188,22,503,35,247,248,45
E10+,76,0,259,25,31,76,0,125,140,40,106,28,242,42,168,31,31
EC,0,0,2,0,1,2,0,1,0,0,0,0,2,0,0,0,0
K-A,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0
M,12,1,10,7,38,256,20,223,265,76,49,33,33,15,294,161,70
RP,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0
T,48,10,126,64,169,297,71,576,336,85,201,68,222,13,343,292,40

In [177]:

# Heatmap visualization
fig_heatmap = px.imshow(
    pivot,
    labels=dict(x="Platform", y="Rating", color="Avg Global Sales"),
    title="Average Global Sales by Genre and Platform (Heatmap)",
    color_continuous_scale=[ '#BDC3C7', '#00A86B', '#4B0082']  # gray → green → purple
)
fig_heatmap.show()

In [178]:
# Most Popular platform based on global sales (Wii , GBA , PC, etc...)
platform_sales_top10 = cleaned_df.groupby('platform')['global_sales'].count().sort_values(ascending=False).head(10).reset_index()
print(platform_sales_top10.head(10))

  platform  global_sales
0      PS2          2161
1       DS          2152
2      PS3          1331
3      Wii          1320
4     X360          1262
5      PSP          1209
6       PS          1197
7       PC           974
8       XB           824
9      GBA           822

In [179]:
fig = px.bar(
    platform_sales_top10,
    x='global_sales',
    y='platform',

    title='Top 10 Platforms by Global Sales (Bar Chart)',
    labels={'global_sales':'Global Sales (millions)', 'platform':'Platform'},
    template='plotly_white'
)

fig.show()

##### Sales by Genre:

In [180]:
# Most profitable game genres 
genre_sales = cleaned_df.groupby('genre')['global_sales'].sum().sort_values(ascending=False).head(10)
genre_sales_df = genre_sales.reset_index()
print(genre_sales_df)

          genre  global_sales
0        Action       1745.27
1        Sports       1332.00
2       Shooter       1052.94
3  Role-Playing        934.40
4      Platform        828.08
5          Misc        803.18
6        Racing        728.90
7      Fighting        447.48
8    Simulation        390.42
9        Puzzle        243.02

In [181]:
fig = px.scatter(
    genre_sales_df,
    x="genre",
    y="global_sales",
    size="global_sales",       # bubble size reflects sales
    color="genre",             # color by genre, it's optional
    title="Top 10 Most Profitable Game Genres (Scatter/Bubble)",
    labels={"global_sales":"Global Sales (millions)", "genre":"Genre"},
    template="plotly_white",
    trendline="ols" 
       
)

fig.show()

In [182]:
# Count frequency of each genre
genre_count = cleaned_df['genre'].value_counts(ascending=False).reset_index()
genre_count

           genre  count
0         Action   3370
1         Sports   2348
2           Misc   1750
3   Role-Playing   1500
4        Shooter   1323
5      Adventure   1303
6         Racing   1249
7       Platform    888
8     Simulation    874
9       Fighting    849
10      Strategy    683
11        Puzzle    580

In [183]:
top10_profitable_game = (
    cleaned_df.groupby(['genre','game_age_category'])['global_sales']
    .mean()
    .reset_index()
    .sort_values(by='global_sales', ascending=False)
    .head(10)
)

fig = px.bar(
    top10_profitable_game,
    x='game_age_category',
    y='global_sales',
    color='game_age_category',
    title="Top 10 Most Profitable Game Genres (Bar Chart)",
    labels={'global_sales':'Average Global Sales (millions)', 'genre':'Genre','game_age_category':'G_Age_Cat'},
    template='plotly_white',facet_col='genre'
)

fig.show()

##### Game names by user_score:

In [184]:
top10_gamesbyuser_score=df[['user_score','genre']].sort_values(by='user_score',ascending=False).head(10)
top10_gamesbyuser_score

       user_score         genre
14414         9.7  Role-Playing
8976          9.6  Role-Playing
3417          9.6    Simulation
10106         9.5        Action
11120         9.5        Puzzle
16631         9.5        Racing
1645          9.5  Role-Playing
16550         9.5        Sports
5920          9.5        Sports
1068          9.4        Action

In [185]:
# Relationship between user scores and global sales for the top 10 games, with bubbles sized by sales and colored by genre
top10_score_sales = (
    cleaned_df.sort_values(by="user_score", ascending=False)
    .head(10)
)

# Scatter bubble chart with trendline
fig_score_sales_top10 = px.scatter(
    top10_score_sales,
    x="user_score",
    y="global_sales",
    size="global_sales",   # bubble size reflects sales
    color="genre",
    hover_name="name",     # show game name on hover
    title="Top 10 Games by User Score vs Global Sales (with Trendline)",
    labels={"user_score":"User Score", "global_sales":"Global Sales (millions)"},
    template="plotly_white",
    trendline="ols"        # regression line
)

fig_score_sales_top10.show()

##### Sales by Publisher:

In [186]:
# Top performing publishers
publisher_sales= cleaned_df.groupby('publisher')['global_sales'].count().sort_values(ascending=False)
print(publisher_sales.head())

publisher
electronic arts                 1356
activision                       985
namco bandai games               939
ubisoft                          933
konami digital entertainment     834
Name: global_sales, dtype: int64

In [187]:
fig_publisher_sales = px.bar(
    publisher_sales.head(5).reset_index(),
    x='global_sales',
    y='publisher',
    orientation='h',
    title='Top 10 Publishers by Global Sales (Bar Chart)',
    labels={'global_sales':'Global Sales (millions)', 'publisher':'Publisher'},
    template='plotly_white'
)
fig_publisher_sales

##### Yearly Sales Trends:

In [188]:
# See how game sales change over time.

years_sales=cleaned_df.groupby('year_of_release')['global_sales'].sum().sort_values(ascending=False)
print(years_sales.head())

year_of_release
2008.0    671.79
2009.0    658.88
2007.0    605.37
2010.0    590.59
2006.0    518.22
Name: global_sales, dtype: float64

In [189]:
# Line Chart of Sales Over Year Time 

fig_line_sales_year = px.line(
    cleaned_df.groupby('year_of_release')['global_sales'].sum().reset_index(),
    x='year_of_release',
    y='global_sales',
    title='Global Sales Over Time (Line Chart)',
    labels={'year_of_release':'Year of Release', 'global_sales':'Global Sales (millions)'},
    template='plotly_white', 
   
)

fig_line_sales_year.show()

Number of Games Released per Year

In [190]:
games_per_year=cleaned_df.groupby('year_of_release')['name'].count().reset_index().sort_values(by='name', ascending=False).rename(columns={'name':'game_count'})
games_per_year

    year_of_release  game_count
28           2008.0        1427
29           2009.0        1426
30           2010.0        1255
27           2007.0        1197
31           2011.0        1136
26           2006.0        1006
25           2005.0         939
22           2002.0         829
23           2003.0         775
24           2004.0         762
32           2012.0         653
35           2015.0         606
34           2014.0         581
33           2013.0         544
36           2016.0         502
21           2001.0         482
18           1998.0         379
20           2000.0         350
19           1999.0         338
17           1997.0         289
16           1996.0         263
15           1995.0         219
14           1994.0         121
13           1993.0          60
1            1981.0          46
12           1992.0          43
11           1991.0          41
2            1982.0          36
6            1986.0          21
9            1989.0          17
3            1983.0          17
10           1990.0          16
7            1987.0          16
8            1988.0          15
4            1984.0          14
5            1985.0          14
0            1980.0           9
37           2017.0           3
38           2020.0           1

In [191]:
# Scatter plot - Number of Games Released per Year
fig = px.scatter(
    games_per_year,
    x='year_of_release',
    y='game_count',
    trendline='ols',   # add regression line
    title="Number of Games Released per Year with Trendline",
    labels={'year_of_release':'Year of Release', 'game_count':'Number of Games'},
    template='plotly_white'
)

fig.show()

In [192]:
# Genre vs Platform pivot table
genre_platform_sales = cleaned_df.pivot_table(
    index='genre',
    columns='platform',
    values='global_sales',
    aggfunc='mean'
)
genre_platform_sales

platform,2600,3DO,3DS,DC,DS,GB,GBA,GC,GEN,GG,...,SAT,SCD,SNES,TG16,WS,Wii,WiiU,X360,XB,XOne
genre,,,,,,,,,,,,,,,,,,,,,
Action,0.480984,NaN,0.310266,0.420000,0.331471,1.320000,0.333892,0.374653,0.913333,NaN,...,0.216667,NaN,0.840000,NaN,NaN,0.483165,0.297656,0.742074,0.317935,0.439412
Adventure,0.850000,0.06,0.128947,0.227273,0.192857,3.432000,0.386316,0.296500,0.095000,NaN,...,0.160000,NaN,0.375000,0.14,NaN,0.214819,0.053333,0.311250,0.117692,0.192143
Fighting,0.620000,NaN,0.755000,0.152500,0.197500,NaN,0.183043,0.438810,1.180000,NaN,...,0.274839,NaN,1.078000,NaN,NaN,0.556190,1.254000,0.574462,0.282292,0.344286
Misc,0.716000,NaN,0.203333,NaN,0.347110,1.668750,0.329545,0.464722,0.030000,NaN,...,0.080000,0.05,0.295294,NaN,NaN,0.772750,0.566818,0.720787,0.208261,0.391579
Platform,1.474444,NaN,1.161429,1.270000,0.834286,2.890000,0.551408,0.392603,2.207143,0.04,...,0.152000,1.50,2.525000,NaN,NaN,1.533103,1.267059,0.452800,0.197143,0.188000
Puzzle,1.334545,0.02,0.277500,NaN,0.350508,3.164667,0.315122,0.361538,NaN,NaN,...,0.200000,NaN,0.490769,NaN,NaN,0.279455,0.330000,0.121429,0.060000,NaN
Racing,0.485000,NaN,1.358182,0.441667,0.568657,2.275000,0.293750,0.347460,0.260000,NaN,...,0.300000,0.07,1.498889,NaN,NaN,0.647849,2.623333,0.625000,0.256016,0.489500
Role-Playing,NaN,NaN,0.957841,0.170000,0.622200,4.201905,0.879589,0.487037,0.090000,NaN,...,0.221176,0.06,0.728600,NaN,0.305,0.391429,0.412857,0.950800,0.587391,0.753571
Shooter,1.103333,NaN,0.184286,0.110000,0.188571,1.200000,0.090000,0.283958,0.130000,NaN,...,0.180909,NaN,0.607000,0.02,NaN,0.433077,0.597000,1.364433,0.481439,1.589211
Simulation,0.450000,0.02,0.884839,0.520000,0.458768,0.710000,0.328333,0.715833,NaN,NaN,...,0.161429,NaN,0.625556,NaN,NaN,0.414138,0.200000,0.354500,0.296250,0.172500
Sports,0.285833,NaN,0.238077,0.366000,0.212230,1.005556,0.186477,0.231727,1.066667,NaN,...,0.174375,NaN,0.364694,NaN,NaN,1.110038,0.398750,0.638018,0.319235,0.704474
Strategy,NaN,NaN,0.140000,NaN,0.188228,1.150000,0.413889,0.392727,0.190000,NaN,...,0.180000,0.14,0.332000,NaN,0.100,0.201200,0.410000,0.358214,0.132381,0.140000

In [193]:
genre_platform_sales_reset = genre_platform_sales.reset_index().melt(  #eshapes a DataFrame from wide format (platforms as separate columns) into long format (platforms as rows).
    id_vars='genre',
    var_name='platform',
    value_name='avg_sales'
)

fig_bar = px.bar(
    genre_platform_sales_reset,
    x='genre',
    y='avg_sales',
    color='platform',
    title="Average Global Sales by Genre and Platform (Stacked Bar)",
    labels={'avg_sales':'Avg Global Sales', 'genre':'Genre'},
    template='plotly_white'
)
fig_bar.show()

##### Genre or platform preference Analysis:

In [194]:

fig_heatmap = px.imshow(
    genre_platform_sales,
    labels=dict(x="Platform", y="Genre", color="Avg Global Sales"),
    title="Average Global Sales by Genre and Platform (Heatmap)",
    color_continuous_scale=my_colors 
)
fig_heatmap.show()

In [195]:
%%writefile video_game_app.py

import streamlit as st
import pandas as pd
import plotly.express as px

# re-style the multiselect tags to look more polished, with gradient colors.
st.markdown("""
<style>

/* Target multiselect selected values (the pills) */
span[data-baseweb="tag"] {
    background: linear-gradient(90deg, #c084fc, #ffb3b3, #a7f3d0) !important; 
    /* light purple → soft red → light green */
    color: #1f2937 !important;           /* dark text for readability */
    border: none !important;
    box-shadow: 0 0 6px rgba(255, 179, 179, 0.3); /* soft glow effect */
}

/* Hover effect */
span[data-baseweb="tag"]:hover {
    background: linear-gradient(90deg, #b794f4, #ffc7c7, #86efac) !important;
}

/* Remove default red “x” color */
span[data-baseweb="tag"] svg {
    color: #1f2937 !important;
}

</style>
""", unsafe_allow_html=True)



# Display a title with HTML/CSS styling
st.markdown(
    """
<h1 style="
    text-align: center;
    font-size: 95px;
    background: linear-gradient(90deg, #7b2ff7, #ff4d4d, #00c9a7);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-weight: bold;
">
    Video Game Sales Dashboard 
</h1>
    """,
    unsafe_allow_html=True
)

# Display header image 

from PIL import Image

img = Image.open("image.png")
img = img.resize((4000, 1000))

col1, col2, col3 = st.columns([0.05, 9, 0.05])
with col2:
    st.image(img, use_container_width=True)



# --------------------------------------------------------------------------------------------------
# Page Config
st.set_page_config(
    page_title="Video Game Sales Dashboard",
    layout="wide"
)

# --------------------------
# Load Data
@st.cache_data
def load_data():
    df = pd.read_csv("clean_video_games.csv")
    return df

df = load_data()



# --------------------------------------------------------------------------------------------------
 

# Sidebar
# Page Navigation
st.sidebar.markdown(
    "<h2 style='font-size:28px'>Navigation</h2>", unsafe_allow_html=True
)

page = st.sidebar.radio(
    " ",# to keep the radio label empty
    [
        "Overview",
        "Analysis",
        "Predictions"

    ]
)


# Add a separator line
st.sidebar.markdown("---")
# --------------------------------------------------------------------------------------------------
# Sidebar Filters

st.sidebar.markdown(
 "<h3 style='font-size:24px'>Data Filters</h3>", unsafe_allow_html=True )

#genre_filter = st.sidebar.multiselect(
   # "Select Genre", options=df["genre"].unique(), default=df["genre"].unique())


with st.sidebar.expander("Select Genre", expanded=False):
    genre_filter = st.multiselect(
        label="",
        options=df["genre"].unique(),
        default=df["genre"].unique()
    )

age_rating_map = { #  # Mapping shorthand ratings to full names 
    "E": "Everyone",
    "E10+": "Everyone 10+",
    "T": "Teen",
    "M": "Mature 17+",
    "AO": "Adults Only 18+",
    "K-A": "Kids to Adults"
}

#rating_filter = st.sidebar.multiselect(
 #   "Select Age Rating",   options=list(age_rating_map.keys()),default=list(age_rating_map.keys()), 
 #   format_func=lambda x: f"{x} — {age_rating_map[x]}")

with st.sidebar.expander("Select Age Rating", expanded=False):
    rating_filter = st.multiselect(
        label="",
        options=list(age_rating_map.keys()),
        default=list(age_rating_map.keys()),
        format_func=lambda x: f"{x} — {age_rating_map[x]}"
    )



#platform_filter = st.sidebar.multiselect(
   # "Select Platform", options=df["platform"].unique(), default=df["platform"].unique())

with st.sidebar.expander("Select Platform", expanded=False):
    platform_filter = st.multiselect(
        label="",
        options=df["platform"].unique(),
        default=df["platform"].unique()
    )


#user_score_filter = st.sidebar.slider(
 #   "Set User Score Range",
  #  float(df["user_score"].min()),
   # float(df["user_score"].max()),
    #(float(df["user_score"].min()), float(df["user_score"].max())),
#)
with st.sidebar.expander("Set User Score Range", expanded=False):
    user_score_filter = st.slider(
        label="",
        min_value=float(df["user_score"].min()),
        max_value=float(df["user_score"].max()),
        value=(
            float(df["user_score"].min()),
            float(df["user_score"].max())
        ),
        step=0.1
    )


    
#year_filter = st.sidebar.slider(
 #   "Set Year of Release Range",
  #  int(df["year_of_release"].min()),
   # int(df["year_of_release"].max()),
    #(int(df["year_of_release"].min()), int(df["year_of_release"].max())),
#)


with st.sidebar.expander("Set Year of Release Range", expanded=False):
    year_filter = st.slider(
        label="",
        min_value=int(df["year_of_release"].min()),
        max_value=int(df["year_of_release"].max()),
        value=(
            int(df["year_of_release"].min()),
            int(df["year_of_release"].max())
        )
    )


# --------------------------------------------------------------------------------------------------
# Apply Filters
filtered_df = df[
    (df["genre"].isin(genre_filter)) &
    (df["rating"].isin(rating_filter)) &
    (df["platform"].isin(platform_filter)) &
   
    (df["user_score"].between(user_score_filter[0], user_score_filter[1])) &
    (df["year_of_release"].between(year_filter[0], year_filter[1]))
]

# --------------------------------------------------------------------------------------------------

# MAIN PAGE
if page == "Overview":

    st.title("Dashboard Overview")

    st.markdown("""
    The Video Game Sales **Dashboard** is an interactive tool for analyzing global video game sales and identifying market trends. Users can filter by Genre, Age Rating, Platform, User Score, and Release Year to explore performance across the gaming industry.
    """)

 


    tab1, tab2, tab3= st.tabs([
        "Dataset Overview",
        "Key Performance Indicators",
        "Data Summary"
    ])
    with tab1:
        st.subheader("Dataset Overview")

        st.markdown("""
        The **Dataset** provides comprehensive data on video game sales, and user insights globally, including details such as the game's name, platform, year of release, genre, publisher, sales in different regions, developer, and age rating.
    """)

    # Initialize number of rows ...................
        if "rows" not in st.session_state:
            st.session_state.rows = 5

    # Display dataframe
        st.dataframe(filtered_df.head(st.session_state.rows))

    # Show more button .......................
        if st.button("🔽 Show More Rows"):
            st.session_state.rows += 10


    
    with tab2:
        st.subheader("Key Performance Indicators (KPIs)")

        # KPI calculations
        Total_Games = filtered_df.shape[0]
        Total_Global_Sales = filtered_df["global_sales"].sum()
        Global_Sales_Rate = Total_Global_Sales / Total_Games if Total_Games else 0
        Top_Selling_Game = filtered_df.groupby('name')['global_sales'].sum().idxmax() if Total_Games else "N/A"
        Avg_User_Score = filtered_df["user_score"].mean()
        Most_Popular_Platform = filtered_df['platform'].mode()[0] if Total_Games else "N/A"
        Top_Genre = filtered_df['genre'].mode()[0] if Total_Games else "N/A"
        # Most_Age_Rating= filtered_df['rating'].mode()[0] if Total_Games else "N/A"
        Most_Age_Rating = (age_rating_map.get(filtered_df['rating'].mode()[0], "N/A") if Total_Games else "N/A"
    )

        # Display KPIs in columns with two rows
        col1, col2, col3, col4 = st.columns(4)
        col5, col6, col7, col8 = st.columns(4)

    # Numeric KPIs
        col1.metric("🕹️ Total Games", Total_Games)
        col2.metric("💰 Total Global Sales (Millions)", f"{Total_Global_Sales:.2f}")
        col3.metric("🔢 Global Sales Rate", f"{Global_Sales_Rate:.2%}")
        col4.metric("🎯 Average User Score", f"{Avg_User_Score:.2f}")
        
    # Categorical KPIs
        col5.metric("🏆 Top Selling Game", Top_Selling_Game)
        col6.metric("🌟 Most Popular Genre", Top_Genre)
        col7.metric("🎮 Most Popular Platform", Most_Popular_Platform)
        col8.metric("👶 Most Age Rating", Most_Age_Rating)
        
    

    with tab3:   # Make sure tab3 = "🧾 Data Summary"
        
    
        st.subheader("Column Descriptions")
       

        column_data = {
            "Column": [
                "Index", "Name", "Platform", "Year_of_Release", "Genre", "Publisher",
                "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales", "User_Score",
                "Developer", "Rating", "Sales_Category","Game_Age","Game_Age_Category"
            ],
            "Description": [
                "Unique identifier for each video game record.",
                "The name of the video game.",
                "The platform on which the game is available (PC, PS4, Xbox, etc.).",
                "The year in which the game was released.",
                "The genre of the game (Action, Sports, etc.).",
                "The company that published the game.",
                "Sales in North America (millions).",
                "Sales in Europe (millions).",
                "Sales in Japan (millions).",
                "Sales in other regions (millions).",
                "Total global sales (millions).",
                "Average score given by users.",
                "The company that developed the game.",
                "ESRB rating (E, T, M, etc.).",
                "Sales performance category (best_seller, medium, low)",
                "Number of years since the game’s release (current year − release year)",
                "Binned game age derived from release year (New, Recent, Old)"
            ]
        }

        df_desc = pd.DataFrame(column_data)
        st.dataframe(df_desc, use_container_width=True)

        
# --------------------------------------------------------------------------------------------------
# ANALYSIS PAGE
elif page == "Analysis":

    st.title("Exploratory Data Analysis (EDA)")

    tab1, tab2, tab3 , tab4, tab5= st.tabs([
        "Univariate Analysis",
        "Bivariate Analysis",
        "Multivariate Analysis", 
        "Insights Q&A",
        "Recommendations"
    ])

    # --------------------------
    # Univariate Analysis
    with tab1:
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Total Global Sales by Genre")

            sales_genre = (
                filtered_df.groupby('genre')['global_sales']
                .sum()
                .reset_index()
                .sort_values(by='global_sales', ascending=False).head(10)
            )

            fig_genre_pie = px.pie(
                sales_genre,
                names='genre',
                values='global_sales',
                labels={'genre':'Genre','global_sales':'Total Global Sales (Millions)'},
                color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ])   

            fig_genre_pie.update_traces(
                    textinfo='value',   # show both genre and global sales
                    textposition='inside'
)
            st.plotly_chart(fig_genre_pie, use_container_width=True)
            st.caption(""" 👉 Action and Sports genres dominate global sales, indicating strong market preference.""")
        
        with col2:
            st.subheader("Games Released by Year")

            games_per_year = (
                filtered_df.groupby('year_of_release')['name']
                .count()
                .reset_index()
                .sort_values(by='name', ascending=False).head(10)
                .rename(columns={'name':'game_count'})
            )

            fig_year_pie = px.pie(
                games_per_year,
                names='year_of_release',
                values='game_count',
                labels={
                    'year_of_release': 'Year of Release',
                    'game_count': 'Number of Games'
                },color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ]
            )

            # Show Year inside pie instead of %
            fig_year_pie.update_traces(
                textinfo='value',
                textposition='inside'
            )

            st.plotly_chart(fig_year_pie, use_container_width=True)
            st.caption(" 👉 Game releases vary over time, with noticeable growth periods that reflect the expansion of the gaming industry.""")
        

        
        st.divider()

        st.subheader("Top 10 Publishers by Global Sales")

        # Aggregate global sales by publisher
        sales_publisher = (
            filtered_df.groupby('publisher')['global_sales']
            .sum()
            .reset_index()
            .sort_values(by='global_sales', ascending=False)
        )

        # Select Top 10 publishers
        top_publishers = sales_publisher.head(10)

        # Bar chart for Top 10 publishers
        fig_publisher_bar = px.bar(
            top_publishers,
            x='publisher',
            y='global_sales',
            color='publisher',labels={'publisher':'Publisher','global_sales':'Global Sales (Millions)'},
            color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ]
        )

        st.plotly_chart(fig_publisher_bar, use_container_width=True)
        st.caption(" 👉 Top 10 Publishers dominate the global sales, highlighting a highly concentrated and competitive market.")
        
        st.divider()

        
        st.subheader("Distribution of User Scores")

        fig_hist = px.histogram(
            filtered_df,
            x="user_score",
            nbins=20,
            marginal="box",  # adds boxplot on top 
            opacity=0.85,
            color_discrete_sequence = ["#2d004d", "#5a189a", "#c48df5", "#e0c3fc", "#ffa8a8", "#d1f2eb", "#b7f5d3", "#38b000", "#004b23"], 
        )

        fig_hist.update_layout(
            xaxis_title="User Score",
            yaxis_title="Number of Games",
            bargap=0.1
        )

        st.plotly_chart(fig_hist, use_container_width=True)
        st.caption(" 👉 Most games receive moderate to high user scores, reflecting generally positive user feedback." )
    # --------------------------------------------------------------------------------------------------
    # Bivariate Analysis
    with tab2:


        st.subheader("Number of Games Released per Year with Trendline")

        # Scatter plot - Number of Games Released per Year
        fig_gyear = px.scatter(
            games_per_year,
            x='year_of_release',
            y='game_count',
            trendline='ols',   # add regression line,
            color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ],
            labels={'year_of_release':'Year of Release', 'game_count':'Number of Games'},
            template='plotly_white'
        )


        st.plotly_chart(fig_gyear, use_container_width=True)
        st.caption("👉 Game production has grown over the years, despite some fluctuations." )
 


        st.divider()

        st.subheader("Global Sales Distribution by User Score (Top 10 Genres)")

    # Get Top 10 genres by total global sales
        top_genres = (
        filtered_df.groupby("genre")["global_sales"]
        .sum()
        .sort_values(ascending=False)
        .head(10)
        .index
    )

        filtered_top10 = filtered_df[filtered_df["genre"].isin(top_genres)]

        fig_violin = px.violin(
        filtered_top10,
        x="genre",              # categorical axis (e.g., genre)
        y="global_sales",       # numeric axis
        color="genre",          # color by genre
        box=True,               # add embedded boxplot
        points="all",           # show all individual points
        hover_data=["name", "user_score"],  # extra info on hover
        labels={
            "genre": "Genre",
            "global_sales": "Global Sales (Millions)"
        },
        color_discrete_sequence=[
            "#2d004d", "#5a189a", "#c77dff",
            "#ff4d4d", "#ff8787",
            "#80ed99", "#38b000",
            "#b7f5d3", "#004b23", "#6a0dad"
        ]
    )

        st.plotly_chart(fig_violin, use_container_width=True)

        st.caption("👉 Sales performance varies across genres, with some genres achieving higher global sales." )


        st.divider()

        st.subheader("Global Sales Trends of Top 3 Platforms")

        # Aggregate global sales by platform and year
        sales_platform_year = (
            filtered_df.groupby(['year_of_release', 'platform'])['global_sales']
            .sum()
            .reset_index()
        )

        # Compute total sales per platform (to find top 3 overall)
        top_platforms = (
            sales_platform_year.groupby('platform')['global_sales']
            .sum()
            .reset_index()
            .sort_values(by='global_sales', ascending=False)
            .head(3)['platform']
        )

        # Filter only top 3 platforms
        sales_top_platforms = sales_platform_year[
            sales_platform_year['platform'].isin(top_platforms)
        ]

        # Line chart: sales trend over years
        fig_platform_line = px.line(
            sales_top_platforms,
            x='year_of_release',
            y='global_sales',
            color='platform',
            labels={'year_of_release':'Year of Release','platform':'Platform','global_sales':'Total Global Sales (Millions)'},
            color_discrete_sequence = ["#2d004d", "#38b000",  "#ff4d4d" ],markers=True,
        )

        st.plotly_chart(fig_platform_line, use_container_width=True)

        st.caption("👉 The top 3 platforms show clear sales peaks across different years, reflecting shifts in console popularity and changes in user demand over time.")
          
    # Multivariate Analysis
       
     
    
    with tab3:
        st.subheader("Global Sales over Years by Top Genres")


        # Get top 3 games by global sales
        top10_games = (
        filtered_df.groupby('genre')['global_sales'].sum().sort_values(ascending=False).head(3).index)

        # Filter dataset
        filtered_df2 = filtered_df[filtered_df['genre'].isin(top10_games)]


        sales_year_genre = filtered_df2.groupby(['year_of_release', 'genre'])['global_sales'].sum().reset_index()
        fig_multi = px.line(sales_year_genre, x='year_of_release', y='global_sales',
                            color='genre', markers=True,  color_discrete_sequence=[

        "#4c1d95",  # purple
        "#b91c1c",  # red
        "#065f46",  # green
        "#6d28d9",  # violet
        "#6ee7b7",  # light green
        "#8b5cf6",  # light purple
        "#10b981",  # green
        "#ef4444"   # red
    ],
                            labels={'year_of_release':'Year of Release', 'genre':'Genre','global_sales':'Global Sales (Millions)' },)
        st.plotly_chart(fig_multi, use_container_width=True)
        st.caption("👉 Global sales by genre show steady year‑over‑year growth followed by a sharp decline.")
      

        st.divider()

        st.subheader("Global Sales by Genre and Age Rating")

        # Mapping shorthand ratings to full names
        rating_map = {
            "E": "Everyone",
            "E10+": "Everyone 10+",
            "M": "Mature",
            "EC": "Early Childhood",
            "RP": "Rating Pending",
            "K-A": "Kids to Adults",
            "AO": "Adults Only",
            "T": "Teen"
        }

        # Aggregate sales by genre and rating
        sales_platform_rating = (
            filtered_df.groupby(['genre', 'rating'])['global_sales']
            .sum()
            .reset_index()
        )

        # Map abbreviations to full names
        sales_platform_rating['rating'] = sales_platform_rating['rating'].map(rating_map)

        # Define rating order
        rating_order = [
            "Everyone",
            "Everyone 10+",
            "Mature",
            "Early Childhood",
            "Rating Pending",
            "Kids to Adults",
            "Adults Only",
            "Teen"
        ]

        # Assign categorical order
        sales_platform_rating['rating'] = pd.Categorical(
            sales_platform_rating['rating'],
            categories=rating_order,
            ordered=True
        )

        # Get Top 5 genres
        top_genres = (
            sales_platform_rating.groupby('genre')['global_sales']
            .sum()
            .sort_values(ascending=False)
            .head(5)
            .index
        )

        # Filter Top 3
        sales_platform_rating = sales_platform_rating[
            sales_platform_rating['genre'].isin(top_genres)
        ]

        # Plot
        fig_platform_rating = px.bar(
            sales_platform_rating,
            x='genre',
            y='global_sales',
            color='rating',
            barmode='group',
            color_discrete_sequence=[

        "#4c1d95",  # purple
        "#b91c1c",  # red
        "#065f46",  # green
        "#6d28d9",  # violet
        "#6ee7b7",  # light green
        "#8b5cf6",  # light purple
        "#10b981",  # green
        "#ef4444"   # red
    ],
            labels={
                'rating': 'Age Rating',
                'genre': 'Genre',
                'global_sales': 'Global Sales (Millions)'
            }
        )

        st.plotly_chart(fig_platform_rating, use_container_width=True)

        st.caption(
            "👉 Top 5 genres dominate global sales, with 'Everyone' and 'Teen' ratings contributing the most across genres."
        )


        st.divider()
    

        st.subheader("Global Sales Heatmap by Genre, Region, and Age Rating")
        
   

        # Melt the regional sales into long format
        sales_region = filtered_df.melt(
            id_vars=['genre', 'rating'],
            value_vars=['na_sales', 'eu_sales', 'jp_sales', 'other_sales'],
            var_name='region',
            value_name='sales'
        )

        # Rename region values for display
        region_map = {
            'na_sales': 'North America',
            'eu_sales': 'Europe',
            'jp_sales': 'Japan',
            'other_sales': 'Other Regions'
        }

        sales_region['region'] = sales_region['region'].map(region_map)

        # Aggregate sales by genre, rating, and region
        sales_region_grouped = (
            sales_region.groupby(['genre', 'rating', 'region'])['sales']
            .sum()
            .reset_index()
        )

        # Get Top 5 genres by total sales
        top_genres = (
            sales_region_grouped.groupby('genre')['sales']
            .sum()
            .sort_values(ascending=False)
            .head(5)
            .index
        )

        # Filter only Top 5 genres
        sales_region_grouped = sales_region_grouped[
            sales_region_grouped['genre'].isin(top_genres)
        ]

        # Heatmap
        fig_facet = px.density_heatmap(
            sales_region_grouped,
            x='genre',
            y='rating',
            z='sales',
            facet_col='region',
            color_continuous_scale=[
                "#2e1065",
                "#4c1d95",
                "#6d28d9",
                "#9333ea",
                "#c026d3",
                "#db2777",
                "#e11d48"
                    ],
            labels={
                'rating': 'Age Rating',
                'genre': 'Genre',
                'region': 'Region',
                'sales': 'Sales'
            }
        )

        st.plotly_chart(fig_facet, use_container_width=True)

        st.caption(
            "👉 Top genres show different regional preferences, with Action and Sports dominating globally and Role-Playing stronger in Japan."
        )
    

    with tab4:
        st.subheader("Insights Q&A")

        question = st.selectbox(
            "Select a business question:",
            [
                "Which Top Video Game per platform?",
                "Which regions generate the most sales?",
                "Genre distribution per region?",
                "What percentage of 'UNKNOWN' publisher from total games?"
            ]
        )

        if question == "Which Top Video Game per platform?":
            # Top-selling game per region (using global_sales)
            region_sales = (
                filtered_df.groupby(["platform", "name"])["global_sales"]
                .sum()
                .reset_index()
                .sort_values(by="global_sales", ascending=False)
            )
            top1_per_platform = region_sales.groupby("platform").head(1)

            fig_top1_platform = px.bar(
                top1_per_platform,
                x="platform",
                y="global_sales",
                color="name",
                text="name",
                title="Top Game per Platform"
            )
            st.plotly_chart(fig_top1_platform)
            st.markdown("➡️ This chart shows the single most globally successful game on each platform.")

        elif question == "Which regions generate the most sales?":
            region_totals = {
                "NA": filtered_df["na_sales"].sum(),
                "EU": filtered_df["eu_sales"].sum(),
                "JP": filtered_df["jp_sales"].sum(),
                "Other": filtered_df["other_sales"].sum()
            }
            region_df = pd.DataFrame(list(region_totals.items()), columns=["Region", "Sales"])

            fig_region_sales = px.bar(
                region_df,
                x="Region",
                y="Sales",
                title="Total Sales by Region",
                text_auto=True,
                color="Sales"
            )
            st.plotly_chart(fig_region_sales)
            st.markdown("➡️ Regions with the highest sales represent strong demand centers.")

        elif question == "Genre distribution per region?":
            genre_region = (
                filtered_df.groupby(["genre", "platform"])["global_sales"]
                .sum()
                .reset_index()
            )
            fig_genre_region = px.bar(
                genre_region,
                x="platform",
                y="global_sales",
                color="genre",
                barmode="group",
                title="Genre Distribution per Platform",
                text_auto=True
            )
            st.plotly_chart(fig_genre_region)
            st.markdown("➡️ Genre-based demand varies across platforms — tailor strategies accordingly.")

        elif question == "What percentage of 'UNKNOWN' publisher from total games?":
            total_games = len(filtered_df)
            unknown_publishers = len(filtered_df[filtered_df["publisher"].str.lower() == "unknown"])
            percentage_unknown = (unknown_publishers / total_games * 100) if total_games > 0 else 0
            st.metric("Percentage of 'UNKNOWN' Publisher", f"{percentage_unknown:.2f}%")
            st.markdown("➡️ A significant share of records have 'UNKNOWN' publishers.")



        
    with tab5:

# =================================================


            st.title("Business Recommendations")
            st.markdown("""
        
        ### Strategic actions to enhance market performance and maximize global video game sales.

        - Focus development on Action & Sports games (since they are the most popular).  
        - Focus on family-friendly ratings to reach more players.. 
        - Improve game quality to raise user scores
        - Target high-performing years trends (release your games during the busiest times of the year when people are buying the most).
        - Emulate PS2‑era success with variety + budget‑friendly pricing.

        """)

elif page == "Predictions":

    st.title("Video Game Global Sales Prediction")

    st.markdown("""
    The Video Game Sales **Dashboard** is an interactive tool for analyzing global video game sales and identifying market trends. Users can filter by Genre, Age Rating, Platform, User Score, and Release Year to explore performance across the gaming industry.
    """)

# Footer

st.markdown("""     ---
<div style='text-align: center; font-size: 18px; color: #999;'>

© 2026 Elaf Bahaa Aldein • All Rights Reserved • 
<a href="mailto:elafbhaa0@gmail.com" style="color:#999; text-decoration:none;">Email</a> • 
<a href="https://github.com/elafbhaa" target="_blank" style="color:#6e6e6e; text-decoration:none;">GitHub</a> • 
<a href="https://www.linkedin.com/in/elaf-bahaa-aldein-50b7552aa/" target="_blank" style="color:#0A66C2; text-decoration:none;">LinkedIn</a> •
<a href="https://wa.me/201557549995?text=Hi%20Elaf,%20I%20visited%20your%20Video%20Game%20Dashboard" 
target="_blank" style="color:#25D366; text-decoration:none;">WhatsApp
</a>
</div>
""", unsafe_allow_html=True)

Overwriting video_game_app.py

### Exploratory Data Analysis (EDA)

#####  Sales Performance Insights ...

In [196]:
# Top selling game: identify the game with highet global_sales.
cleaned_df['global_sales'].max()
df.loc[cleaned_df['global_sales'].idxmax()]['name']

'Wii Sports'

In [197]:
top5games= cleaned_df['name'].value_counts().head(5)
top5games

name
Need for Speed: Most Wanted    12
Ratatouille                     9
Madden NFL 07                   9
FIFA 14                         9
LEGO Marvel Super Heroes        9
Name: count, dtype: int64

In [198]:
# Bar Chart - Top 10 Games with the Globa_sales. 
top10_games = cleaned_df[['name','global_sales','genre']].sort_values(by='global_sales', ascending=False).head(10)
top10_games

                        name  global_sales         genre
0                 Wii Sports         82.53        Sports
1          Super Mario Bros.         40.24      Platform
2             Mario Kart Wii         35.52        Racing
3          Wii Sports Resort         32.77        Sports
4   Pokemon Red/Pokemon Blue         31.37  Role-Playing
5                     Tetris         30.26        Puzzle
6      New Super Mario Bros.         29.80      Platform
7                   Wii Play         28.92          Misc
8  New Super Mario Bros. Wii         28.32      Platform
9                  Duck Hunt         28.31       Shooter

In [199]:

#my_colors = ["#4B0082", "#9B59B6", "#00A86B", "#2ECC71", "#2C2C2C", "#BDC3C7"]

fig_top10_games = px.bar(
    top10_games,
    x='name',
    y='global_sales',
    title='Top 10 Games by Global Sales (Bar Chart)',
    text='global_sales',
    color='genre'  ,
   # color_discrete_sequence=my_colors
)

fig_top10_games.update_layout(
    xaxis_title="Game Names",
    yaxis_title="Global Sales (Millions)"
)

fig_top10_games.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig_top10_games.show()

In [200]:
# Top 10 best‑selling games list (based in global sales) with age rating.
best_sellinggame_with_agerate = cleaned_df.sort_values(by='global_sales', ascending=False).head(10)

print(best_sellinggame_with_agerate[['name','rating']])

                        name rating
0                 Wii Sports      E
1          Super Mario Bros.    NaN
2             Mario Kart Wii      E
3          Wii Sports Resort      E
4   Pokemon Red/Pokemon Blue    NaN
5                     Tetris    NaN
6      New Super Mario Bros.      E
7                   Wii Play      E
8  New Super Mario Bros. Wii      E
9                  Duck Hunt    NaN

In [201]:
# Top 10 games with with age rating

fig_line_top10_games=px.line(best_sellinggame_with_agerate,x='name',y='global_sales',color='rating',title='Top 10 Games by Sales (Line)',text='global_sales')
fig_line_top10_games

In [202]:
# Highest Rated Games
# Sort by user_score and select top 10

# Top 10 best‑selling games list (based in global sales) with age rating.

top_rated = cleaned_df.sort_values(by='user_score', ascending=False).head(10)

print(top_rated[['name','user_score']])

                                        name  user_score
14414                     Breath of Fire III         9.7
8976         Boktai: The Sun is in Your Hand         9.6
3417   Harvest Moon: Friends of Mineral Town         9.6
10106                      Cory in the House         9.5
11120                Super Puzzle Fighter II         9.5
16631                          Karnaaj Rally         9.5
1645                Golden Sun: The Lost Age         9.5
16550            Wade Hixton's Counter Punch         9.5
5920                     MLB SlugFest Loaded         9.5
1068                         Resident Evil 4         9.4

In [203]:
fig = px.strip(
    top_rated,
    y='user_score',
    x='name',
    title='Top 10 Highest Rated Games (strip)',
    labels={'user_score':'User Score', 'name':'Game Name'},
    template='plotly_white',
    color='genre'
)

fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

In [204]:
# Top 10 best‑selling games list (based on global sales) with age rating
best_selling_with_age_rate = (
    cleaned_df.groupby(['name', 'rating'])['global_sales'].sum().reset_index().sort_values(by='global_sales', ascending=False)
    .head(10)
)
print(best_selling_with_age_rate[['name', 'rating', 'global_sales']])

                                name rating  global_sales
6000                      Wii Sports      E         82.53
2117              Grand Theft Auto V      M         56.57
3016                  Mario Kart Wii      E         35.52
6002               Wii Sports Resort      E         32.77
719   Call of Duty: Modern Warfare 3      M         30.59
712          Call of Duty: Black Ops      M         30.24
3689           New Super Mario Bros.      E         29.80
714       Call of Duty: Black Ops II      M         29.40
5998                        Wii Play      E         28.92
3692       New Super Mario Bros. Wii      E         28.32

In [205]:

fig_best_selling = px.bar(
    best_selling_with_age_rate,
    x="global_sales",
    y="name",
    color="rating",   # color bars by age rating
    orientation="h",  # horizontal bars for readability
    title="Top 10 Best-Selling Games with Age Rating (Bar Chart)",
    labels={"global_sales":"Global Sales (millions)", "name":"Game"},
    template="plotly_white"
)

fig_best_selling.show()

##### Average sales for each region (NA, EU, JP, Other):

In [206]:
# Sales by regions: Compare NA, EU, JP, and Other sales.
regions=['na_sales','eu_sales','jp_sales','other_sales']
region_sales = cleaned_df[['na_sales','eu_sales','jp_sales','other_sales']].mean()
region_sales = region_sales.rename({     # rename region sales columns for clearer labels and better visualization
    'na_sales': 'North America',
    'eu_sales': 'Europe',
    'jp_sales': 'Japan',
    'other_sales': 'Other Regions'
})
region_sales_df = region_sales.reset_index()
region_sales_df.columns = ['Region', 'Average Sales']

print(region_sales_df)

          Region  Average Sales
0  North America       0.263330
1         Europe       0.145025
2          Japan       0.077602
3  Other Regions       0.047332

In [207]:

corr_with_global = cleaned_df[regions].corrwith(cleaned_df['global_sales']).reset_index()
corr_with_global.columns = ['Region', 'Correlation with Global Sales']


corr_with_global['Region'] = corr_with_global['Region'].replace({
    'na_sales': 'North America',
    'eu_sales': 'Europe',
    'jp_sales': 'Japan',
    'other_sales': 'Other Regions'
})

fig = px.bar(corr_with_global, x='Region', y='Correlation with Global Sales',
             title="Correlation of Regional Sales with Global Sales (Bar Chart)",
             color='Correlation with Global Sales', color_continuous_scale=['#4B0082', '#00A86B', '#BDC3C7']) # purple → green → gray)
fig.show()

In [208]:
# Sales by game_name and regions.
pivot = pd.pivot_table(cleaned_df, values=['na_sales','eu_sales','jp_sales','other_sales','global_sales'],index='name',aggfunc='sum')

top10_sales_regions = pivot.sort_values(by='global_sales', ascending=False).head(10)
top10_sales_regions

,eu_sales,global_sales,jp_sales,na_sales,other_sales
name,,,,,
Wii Sports,28.96,82.53,3.77,41.36,8.45
Grand Theft Auto V,23.42,56.57,1.42,23.84,7.90
Super Mario Bros.,4.88,45.31,6.96,32.48,0.99
Tetris,2.95,35.84,6.03,26.17,0.69
Mario Kart Wii,12.76,35.52,3.79,15.68,3.29
Wii Sports Resort,10.93,32.77,3.28,15.61,2.95
Pokemon Red/Pokemon Blue,8.89,31.37,10.22,11.27,1.00
Call of Duty: Black Ops,9.35,30.82,0.59,17.57,3.31
Call of Duty: Modern Warfare 3,11.15,30.59,0.62,15.54,3.29
New Super Mario Bros.,9.14,29.80,6.50,11.28,2.88

##### Sales by Platform:

In [209]:
# Create a pivot table to summarize global sales by platform.
pivot = pd.pivot_table(cleaned_df,values='global_sales', index='platform',aggfunc='sum')
print(pivot)

          global_sales
platform
2600             97.08
3DO               0.10
3DS             259.09
DC               15.97
DS              807.10
GB              255.45
GBA             318.50
GC              199.36
GEN              30.78
GG                0.04
N64             218.88
NES             251.07
NG                1.44
PC              260.30
PCFX              0.03
PS              730.68
PS2            1255.64
PS3             939.43
PS4             314.23
PSP             294.30
PSV              54.12
SAT              33.59
SCD               1.87
SNES            200.05
TG16              0.16
WS                1.42
Wii             908.13
WiiU             82.16
X360            971.63
XB              258.26
XOne            159.44

In [210]:
# Count each rating per each platform
rating_counts = cleaned_df.groupby('platform')['rating'].value_counts().sort_values(ascending=False).head(10)
rating_counts_df = rating_counts.reset_index()

print(rating_counts_df)

  platform rating  count
0       DS      E    877
1      PS2      T    576
2      PS2      E    556
3      Wii      E    503
4      GBA      E    426
5     X360      T    343
6      PS3      T    336
7       PC      T    297
8     X360      M    294
9       XB      T    292

In [211]:
pivot = pd.pivot_table(
    cleaned_df,
   
    index='rating',
    columns='platform',   # ratings become columns
    aggfunc='size',     # count occurrences
    fill_value=0
)
pivot

platform,3DS,DC,DS,GBA,GC,PC,PS,PS2,PS3,PS4,PSP,PSV,Wii,WiiU,X360,XB,XOne
rating,,,,,,,,,,,,,,,,,
AO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
E,92,3,877,426,230,138,116,556,211,54,188,22,503,35,247,248,45
E10+,76,0,259,25,31,76,0,125,140,40,106,28,242,42,168,31,31
EC,0,0,2,0,1,2,0,1,0,0,0,0,2,0,0,0,0
K-A,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0
M,12,1,10,7,38,256,20,223,265,76,49,33,33,15,294,161,70
RP,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0
T,48,10,126,64,169,297,71,576,336,85,201,68,222,13,343,292,40

In [212]:

# Heatmap visualization
fig_heatmap = px.imshow(
    pivot,
    labels=dict(x="Platform", y="Rating", color="Avg Global Sales"),
    title="Average Global Sales by Genre and Platform (Heatmap)",
    color_continuous_scale=[ '#BDC3C7', '#00A86B', '#4B0082']  # gray → green → purple
)
fig_heatmap.show()

In [213]:
# Most Popular platform based on global sales (Wii , GBA , PC, etc...)
platform_sales_top10 = cleaned_df.groupby('platform')['global_sales'].count().sort_values(ascending=False).head(10).reset_index()
print(platform_sales_top10.head(10))

  platform  global_sales
0      PS2          2161
1       DS          2152
2      PS3          1331
3      Wii          1320
4     X360          1262
5      PSP          1209
6       PS          1197
7       PC           974
8       XB           824
9      GBA           822

In [214]:
fig = px.bar(
    platform_sales_top10,
    x='global_sales',
    y='platform',

    title='Top 10 Platforms by Global Sales (Bar Chart)',
    labels={'global_sales':'Global Sales (millions)', 'platform':'Platform'},
    template='plotly_white'
)

fig.show()

##### Sales by Genre:

In [215]:
# Most profitable game genres 
genre_sales = cleaned_df.groupby('genre')['global_sales'].sum().sort_values(ascending=False).head(10)
genre_sales_df = genre_sales.reset_index()
print(genre_sales_df)

          genre  global_sales
0        Action       1745.27
1        Sports       1332.00
2       Shooter       1052.94
3  Role-Playing        934.40
4      Platform        828.08
5          Misc        803.18
6        Racing        728.90
7      Fighting        447.48
8    Simulation        390.42
9        Puzzle        243.02

In [216]:
fig = px.scatter(
    genre_sales_df,
    x="genre",
    y="global_sales",
    size="global_sales",       # bubble size reflects sales
    color="genre",             # color by genre, it's optional
    title="Top 10 Most Profitable Game Genres (Scatter/Bubble)",
    labels={"global_sales":"Global Sales (millions)", "genre":"Genre"},
    template="plotly_white",
    trendline="ols" 
       
)

fig.show()

In [217]:
# Count frequency of each genre
genre_count = cleaned_df['genre'].value_counts(ascending=False).reset_index()
genre_count

           genre  count
0         Action   3370
1         Sports   2348
2           Misc   1750
3   Role-Playing   1500
4        Shooter   1323
5      Adventure   1303
6         Racing   1249
7       Platform    888
8     Simulation    874
9       Fighting    849
10      Strategy    683
11        Puzzle    580

In [218]:
top10_profitable_game = (
    cleaned_df.groupby(['genre','game_age_category'])['global_sales']
    .mean()
    .reset_index()
    .sort_values(by='global_sales', ascending=False)
    .head(10)
)

fig = px.bar(
    top10_profitable_game,
    x='game_age_category',
    y='global_sales',
    color='game_age_category',
    title="Top 10 Most Profitable Game Genres (Bar Chart)",
    labels={'global_sales':'Average Global Sales (millions)', 'genre':'Genre','game_age_category':'G_Age_Cat'},
    template='plotly_white',facet_col='genre'
)

fig.show()

##### Game names by user_score:

In [219]:
top10_gamesbyuser_score=df[['user_score','genre']].sort_values(by='user_score',ascending=False).head(10)
top10_gamesbyuser_score

       user_score         genre
14414         9.7  Role-Playing
8976          9.6  Role-Playing
3417          9.6    Simulation
10106         9.5        Action
11120         9.5        Puzzle
16631         9.5        Racing
1645          9.5  Role-Playing
16550         9.5        Sports
5920          9.5        Sports
1068          9.4        Action

In [220]:
# Relationship between user scores and global sales for the top 10 games, with bubbles sized by sales and colored by genre
top10_score_sales = (
    cleaned_df.sort_values(by="user_score", ascending=False)
    .head(10)
)

# Scatter bubble chart with trendline
fig_score_sales_top10 = px.scatter(
    top10_score_sales,
    x="user_score",
    y="global_sales",
    size="global_sales",   # bubble size reflects sales
    color="genre",
    hover_name="name",     # show game name on hover
    title="Top 10 Games by User Score vs Global Sales (with Trendline)",
    labels={"user_score":"User Score", "global_sales":"Global Sales (millions)"},
    template="plotly_white",
    trendline="ols"        # regression line
)

fig_score_sales_top10.show()

##### Sales by Publisher:

In [221]:
# Top performing publishers
publisher_sales= cleaned_df.groupby('publisher')['global_sales'].count().sort_values(ascending=False)
print(publisher_sales.head())

publisher
electronic arts                 1356
activision                       985
namco bandai games               939
ubisoft                          933
konami digital entertainment     834
Name: global_sales, dtype: int64

In [222]:
fig_publisher_sales = px.bar(
    publisher_sales.head(5).reset_index(),
    x='global_sales',
    y='publisher',
    orientation='h',
    title='Top 10 Publishers by Global Sales (Bar Chart)',
    labels={'global_sales':'Global Sales (millions)', 'publisher':'Publisher'},
    template='plotly_white'
)
fig_publisher_sales

##### Yearly Sales Trends:

In [223]:
# See how game sales change over time.

years_sales=cleaned_df.groupby('year_of_release')['global_sales'].sum().sort_values(ascending=False)
print(years_sales.head())

year_of_release
2008.0    671.79
2009.0    658.88
2007.0    605.37
2010.0    590.59
2006.0    518.22
Name: global_sales, dtype: float64

In [224]:
# Line Chart of Sales Over Year Time 

fig_line_sales_year = px.line(
    cleaned_df.groupby('year_of_release')['global_sales'].sum().reset_index(),
    x='year_of_release',
    y='global_sales',
    title='Global Sales Over Time (Line Chart)',
    labels={'year_of_release':'Year of Release', 'global_sales':'Global Sales (millions)'},
    template='plotly_white', 
   
)

fig_line_sales_year.show()

Number of Games Released per Year

In [225]:
games_per_year=cleaned_df.groupby('year_of_release')['name'].count().reset_index().sort_values(by='name', ascending=False).rename(columns={'name':'game_count'})
games_per_year

    year_of_release  game_count
28           2008.0        1427
29           2009.0        1426
30           2010.0        1255
27           2007.0        1197
31           2011.0        1136
26           2006.0        1006
25           2005.0         939
22           2002.0         829
23           2003.0         775
24           2004.0         762
32           2012.0         653
35           2015.0         606
34           2014.0         581
33           2013.0         544
36           2016.0         502
21           2001.0         482
18           1998.0         379
20           2000.0         350
19           1999.0         338
17           1997.0         289
16           1996.0         263
15           1995.0         219
14           1994.0         121
13           1993.0          60
1            1981.0          46
12           1992.0          43
11           1991.0          41
2            1982.0          36
6            1986.0          21
9            1989.0          17
3            1983.0          17
10           1990.0          16
7            1987.0          16
8            1988.0          15
4            1984.0          14
5            1985.0          14
0            1980.0           9
37           2017.0           3
38           2020.0           1

In [226]:
# Scatter plot - Number of Games Released per Year
fig = px.scatter(
    games_per_year,
    x='year_of_release',
    y='game_count',
    trendline='ols',   # add regression line
    title="Number of Games Released per Year with Trendline",
    labels={'year_of_release':'Year of Release', 'game_count':'Number of Games'},
    template='plotly_white'
)

fig.show()

In [227]:
# Genre vs Platform pivot table
genre_platform_sales = cleaned_df.pivot_table(
    index='genre',
    columns='platform',
    values='global_sales',
    aggfunc='mean'
)
genre_platform_sales

platform,2600,3DO,3DS,DC,DS,GB,GBA,GC,GEN,GG,...,SAT,SCD,SNES,TG16,WS,Wii,WiiU,X360,XB,XOne
genre,,,,,,,,,,,,,,,,,,,,,
Action,0.480984,NaN,0.310266,0.420000,0.331471,1.320000,0.333892,0.374653,0.913333,NaN,...,0.216667,NaN,0.840000,NaN,NaN,0.483165,0.297656,0.742074,0.317935,0.439412
Adventure,0.850000,0.06,0.128947,0.227273,0.192857,3.432000,0.386316,0.296500,0.095000,NaN,...,0.160000,NaN,0.375000,0.14,NaN,0.214819,0.053333,0.311250,0.117692,0.192143
Fighting,0.620000,NaN,0.755000,0.152500,0.197500,NaN,0.183043,0.438810,1.180000,NaN,...,0.274839,NaN,1.078000,NaN,NaN,0.556190,1.254000,0.574462,0.282292,0.344286
Misc,0.716000,NaN,0.203333,NaN,0.347110,1.668750,0.329545,0.464722,0.030000,NaN,...,0.080000,0.05,0.295294,NaN,NaN,0.772750,0.566818,0.720787,0.208261,0.391579
Platform,1.474444,NaN,1.161429,1.270000,0.834286,2.890000,0.551408,0.392603,2.207143,0.04,...,0.152000,1.50,2.525000,NaN,NaN,1.533103,1.267059,0.452800,0.197143,0.188000
Puzzle,1.334545,0.02,0.277500,NaN,0.350508,3.164667,0.315122,0.361538,NaN,NaN,...,0.200000,NaN,0.490769,NaN,NaN,0.279455,0.330000,0.121429,0.060000,NaN
Racing,0.485000,NaN,1.358182,0.441667,0.568657,2.275000,0.293750,0.347460,0.260000,NaN,...,0.300000,0.07,1.498889,NaN,NaN,0.647849,2.623333,0.625000,0.256016,0.489500
Role-Playing,NaN,NaN,0.957841,0.170000,0.622200,4.201905,0.879589,0.487037,0.090000,NaN,...,0.221176,0.06,0.728600,NaN,0.305,0.391429,0.412857,0.950800,0.587391,0.753571
Shooter,1.103333,NaN,0.184286,0.110000,0.188571,1.200000,0.090000,0.283958,0.130000,NaN,...,0.180909,NaN,0.607000,0.02,NaN,0.433077,0.597000,1.364433,0.481439,1.589211
Simulation,0.450000,0.02,0.884839,0.520000,0.458768,0.710000,0.328333,0.715833,NaN,NaN,...,0.161429,NaN,0.625556,NaN,NaN,0.414138,0.200000,0.354500,0.296250,0.172500
Sports,0.285833,NaN,0.238077,0.366000,0.212230,1.005556,0.186477,0.231727,1.066667,NaN,...,0.174375,NaN,0.364694,NaN,NaN,1.110038,0.398750,0.638018,0.319235,0.704474
Strategy,NaN,NaN,0.140000,NaN,0.188228,1.150000,0.413889,0.392727,0.190000,NaN,...,0.180000,0.14,0.332000,NaN,0.100,0.201200,0.410000,0.358214,0.132381,0.140000

In [228]:
genre_platform_sales_reset = genre_platform_sales.reset_index().melt(  #eshapes a DataFrame from wide format (platforms as separate columns) into long format (platforms as rows).
    id_vars='genre',
    var_name='platform',
    value_name='avg_sales'
)

fig_bar = px.bar(
    genre_platform_sales_reset,
    x='genre',
    y='avg_sales',
    color='platform',
    title="Average Global Sales by Genre and Platform (Stacked Bar)",
    labels={'avg_sales':'Avg Global Sales', 'genre':'Genre'},
    template='plotly_white'
)
fig_bar.show()

##### Genre or platform preference Analysis:

In [229]:

fig_heatmap = px.imshow(
    genre_platform_sales,
    labels=dict(x="Platform", y="Genre", color="Avg Global Sales"),
    title="Average Global Sales by Genre and Platform (Heatmap)",
    color_continuous_scale=my_colors 
)
fig_heatmap.show()

In [231]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from sklearn.ensemble import RandomForestRegressor

features = ["genre", "platform", "publisher", "user_score"]
X = df[features]
y = df["global_sales"]

pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ("scaler", RobustScaler()),
    ("model", RandomForestRegressor())
])

pipeline.fit(X, y)
joblib.dump(pipeline, "video_game_model.pkl")

['video_game_model.pkl']

In [236]:
%%writefile video_game_app.py

import streamlit as st
import pandas as pd
import plotly.express as px
import joblib 
from sklearn.preprocessing import OneHotEncoder,RobustScaler 
from category_encoders import BinaryEncoder 
from sklearn.ensemble import RandomForestRegressor 

# re-style the multiselect tags to look more polished, with gradient colors.
st.markdown("""
<style>

/* Target multiselect selected values (the pills) */
span[data-baseweb="tag"] {
    background: linear-gradient(90deg, #c084fc, #ffb3b3, #a7f3d0) !important; 
    /* light purple → soft red → light green */
    color: #1f2937 !important;           /* dark text for readability */
    border: none !important;
    box-shadow: 0 0 6px rgba(255, 179, 179, 0.3); /* soft glow effect */
}

/* Hover effect */
span[data-baseweb="tag"]:hover {
    background: linear-gradient(90deg, #b794f4, #ffc7c7, #86efac) !important;
}

/* Remove default red “x” color */
span[data-baseweb="tag"] svg {
    color: #1f2937 !important;
}

</style>
""", unsafe_allow_html=True)



# Display a title with HTML/CSS styling
st.markdown(
    """
<h1 style="
    text-align: center;
    font-size: 95px;
    background: linear-gradient(90deg, #7b2ff7, #ff4d4d, #00c9a7);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-weight: bold;
">
    Video Game Sales Dashboard 
</h1>
    """,
    unsafe_allow_html=True
)

# Display header image 

from PIL import Image

img = Image.open("image.png")
img = img.resize((4000, 1000))

col1, col2, col3 = st.columns([0.05, 9, 0.05])
with col2:
    st.image(img, use_container_width=True)



# --------------------------------------------------------------------------------------------------
# Page Config
st.set_page_config(
    page_title="Video Game Sales Dashboard",
    layout="wide"
)



# Load Data
@st.cache_data
def load_data():
    df = pd.read_csv("clean_video_games.csv")
    return df

df = load_data()

# Sidebar
# Page Navigation
st.sidebar.markdown(
    "<h2 style='font-size:28px'>Navigation</h2>", unsafe_allow_html=True
)

page = st.sidebar.radio(
    " ",# to keep the radio label empty
    [
        "Overview",
        "Analysis",
        "Predictions"

    ]
)


# Add a separator line
st.sidebar.markdown("---")
# --------------------------------------------------------------------------------------------------
# Sidebar Filters

st.sidebar.markdown(
 "<h3 style='font-size:24px'>Data Filters</h3>", unsafe_allow_html=True )

#genre_filter = st.sidebar.multiselect(
   # "Select Genre", options=df["genre"].unique(), default=df["genre"].unique())


with st.sidebar.expander("Select Genre", expanded=False):
    genre_filter = st.multiselect(
        label="",
        options=df["genre"].unique(),
        default=df["genre"].unique()
    )

age_rating_map = { #  # Mapping shorthand ratings to full names 
    "E": "Everyone",
    "E10+": "Everyone 10+",
    "T": "Teen",
    "M": "Mature 17+",
    "AO": "Adults Only 18+",
    "K-A": "Kids to Adults"
}

#rating_filter = st.sidebar.multiselect(
 #   "Select Age Rating",   options=list(age_rating_map.keys()),default=list(age_rating_map.keys()), 
 #   format_func=lambda x: f"{x} — {age_rating_map[x]}")

with st.sidebar.expander("Select Age Rating", expanded=False):
    rating_filter = st.multiselect(
        label="",
        options=list(age_rating_map.keys()),
        default=list(age_rating_map.keys()),
        format_func=lambda x: f"{x} — {age_rating_map[x]}"
    )



#platform_filter = st.sidebar.multiselect(
   # "Select Platform", options=df["platform"].unique(), default=df["platform"].unique())

with st.sidebar.expander("Select Platform", expanded=False):
    platform_filter = st.multiselect(
        label="",
        options=df["platform"].unique(),
        default=df["platform"].unique()
    )


#user_score_filter = st.sidebar.slider(
 #   "Set User Score Range",
  #  float(df["user_score"].min()),
   # float(df["user_score"].max()),
    #(float(df["user_score"].min()), float(df["user_score"].max())),
#)
with st.sidebar.expander("Set User Score Range", expanded=False):
    user_score_filter = st.slider(
        label="",
        min_value=float(df["user_score"].min()),
        max_value=float(df["user_score"].max()),
        value=(
            float(df["user_score"].min()),
            float(df["user_score"].max())
        ),
        step=0.1
    )


    
#year_filter = st.sidebar.slider(
 #   "Set Year of Release Range",
  #  int(df["year_of_release"].min()),
   # int(df["year_of_release"].max()),
    #(int(df["year_of_release"].min()), int(df["year_of_release"].max())),
#)


with st.sidebar.expander("Set Year of Release Range", expanded=False):
    year_filter = st.slider(
        label="",
        min_value=int(df["year_of_release"].min()),
        max_value=int(df["year_of_release"].max()),
        value=(
            int(df["year_of_release"].min()),
            int(df["year_of_release"].max())
        )
    )


# --------------------------------------------------------------------------------------------------
# Apply Filters
filtered_df = df[
    (df["genre"].isin(genre_filter)) &
    (df["rating"].isin(rating_filter)) &
    (df["platform"].isin(platform_filter)) &
   
    (df["user_score"].between(user_score_filter[0], user_score_filter[1])) &
    (df["year_of_release"].between(year_filter[0], year_filter[1]))
]

# --------------------------------------------------------------------------------------------------

# MAIN PAGE
if page == "Overview":

    st.title("Dashboard Overview")

    st.markdown("""
    The Video Game Sales **Dashboard** is an interactive tool for analyzing global video game sales and identifying market trends. Users can filter by Genre, Age Rating, Platform, User Score, and Release Year to explore performance across the gaming industry.
    """)

 


    tab1, tab2, tab3= st.tabs([
        "Dataset Overview",
        "Key Performance Indicators",
        "Data Summary"
    ])
    with tab1:
        st.subheader("Dataset Overview")

        st.markdown("""
        The **Dataset** provides comprehensive data on video game sales, and user insights globally, including details such as the game's name, platform, year of release, genre, publisher, sales in different regions, developer, and age rating.
    """)

    # Initialize number of rows ...................
        if "rows" not in st.session_state:
            st.session_state.rows = 5

    # Display dataframe
        st.dataframe(filtered_df.head(st.session_state.rows))

    # Show more button .......................
        if st.button("🔽 Show More Rows"):
            st.session_state.rows += 10


    
    with tab2:
        st.subheader("Key Performance Indicators (KPIs)")

        # KPI calculations
        Total_Games = filtered_df.shape[0]
        Total_Global_Sales = filtered_df["global_sales"].sum()
        Global_Sales_Rate = Total_Global_Sales / Total_Games if Total_Games else 0
        Top_Selling_Game = filtered_df.groupby('name')['global_sales'].sum().idxmax() if Total_Games else "N/A"
        Avg_User_Score = filtered_df["user_score"].mean()
        Most_Popular_Platform = filtered_df['platform'].mode()[0] if Total_Games else "N/A"
        Top_Genre = filtered_df['genre'].mode()[0] if Total_Games else "N/A"
        # Most_Age_Rating= filtered_df['rating'].mode()[0] if Total_Games else "N/A"
        Most_Age_Rating = (age_rating_map.get(filtered_df['rating'].mode()[0], "N/A") if Total_Games else "N/A"
    )

        # Display KPIs in columns with two rows
        col1, col2, col3, col4 = st.columns(4)
        col5, col6, col7, col8 = st.columns(4)

    # Numeric KPIs
        col1.metric("🕹️ Total Games", Total_Games)
        col2.metric("💰 Total Global Sales (Millions)", f"{Total_Global_Sales:.2f}")
        col3.metric("🔢 Global Sales Rate", f"{Global_Sales_Rate:.2%}")
        col4.metric("🎯 Average User Score", f"{Avg_User_Score:.2f}")
        
    # Categorical KPIs
        col5.metric("🏆 Top Selling Game", Top_Selling_Game)
        col6.metric("🌟 Most Popular Genre", Top_Genre)
        col7.metric("🎮 Most Popular Platform", Most_Popular_Platform)
        col8.metric("👶 Most Age Rating", Most_Age_Rating)
        
    

    with tab3:   # Make sure tab3 = "🧾 Data Summary"
        
    
        st.subheader("Column Descriptions")
       

        column_data = {
            "Column": [
                "Index", "Name", "Platform", "Year_of_Release", "Genre", "Publisher",
                "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales", "User_Score",
                "Developer", "Rating", "Sales_Category","Game_Age","Game_Age_Category"
            ],
            "Description": [
                "Unique identifier for each video game record.",
                "The name of the video game.",
                "The platform on which the game is available (PC, PS4, Xbox, etc.).",
                "The year in which the game was released.",
                "The genre of the game (Action, Sports, etc.).",
                "The company that published the game.",
                "Sales in North America (millions).",
                "Sales in Europe (millions).",
                "Sales in Japan (millions).",
                "Sales in other regions (millions).",
                "Total global sales (millions).",
                "Average score given by users.",
                "The company that developed the game.",
                "ESRB rating (E, T, M, etc.).",
                "Sales performance category (best_seller, medium, low)",
                "Number of years since the game’s release (current year − release year)",
                "Binned game age derived from release year (New, Recent, Old)"
            ]
        }

        df_desc = pd.DataFrame(column_data)
        st.dataframe(df_desc, use_container_width=True)

        
# --------------------------------------------------------------------------------------------------
# ANALYSIS PAGE
elif page == "Analysis":

    st.title("Exploratory Data Analysis (EDA)")

    tab1, tab2, tab3 , tab4, tab5= st.tabs([
        "Univariate Analysis",
        "Bivariate Analysis",
        "Multivariate Analysis", 
        "Insights Q&A",
        "Recommendations"
    ])

    # --------------------------
    # Univariate Analysis
    with tab1:
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Total Global Sales by Genre")

            sales_genre = (
                filtered_df.groupby('genre')['global_sales']
                .sum()
                .reset_index()
                .sort_values(by='global_sales', ascending=False).head(10)
            )

            fig_genre_pie = px.pie(
                sales_genre,
                names='genre',
                values='global_sales',
                labels={'genre':'Genre','global_sales':'Total Global Sales (Millions)'},
                color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ])   

            fig_genre_pie.update_traces(
                    textinfo='value',   # show both genre and global sales
                    textposition='inside'
)
            st.plotly_chart(fig_genre_pie, use_container_width=True)
            st.caption(""" 👉 Action and Sports genres dominate global sales, indicating strong market preference.""")
        
        with col2:
            st.subheader("Games Released by Year")

            games_per_year = (
                filtered_df.groupby('year_of_release')['name']
                .count()
                .reset_index()
                .sort_values(by='name', ascending=False).head(10)
                .rename(columns={'name':'game_count'})
            )

            fig_year_pie = px.pie(
                games_per_year,
                names='year_of_release',
                values='game_count',
                labels={
                    'year_of_release': 'Year of Release',
                    'game_count': 'Number of Games'
                },color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ]
            )

            # Show Year inside pie instead of %
            fig_year_pie.update_traces(
                textinfo='value',
                textposition='inside'
            )

            st.plotly_chart(fig_year_pie, use_container_width=True)
            st.caption(" 👉 Game releases vary over time, with noticeable growth periods that reflect the expansion of the gaming industry.""")
        

        
        st.divider()

        st.subheader("Top 10 Publishers by Global Sales")

        # Aggregate global sales by publisher
        sales_publisher = (
            filtered_df.groupby('publisher')['global_sales']
            .sum()
            .reset_index()
            .sort_values(by='global_sales', ascending=False)
        )

        # Select Top 10 publishers
        top_publishers = sales_publisher.head(10)

        # Bar chart for Top 10 publishers
        fig_publisher_bar = px.bar(
            top_publishers,
            x='publisher',
            y='global_sales',
            color='publisher',labels={'publisher':'Publisher','global_sales':'Global Sales (Millions)'},
            color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ]
        )

        st.plotly_chart(fig_publisher_bar, use_container_width=True)
        st.caption(" 👉 Top 10 Publishers dominate the global sales, highlighting a highly concentrated and competitive market.")
        
        st.divider()

        
        st.subheader("Distribution of User Scores")

        fig_hist = px.histogram(
            filtered_df,
            x="user_score",
            nbins=20,
            marginal="box",  # adds boxplot on top 
            opacity=0.85,
            color_discrete_sequence = ["#2d004d", "#5a189a", "#c48df5", "#e0c3fc", "#ffa8a8", "#d1f2eb", "#b7f5d3", "#38b000", "#004b23"], 
        )

        fig_hist.update_layout(
            xaxis_title="User Score",
            yaxis_title="Number of Games",
            bargap=0.1
        )

        st.plotly_chart(fig_hist, use_container_width=True)
        st.caption(" 👉 Most games receive moderate to high user scores, reflecting generally positive user feedback." )
    # --------------------------------------------------------------------------------------------------
    # Bivariate Analysis
    with tab2:


        st.subheader("Number of Games Released per Year with Trendline")

        # Scatter plot - Number of Games Released per Year
        fig_gyear = px.scatter(
            games_per_year,
            x='year_of_release',
            y='game_count',
            trendline='ols',   # add regression line,
            color_discrete_sequence = ["#3f145f", "#55307a","#6b468e","#805ea3","#9a7bb7","#b49acb","#cbb3da" ],
            labels={'year_of_release':'Year of Release', 'game_count':'Number of Games'},
            template='plotly_white'
        )


        st.plotly_chart(fig_gyear, use_container_width=True)
        st.caption("👉 Game production has grown over the years, despite some fluctuations." )
 


        st.divider()

        st.subheader("Global Sales Distribution by User Score (Top 10 Genres)")

    # Get Top 10 genres by total global sales
        top_genres = (
        filtered_df.groupby("genre")["global_sales"]
        .sum()
        .sort_values(ascending=False)
        .head(10)
        .index
    )

        filtered_top10 = filtered_df[filtered_df["genre"].isin(top_genres)]

        fig_violin = px.violin(
        filtered_top10,
        x="genre",              # categorical axis (e.g., genre)
        y="global_sales",       # numeric axis
        color="genre",          # color by genre
        box=True,               # add embedded boxplot
        points="all",           # show all individual points
        hover_data=["name", "user_score"],  # extra info on hover
        labels={
            "genre": "Genre",
            "global_sales": "Global Sales (Millions)"
        },
        color_discrete_sequence=[
            "#2d004d", "#5a189a", "#c77dff",
            "#ff4d4d", "#ff8787",
            "#80ed99", "#38b000",
            "#b7f5d3", "#004b23", "#6a0dad"
        ]
    )

        st.plotly_chart(fig_violin, use_container_width=True)

        st.caption("👉 Sales performance varies across genres, with some genres achieving higher global sales." )


        st.divider()

        st.subheader("Global Sales Trends of Top 3 Platforms")

        # Aggregate global sales by platform and year
        sales_platform_year = (
            filtered_df.groupby(['year_of_release', 'platform'])['global_sales']
            .sum()
            .reset_index()
        )

        # Compute total sales per platform (to find top 3 overall)
        top_platforms = (
            sales_platform_year.groupby('platform')['global_sales']
            .sum()
            .reset_index()
            .sort_values(by='global_sales', ascending=False)
            .head(3)['platform']
        )

        # Filter only top 3 platforms
        sales_top_platforms = sales_platform_year[
            sales_platform_year['platform'].isin(top_platforms)
        ]

        # Line chart: sales trend over years
        fig_platform_line = px.line(
            sales_top_platforms,
            x='year_of_release',
            y='global_sales',
            color='platform',
            labels={'year_of_release':'Year of Release','platform':'Platform','global_sales':'Total Global Sales (Millions)'},
            color_discrete_sequence = ["#2d004d", "#38b000",  "#ff4d4d" ],markers=True,
        )

        st.plotly_chart(fig_platform_line, use_container_width=True)

        st.caption("👉 The top 3 platforms show clear sales peaks across different years, reflecting shifts in console popularity and changes in user demand over time.")
          
    # Multivariate Analysis
       
     
    
    with tab3:
        st.subheader("Global Sales over Years by Top Genres")


        # Get top 3 games by global sales
        top10_games = (
        filtered_df.groupby('genre')['global_sales'].sum().sort_values(ascending=False).head(3).index)

        # Filter dataset
        filtered_df2 = filtered_df[filtered_df['genre'].isin(top10_games)]


        sales_year_genre = filtered_df2.groupby(['year_of_release', 'genre'])['global_sales'].sum().reset_index()
        fig_multi = px.line(sales_year_genre, x='year_of_release', y='global_sales',
                            color='genre', markers=True,  color_discrete_sequence=[

        "#4c1d95",  # purple
        "#b91c1c",  # red
        "#065f46",  # green
        "#6d28d9",  # violet
        "#6ee7b7",  # light green
        "#8b5cf6",  # light purple
        "#10b981",  # green
        "#ef4444"   # red
    ],
                            labels={'year_of_release':'Year of Release', 'genre':'Genre','global_sales':'Global Sales (Millions)' },)
        st.plotly_chart(fig_multi, use_container_width=True)
        st.caption("👉 Global sales by genre show steady year‑over‑year growth followed by a sharp decline.")
      

        st.divider()

        st.subheader("Global Sales by Genre and Age Rating")

        # Mapping shorthand ratings to full names
        rating_map = {
            "E": "Everyone",
            "E10+": "Everyone 10+",
            "M": "Mature",
            "EC": "Early Childhood",
            "RP": "Rating Pending",
            "K-A": "Kids to Adults",
            "AO": "Adults Only",
            "T": "Teen"
        }

        # Aggregate sales by genre and rating
        sales_platform_rating = (
            filtered_df.groupby(['genre', 'rating'])['global_sales']
            .sum()
            .reset_index()
        )

        # Map abbreviations to full names
        sales_platform_rating['rating'] = sales_platform_rating['rating'].map(rating_map)

        # Define rating order
        rating_order = [
            "Everyone",
            "Everyone 10+",
            "Mature",
            "Early Childhood",
            "Rating Pending",
            "Kids to Adults",
            "Adults Only",
            "Teen"
        ]

        # Assign categorical order
        sales_platform_rating['rating'] = pd.Categorical(
            sales_platform_rating['rating'],
            categories=rating_order,
            ordered=True
        )

        # Get Top 5 genres
        top_genres = (
            sales_platform_rating.groupby('genre')['global_sales']
            .sum()
            .sort_values(ascending=False)
            .head(5)
            .index
        )

        # Filter Top 3
        sales_platform_rating = sales_platform_rating[
            sales_platform_rating['genre'].isin(top_genres)
        ]

        # Plot
        fig_platform_rating = px.bar(
            sales_platform_rating,
            x='genre',
            y='global_sales',
            color='rating',
            barmode='group',
            color_discrete_sequence=[

        "#4c1d95",  # purple
        "#b91c1c",  # red
        "#065f46",  # green
        "#6d28d9",  # violet
        "#6ee7b7",  # light green
        "#8b5cf6",  # light purple
        "#10b981",  # green
        "#ef4444"   # red
    ],
            labels={
                'rating': 'Age Rating',
                'genre': 'Genre',
                'global_sales': 'Global Sales (Millions)'
            }
        )

        st.plotly_chart(fig_platform_rating, use_container_width=True)

        st.caption(
            "👉 Top 5 genres dominate global sales, with 'Everyone' and 'Teen' ratings contributing the most across genres."
        )


        st.divider()
    

        st.subheader("Global Sales Heatmap by Genre, Region, and Age Rating")
        
   

        # Melt the regional sales into long format
        sales_region = filtered_df.melt(
            id_vars=['genre', 'rating'],
            value_vars=['na_sales', 'eu_sales', 'jp_sales', 'other_sales'],
            var_name='region',
            value_name='sales'
        )

        # Rename region values for display
        region_map = {
            'na_sales': 'North America',
            'eu_sales': 'Europe',
            'jp_sales': 'Japan',
            'other_sales': 'Other Regions'
        }

        sales_region['region'] = sales_region['region'].map(region_map)

        # Aggregate sales by genre, rating, and region
        sales_region_grouped = (
            sales_region.groupby(['genre', 'rating', 'region'])['sales']
            .sum()
            .reset_index()
        )

        # Get Top 5 genres by total sales
        top_genres = (
            sales_region_grouped.groupby('genre')['sales']
            .sum()
            .sort_values(ascending=False)
            .head(5)
            .index
        )

        # Filter only Top 5 genres
        sales_region_grouped = sales_region_grouped[
            sales_region_grouped['genre'].isin(top_genres)
        ]

        # Heatmap
        fig_facet = px.density_heatmap(
            sales_region_grouped,
            x='genre',
            y='rating',
            z='sales',
            facet_col='region',
            color_continuous_scale=[
                "#2e1065",
                "#4c1d95",
                "#6d28d9",
                "#9333ea",
                "#c026d3",
                "#db2777",
                "#e11d48"
                    ],
            labels={
                'rating': 'Age Rating',
                'genre': 'Genre',
                'region': 'Region',
                'sales': 'Sales'
            }
        )

        st.plotly_chart(fig_facet, use_container_width=True)

        st.caption(
            "👉 Top genres show different regional preferences, with Action and Sports dominating globally and Role-Playing stronger in Japan."
        )
    

    with tab4:
        st.subheader("Insights Q&A")

        question = st.selectbox(
            "Select a business question:",
            [
                "Which Top Video Game per platform?",
                "Which regions generate the most sales?",
                "Genre distribution per region?",
                "What percentage of 'UNKNOWN' publisher from total games?"
            ]
        )

        if question == "Which Top Video Game per platform?":
            # Top-selling game per region (using global_sales)
            region_sales = (
                filtered_df.groupby(["platform", "name"])["global_sales"]
                .sum()
                .reset_index()
                .sort_values(by="global_sales", ascending=False)
            )
            top1_per_platform = region_sales.groupby("platform").head(1)

            fig_top1_platform = px.bar(
                top1_per_platform,
                x="platform",
                y="global_sales",
                color="name",
                text="name",
                title="Top Game per Platform"
            )
            st.plotly_chart(fig_top1_platform)
            st.markdown("➡️ This chart shows the single most globally successful game on each platform.")

        elif question == "Which regions generate the most sales?":
            region_totals = {
                "NA": filtered_df["na_sales"].sum(),
                "EU": filtered_df["eu_sales"].sum(),
                "JP": filtered_df["jp_sales"].sum(),
                "Other": filtered_df["other_sales"].sum()
            }
            region_df = pd.DataFrame(list(region_totals.items()), columns=["Region", "Sales"])

            fig_region_sales = px.bar(
                region_df,
                x="Region",
                y="Sales",
                title="Total Sales by Region",
                text_auto=True,
                color="Sales"
            )
            st.plotly_chart(fig_region_sales)
            st.markdown("➡️ Regions with the highest sales represent strong demand centers.")

        elif question == "Genre distribution per region?":
            genre_region = (
                filtered_df.groupby(["genre", "platform"])["global_sales"]
                .sum()
                .reset_index()
            )
            fig_genre_region = px.bar(
                genre_region,
                x="platform",
                y="global_sales",
                color="genre",
                barmode="group",
                title="Genre Distribution per Platform",
                text_auto=True
            )
            st.plotly_chart(fig_genre_region)
            st.markdown("➡️ Genre-based demand varies across platforms — tailor strategies accordingly.")

        elif question == "What percentage of 'UNKNOWN' publisher from total games?":
            total_games = len(filtered_df)
            unknown_publishers = len(filtered_df[filtered_df["publisher"].str.lower() == "unknown"])
            percentage_unknown = (unknown_publishers / total_games * 100) if total_games > 0 else 0
            st.metric("Percentage of 'UNKNOWN' Publisher", f"{percentage_unknown:.2f}%")
            st.markdown("➡️ A significant share of records have 'UNKNOWN' publishers.")



        
    with tab5:

# =================================================


            st.title("Business Recommendations")
            st.markdown("""
        
        ### Strategic actions to enhance market performance and maximize global video game sales.

        - Focus development on Action & Sports games (since they are the most popular).  
        - Focus on family-friendly ratings to reach more players.. 
        - Improve game quality to raise user scores
        - Target high-performing years trends (release your games during the busiest times of the year when people are buying the most).
        - Emulate PS2‑era success with variety + budget‑friendly pricing.

        """)

elif page == "Predictions":

    st.title("🎮 Video Game Sales Prediction")
    st.sidebar.markdown("### Game Specifications")

    # --- Sanitize categorical columns ---
    df["genre"] = df["genre"].fillna("Unknown").astype(str)
    df["platform"] = df["platform"].fillna("Unknown").astype(str)
    df["publisher"] = df["publisher"].fillna("Unknown").astype(str)

    # Sidebar inputs
    genre = st.sidebar.selectbox("Genre", sorted(df["genre"].unique()))
    platform = st.sidebar.selectbox("Platform", sorted(df["platform"].unique()))
    publisher = st.sidebar.selectbox("Publisher", sorted(df["publisher"].unique()))
    user_score = st.sidebar.slider("User Score (0–10)", 0.0, 10.0, 7.5, 0.1)

    # Input Data Summary
    input_df = pd.DataFrame({
        "genre": [genre],
        "platform": [platform],
        "publisher": [publisher],
        "user_score": [user_score]
    })

    st.markdown("### 📋 Input Summary")
    st.table(input_df)

    if st.button("Predict Global Sales"):
        try:
            # Load the full pipeline (preprocessing + model)
            pipeline = joblib.load("video_game_model.pkl")

            # Ensure all expected columns exist
            expected_cols = pipeline.feature_names_in_
            input_df = input_df.reindex(columns=expected_cols, fill_value=0)

            # Predict
            prediction = pipeline.predict(input_df)
            st.success(f"Predicted Global Sales: {prediction[0]:.2f} million")

        except Exception as e:
            st.error(f"Prediction Error: {e}")


# Footer

st.markdown("""     ---
<div style='text-align: center; font-size: 18px; color: #999;'>

© 2026 Elaf Bahaa Aldein • All Rights Reserved • 
<a href="mailto:elafbhaa0@gmail.com" style="color:#999; text-decoration:none;">Email</a> • 
<a href="https://github.com/elafbhaa" target="_blank" style="color:#6e6e6e; text-decoration:none;">GitHub</a> • 
<a href="https://www.linkedin.com/in/elaf-bahaa-aldein-50b7552aa/" target="_blank" style="color:#0A66C2; text-decoration:none;">LinkedIn</a> •
<a href="https://wa.me/201557549995?text=Hi%20Elaf,%20I%20visited%20your%20Video%20Game%20Dashboard" 
target="_blank" style="color:#25D366; text-decoration:none;">WhatsApp
</a>
</div>
""", unsafe_allow_html=True)

Overwriting video_game_app.py

In [238]:

# Run stremlit Dashboard
! streamlit run video_game_app.py

^C